package com.dgphoenix.casino.gs.singlegames.tools.cbservtools;

/**
 * User: flsh
 * Date: 17.01.14
 */
public interface IGameController {
    int ERROR_OLD_ROUND_ID = 1;

    // prefix and postfix of returned data
    String DATABEGINNING = "<!--start of data-->";
    String DATAENDING = "<!--end of data-->";

    // errors
    String RESGENERICERROR = "ERROR";

    String RESNOTENOUGHMONEY = "NOTENOUGHMONEY";
    String RESVALIDATEERROR = "NOTENOUGHMONEY";
    String RESINTERNALERROR = "INTERNALERROR";
    String RESSESSIONERROR = "SESSIONERROR";

    String RESFATAL = "FATAL";
    String RESAPPLICATION = "APPLICATION";

    String RESINVALIDPARAMETERERROR = "INVALIDPARAMETER";
    String RESINVALIDCLIENTVERSION = "INVALIDCLIENTVERSION";
    String RESGAMEALREADYEXISTS = "GAMEALREADYEXISTS";
    String RESINCORRECTCOMMAND = "INCORRECTCOMMAND";
    String RESGAMEDISABLED = "DISABLED";

    // commands
    String CMDENTER = "ENTER";
    String CMDEXIT = "EXIT";
    String CMDCLOSEONLINEGAME = "CLOSEONLINEGAME";
    String CMDPLACEBET = "PLACEBET";
    String CMDDOBONUS = "DOBONUS";
    String CMDGETJACKPOT = "GETJACKPOT";
    String CMDGETTIME = "GETTIME";
    String CMD_PROMO_ENTER = "PROMO_ENTER";
    String CMD_GET_PROMO_MESSAGES = "GET_PROMO_MESSAGES";
    String CMD_GET_PROMO_NOTIFICATIONS = "GET_PROMO_NOTIFICATIONS";
    String CMD_NOTIFICATIONS_SHOWN = "NOTIFICATIONS_SHOWN";
    String CMDREFRESH_UNJ = "REFRESH_UNJ";
    String CMDUPDATEBALANCE = "UPDATEBALANCE";
    String CMDRESTART = "RESTART";
    String CMDDOUBLEUP = "DOUBLEUP";
    String CMDTRIPLEUP = "TRIPLEUP";
    String CMD_REFRESH_BALANCE = "REFRESHBALANCE";
    String CMD_UPDATE_EXTERNAL_SESSION = "UPDATE_EXTERNAL_SESSION";

    String CMDAUTHENTICATE = "AUTHENTICATE";
    String CMDINITSERVERAUTHENTICATE = "INITSERVERAUTHENTICATE";
    String CMDSERVERAUTHENTICATE = "SERVERAUTHENTICATE";
    String CMDABORTSTARTGAME = "ABORTSTARTGAME";
    String CMDFLASH_DEBUG = "FLASH_DEBUG";

    // input params
    String PARAMDBLINK = "DBLINK";
    String PARAMCMD = "CMD";
    String PARAMBET = "BET";
    String PARAMFLASH_LOG = "LOG";
    String PARAMPLAYERDATA = "PLAYERDATA";
    String PARAMGAME = "GAME";
    String PARAMCLIENT = "CLIENT";
    String PARAMNEWBALANCE = "NEWBALANCE";
    String PARAMFLASH = "FLASH";
    String PARAMLAUNCH = "LAUNCH";
    String PARAM_CREATE_SESSION = "CREATESESSION";
    String PARAMKEY = "KEY";
    String PARAM_PLAYABLE_BET = "PLAYABLE_BET";
    String PARAM_AUTOPLAYSPIN = "AUTOPLAYSPIN";
    String PARAM_LANG = "LANG";
    String PARAM_NEXT_MODE_IS_FRB = "NEXT_MODE_FRB";
    String SPIN_STAT = "PRECSPINSTAT";
    String PARAM_ASYNC_REFRESH_BALANCE_REASON = "REASON";
    String PARAM_BUY = "BUY";

    // output parameters
    String PARAMRESULT = "RESULT";
    String PARAM_REASON = "REASON";
    String PARAMTIME = "TIME";
    String PARAMERROR_CODE = "ERROR_CODE";
    String TERMINATE = "TERMINATE";
    String PARAMBALANCE = "BALANCE";
    String PARAMBONUSBALANCE = "BONUSBALANCE";
    String PARAMBETSUM = "BETSUM";
    String PARAMGAMEID = "GID";
    String ADDITIONAL = "ADDITIONAL";
    String ADDITIONAL_ENTER = "ADDITENTER";
    String RESOK = "OK";
    String PARAMLASTHAND = "LASTHAND";
    String LASTHANDYES = "YES";
    String LASTHANDNO = "NO";
    String PARAMPAYOUT = "PAYOUT";
    String PARAMJACKPOT = "JACKPOT";
    String PARAMOUTOFTIME = "OUTOFTIME";
    String PARAMSESSIONID = "SESSIONID";
    String PARAMREPEAT = "REPEAT";
    String PARAM_LIMITS_CHANGED = "LIMITS_CHANGED";
    String PARAM_UTC_OFFSET = "UTC_OFFSET";
    String PARAM_BALANCE_ID = "BALANCE_ID";
    String PARAMROUNDID = "ROUNDID";

    String PARAMMESSAGE_TYPE = "MESSAGE_TYPE";
    String PARAMTERMINATE = "TERMINATE";
    String PARAMBONUSMODE = "BONUS_MODE";
    String PARAMJS_CLOSE = "JS_CLOSE";
    String PARAMFRBTOTALWIN = "FRB_TOTAL_WIN";

    String PARAMERRORCATEGORY = "ERRORCATEGORY";
    String PARAMERRORTEXT = "ERRORTEXT";
    String PARAMEXTERRORDESC = "EXT_ERROR_DESC";
    String PARAMEXTERRORCODE = "EXT_ERROR_CODE";
    String PARAMEXTMESSAGE = "EXT_MESSAGE_OBJ";
    String PARAM_UI_ERROR_MESSAGE = "UI_ERROR_MESSAGE";
    String PARAM_FRC = "FRC";
    String PARAM_TFRC = "TFRC";
    String PARAM_FRB_MODE = "FRB_MODE";
    String PARAM_GAME_GAME_MODE = "game_mode";
    String PARAM_SERVER_TYPE = "server_type";
    String PARAM_AUTOPLAY_VALUES = "AUTOPLAY_VALUES";
    String PARAM_CURRENCY_SYMBOL = "CURRENCY_SYMBOL";
    String PARAM_CURRENCY_CODE = "CURRENCY_CODE";
    String PARAM_BASE_TIME = "BASE_TIME";
    String PARAM_BASE_TIME_TYPE = "BASE_TIME_TYPE";
    String BASE_TIME_TYPE = "CASINO_LOGIN_TIME";

    String PARAM_GAME_SESSION_ID = "GAMESESSIONID";
    String PARAM_RESTART = "RESTART";
    String PARAM_JS_SET_SESSION = "JS_SET_SESSION";
    String PARAM_JS_FRB_DIALOG = "JS_FRB_DIALOG";
    String PARAM_ROUND_REFERENCE = "ROUND_REF";
    String PARAM_EXTERNAL_SESSION_ID = "EXTERNAL_SESSION_ID";

    String SESSION_ERROR_TEXT = "Session error. Please relogin.";

    String INTERNAL_ERROR_TEXT = "System error. Please contact to support.";
    String VALIDATE_ERROR_TEXT = "Error validate user.";

    String NOTENOUGHMONEY_ERROR_TEXT = "Not enough money. Please reduce you bet.";

    String JS_PC_CASHIER = "redirectToCashier";
    String JS_MOBILE_CASHIER = "launchCashier";

    String TOURNAMENT_ID = "tournamentId";
}
