/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dgphoenix.casino.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TBGDeactivateRoomRequest implements org.apache.thrift.TBase<TBGDeactivateRoomRequest, TBGDeactivateRoomRequest._Fields>, java.io.Serializable, Cloneable, Comparable<TBGDeactivateRoomRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TBGDeactivateRoomRequest");

  private static final org.apache.thrift.protocol.TField OWNER_USERNAME_FIELD_DESC = new org.apache.thrift.protocol.TField("ownerUsername", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField OWNER_ACCOUNT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("ownerAccountId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField ROOM_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("roomId", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField OWNER_EXTERNAL_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("ownerExternalId", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TBGDeactivateRoomRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TBGDeactivateRoomRequestTupleSchemeFactory();

  public java.lang.String ownerUsername; // required
  public long ownerAccountId; // required
  public java.lang.String roomId; // required
  public java.lang.String ownerExternalId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OWNER_USERNAME((short)1, "ownerUsername"),
    OWNER_ACCOUNT_ID((short)2, "ownerAccountId"),
    ROOM_ID((short)3, "roomId"),
    OWNER_EXTERNAL_ID((short)4, "ownerExternalId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OWNER_USERNAME
          return OWNER_USERNAME;
        case 2: // OWNER_ACCOUNT_ID
          return OWNER_ACCOUNT_ID;
        case 3: // ROOM_ID
          return ROOM_ID;
        case 4: // OWNER_EXTERNAL_ID
          return OWNER_EXTERNAL_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __OWNERACCOUNTID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OWNER_USERNAME, new org.apache.thrift.meta_data.FieldMetaData("ownerUsername", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OWNER_ACCOUNT_ID, new org.apache.thrift.meta_data.FieldMetaData("ownerAccountId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.ROOM_ID, new org.apache.thrift.meta_data.FieldMetaData("roomId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OWNER_EXTERNAL_ID, new org.apache.thrift.meta_data.FieldMetaData("ownerExternalId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TBGDeactivateRoomRequest.class, metaDataMap);
  }

  public TBGDeactivateRoomRequest() {
  }

  public TBGDeactivateRoomRequest(
    java.lang.String ownerUsername,
    long ownerAccountId,
    java.lang.String roomId,
    java.lang.String ownerExternalId)
  {
    this();
    this.ownerUsername = ownerUsername;
    this.ownerAccountId = ownerAccountId;
    setOwnerAccountIdIsSet(true);
    this.roomId = roomId;
    this.ownerExternalId = ownerExternalId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TBGDeactivateRoomRequest(TBGDeactivateRoomRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetOwnerUsername()) {
      this.ownerUsername = other.ownerUsername;
    }
    this.ownerAccountId = other.ownerAccountId;
    if (other.isSetRoomId()) {
      this.roomId = other.roomId;
    }
    if (other.isSetOwnerExternalId()) {
      this.ownerExternalId = other.ownerExternalId;
    }
  }

  public TBGDeactivateRoomRequest deepCopy() {
    return new TBGDeactivateRoomRequest(this);
  }

  @Override
  public void clear() {
    this.ownerUsername = null;
    setOwnerAccountIdIsSet(false);
    this.ownerAccountId = 0;
    this.roomId = null;
    this.ownerExternalId = null;
  }

  public java.lang.String getOwnerUsername() {
    return this.ownerUsername;
  }

  public TBGDeactivateRoomRequest setOwnerUsername(java.lang.String ownerUsername) {
    this.ownerUsername = ownerUsername;
    return this;
  }

  public void unsetOwnerUsername() {
    this.ownerUsername = null;
  }

  /** Returns true if field ownerUsername is set (has been assigned a value) and false otherwise */
  public boolean isSetOwnerUsername() {
    return this.ownerUsername != null;
  }

  public void setOwnerUsernameIsSet(boolean value) {
    if (!value) {
      this.ownerUsername = null;
    }
  }

  public long getOwnerAccountId() {
    return this.ownerAccountId;
  }

  public TBGDeactivateRoomRequest setOwnerAccountId(long ownerAccountId) {
    this.ownerAccountId = ownerAccountId;
    setOwnerAccountIdIsSet(true);
    return this;
  }

  public void unsetOwnerAccountId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __OWNERACCOUNTID_ISSET_ID);
  }

  /** Returns true if field ownerAccountId is set (has been assigned a value) and false otherwise */
  public boolean isSetOwnerAccountId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __OWNERACCOUNTID_ISSET_ID);
  }

  public void setOwnerAccountIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __OWNERACCOUNTID_ISSET_ID, value);
  }

  public java.lang.String getRoomId() {
    return this.roomId;
  }

  public TBGDeactivateRoomRequest setRoomId(java.lang.String roomId) {
    this.roomId = roomId;
    return this;
  }

  public void unsetRoomId() {
    this.roomId = null;
  }

  /** Returns true if field roomId is set (has been assigned a value) and false otherwise */
  public boolean isSetRoomId() {
    return this.roomId != null;
  }

  public void setRoomIdIsSet(boolean value) {
    if (!value) {
      this.roomId = null;
    }
  }

  public java.lang.String getOwnerExternalId() {
    return this.ownerExternalId;
  }

  public TBGDeactivateRoomRequest setOwnerExternalId(java.lang.String ownerExternalId) {
    this.ownerExternalId = ownerExternalId;
    return this;
  }

  public void unsetOwnerExternalId() {
    this.ownerExternalId = null;
  }

  /** Returns true if field ownerExternalId is set (has been assigned a value) and false otherwise */
  public boolean isSetOwnerExternalId() {
    return this.ownerExternalId != null;
  }

  public void setOwnerExternalIdIsSet(boolean value) {
    if (!value) {
      this.ownerExternalId = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case OWNER_USERNAME:
      if (value == null) {
        unsetOwnerUsername();
      } else {
        setOwnerUsername((java.lang.String)value);
      }
      break;

    case OWNER_ACCOUNT_ID:
      if (value == null) {
        unsetOwnerAccountId();
      } else {
        setOwnerAccountId((java.lang.Long)value);
      }
      break;

    case ROOM_ID:
      if (value == null) {
        unsetRoomId();
      } else {
        setRoomId((java.lang.String)value);
      }
      break;

    case OWNER_EXTERNAL_ID:
      if (value == null) {
        unsetOwnerExternalId();
      } else {
        setOwnerExternalId((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case OWNER_USERNAME:
      return getOwnerUsername();

    case OWNER_ACCOUNT_ID:
      return getOwnerAccountId();

    case ROOM_ID:
      return getRoomId();

    case OWNER_EXTERNAL_ID:
      return getOwnerExternalId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case OWNER_USERNAME:
      return isSetOwnerUsername();
    case OWNER_ACCOUNT_ID:
      return isSetOwnerAccountId();
    case ROOM_ID:
      return isSetRoomId();
    case OWNER_EXTERNAL_ID:
      return isSetOwnerExternalId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TBGDeactivateRoomRequest)
      return this.equals((TBGDeactivateRoomRequest)that);
    return false;
  }

  public boolean equals(TBGDeactivateRoomRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_ownerUsername = true && this.isSetOwnerUsername();
    boolean that_present_ownerUsername = true && that.isSetOwnerUsername();
    if (this_present_ownerUsername || that_present_ownerUsername) {
      if (!(this_present_ownerUsername && that_present_ownerUsername))
        return false;
      if (!this.ownerUsername.equals(that.ownerUsername))
        return false;
    }

    boolean this_present_ownerAccountId = true;
    boolean that_present_ownerAccountId = true;
    if (this_present_ownerAccountId || that_present_ownerAccountId) {
      if (!(this_present_ownerAccountId && that_present_ownerAccountId))
        return false;
      if (this.ownerAccountId != that.ownerAccountId)
        return false;
    }

    boolean this_present_roomId = true && this.isSetRoomId();
    boolean that_present_roomId = true && that.isSetRoomId();
    if (this_present_roomId || that_present_roomId) {
      if (!(this_present_roomId && that_present_roomId))
        return false;
      if (!this.roomId.equals(that.roomId))
        return false;
    }

    boolean this_present_ownerExternalId = true && this.isSetOwnerExternalId();
    boolean that_present_ownerExternalId = true && that.isSetOwnerExternalId();
    if (this_present_ownerExternalId || that_present_ownerExternalId) {
      if (!(this_present_ownerExternalId && that_present_ownerExternalId))
        return false;
      if (!this.ownerExternalId.equals(that.ownerExternalId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetOwnerUsername()) ? 131071 : 524287);
    if (isSetOwnerUsername())
      hashCode = hashCode * 8191 + ownerUsername.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(ownerAccountId);

    hashCode = hashCode * 8191 + ((isSetRoomId()) ? 131071 : 524287);
    if (isSetRoomId())
      hashCode = hashCode * 8191 + roomId.hashCode();

    hashCode = hashCode * 8191 + ((isSetOwnerExternalId()) ? 131071 : 524287);
    if (isSetOwnerExternalId())
      hashCode = hashCode * 8191 + ownerExternalId.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TBGDeactivateRoomRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetOwnerUsername()).compareTo(other.isSetOwnerUsername());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOwnerUsername()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ownerUsername, other.ownerUsername);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOwnerAccountId()).compareTo(other.isSetOwnerAccountId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOwnerAccountId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ownerAccountId, other.ownerAccountId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRoomId()).compareTo(other.isSetRoomId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoomId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roomId, other.roomId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOwnerExternalId()).compareTo(other.isSetOwnerExternalId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOwnerExternalId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ownerExternalId, other.ownerExternalId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TBGDeactivateRoomRequest(");
    boolean first = true;

    sb.append("ownerUsername:");
    if (this.ownerUsername == null) {
      sb.append("null");
    } else {
      sb.append(this.ownerUsername);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ownerAccountId:");
    sb.append(this.ownerAccountId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("roomId:");
    if (this.roomId == null) {
      sb.append("null");
    } else {
      sb.append(this.roomId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ownerExternalId:");
    if (this.ownerExternalId == null) {
      sb.append("null");
    } else {
      sb.append(this.ownerExternalId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TBGDeactivateRoomRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TBGDeactivateRoomRequestStandardScheme getScheme() {
      return new TBGDeactivateRoomRequestStandardScheme();
    }
  }

  private static class TBGDeactivateRoomRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<TBGDeactivateRoomRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TBGDeactivateRoomRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OWNER_USERNAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ownerUsername = iprot.readString();
              struct.setOwnerUsernameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OWNER_ACCOUNT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.ownerAccountId = iprot.readI64();
              struct.setOwnerAccountIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ROOM_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.roomId = iprot.readString();
              struct.setRoomIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // OWNER_EXTERNAL_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ownerExternalId = iprot.readString();
              struct.setOwnerExternalIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TBGDeactivateRoomRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.ownerUsername != null) {
        oprot.writeFieldBegin(OWNER_USERNAME_FIELD_DESC);
        oprot.writeString(struct.ownerUsername);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(OWNER_ACCOUNT_ID_FIELD_DESC);
      oprot.writeI64(struct.ownerAccountId);
      oprot.writeFieldEnd();
      if (struct.roomId != null) {
        oprot.writeFieldBegin(ROOM_ID_FIELD_DESC);
        oprot.writeString(struct.roomId);
        oprot.writeFieldEnd();
      }
      if (struct.ownerExternalId != null) {
        oprot.writeFieldBegin(OWNER_EXTERNAL_ID_FIELD_DESC);
        oprot.writeString(struct.ownerExternalId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TBGDeactivateRoomRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TBGDeactivateRoomRequestTupleScheme getScheme() {
      return new TBGDeactivateRoomRequestTupleScheme();
    }
  }

  private static class TBGDeactivateRoomRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<TBGDeactivateRoomRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TBGDeactivateRoomRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetOwnerUsername()) {
        optionals.set(0);
      }
      if (struct.isSetOwnerAccountId()) {
        optionals.set(1);
      }
      if (struct.isSetRoomId()) {
        optionals.set(2);
      }
      if (struct.isSetOwnerExternalId()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetOwnerUsername()) {
        oprot.writeString(struct.ownerUsername);
      }
      if (struct.isSetOwnerAccountId()) {
        oprot.writeI64(struct.ownerAccountId);
      }
      if (struct.isSetRoomId()) {
        oprot.writeString(struct.roomId);
      }
      if (struct.isSetOwnerExternalId()) {
        oprot.writeString(struct.ownerExternalId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TBGDeactivateRoomRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.ownerUsername = iprot.readString();
        struct.setOwnerUsernameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ownerAccountId = iprot.readI64();
        struct.setOwnerAccountIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.roomId = iprot.readString();
        struct.setRoomIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.ownerExternalId = iprot.readString();
        struct.setOwnerExternalIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

