/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dgphoenix.casino.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TBGUpdateOnlinePlayersRequest implements org.apache.thrift.TBase<TBGUpdateOnlinePlayersRequest, TBGUpdateOnlinePlayersRequest._Fields>, java.io.Serializable, Cloneable, Comparable<TBGUpdateOnlinePlayersRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TBGUpdateOnlinePlayersRequest");

  private static final org.apache.thrift.protocol.TField ONLINE_PLAYERS_FIELD_DESC = new org.apache.thrift.protocol.TField("onlinePlayers", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TBGUpdateOnlinePlayersRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TBGUpdateOnlinePlayersRequestTupleSchemeFactory();

  public java.util.List<TBGOnlinePlayer> onlinePlayers; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ONLINE_PLAYERS((short)1, "onlinePlayers");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ONLINE_PLAYERS
          return ONLINE_PLAYERS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ONLINE_PLAYERS, new org.apache.thrift.meta_data.FieldMetaData("onlinePlayers", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TBGOnlinePlayer.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TBGUpdateOnlinePlayersRequest.class, metaDataMap);
  }

  public TBGUpdateOnlinePlayersRequest() {
  }

  public TBGUpdateOnlinePlayersRequest(
    java.util.List<TBGOnlinePlayer> onlinePlayers)
  {
    this();
    this.onlinePlayers = onlinePlayers;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TBGUpdateOnlinePlayersRequest(TBGUpdateOnlinePlayersRequest other) {
    if (other.isSetOnlinePlayers()) {
      java.util.List<TBGOnlinePlayer> __this__onlinePlayers = new java.util.ArrayList<TBGOnlinePlayer>(other.onlinePlayers.size());
      for (TBGOnlinePlayer other_element : other.onlinePlayers) {
        __this__onlinePlayers.add(new TBGOnlinePlayer(other_element));
      }
      this.onlinePlayers = __this__onlinePlayers;
    }
  }

  public TBGUpdateOnlinePlayersRequest deepCopy() {
    return new TBGUpdateOnlinePlayersRequest(this);
  }

  @Override
  public void clear() {
    this.onlinePlayers = null;
  }

  public int getOnlinePlayersSize() {
    return (this.onlinePlayers == null) ? 0 : this.onlinePlayers.size();
  }

  public java.util.Iterator<TBGOnlinePlayer> getOnlinePlayersIterator() {
    return (this.onlinePlayers == null) ? null : this.onlinePlayers.iterator();
  }

  public void addToOnlinePlayers(TBGOnlinePlayer elem) {
    if (this.onlinePlayers == null) {
      this.onlinePlayers = new java.util.ArrayList<TBGOnlinePlayer>();
    }
    this.onlinePlayers.add(elem);
  }

  public java.util.List<TBGOnlinePlayer> getOnlinePlayers() {
    return this.onlinePlayers;
  }

  public TBGUpdateOnlinePlayersRequest setOnlinePlayers(java.util.List<TBGOnlinePlayer> onlinePlayers) {
    this.onlinePlayers = onlinePlayers;
    return this;
  }

  public void unsetOnlinePlayers() {
    this.onlinePlayers = null;
  }

  /** Returns true if field onlinePlayers is set (has been assigned a value) and false otherwise */
  public boolean isSetOnlinePlayers() {
    return this.onlinePlayers != null;
  }

  public void setOnlinePlayersIsSet(boolean value) {
    if (!value) {
      this.onlinePlayers = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ONLINE_PLAYERS:
      if (value == null) {
        unsetOnlinePlayers();
      } else {
        setOnlinePlayers((java.util.List<TBGOnlinePlayer>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ONLINE_PLAYERS:
      return getOnlinePlayers();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ONLINE_PLAYERS:
      return isSetOnlinePlayers();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TBGUpdateOnlinePlayersRequest)
      return this.equals((TBGUpdateOnlinePlayersRequest)that);
    return false;
  }

  public boolean equals(TBGUpdateOnlinePlayersRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_onlinePlayers = true && this.isSetOnlinePlayers();
    boolean that_present_onlinePlayers = true && that.isSetOnlinePlayers();
    if (this_present_onlinePlayers || that_present_onlinePlayers) {
      if (!(this_present_onlinePlayers && that_present_onlinePlayers))
        return false;
      if (!this.onlinePlayers.equals(that.onlinePlayers))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetOnlinePlayers()) ? 131071 : 524287);
    if (isSetOnlinePlayers())
      hashCode = hashCode * 8191 + onlinePlayers.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TBGUpdateOnlinePlayersRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetOnlinePlayers()).compareTo(other.isSetOnlinePlayers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOnlinePlayers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.onlinePlayers, other.onlinePlayers);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TBGUpdateOnlinePlayersRequest(");
    boolean first = true;

    sb.append("onlinePlayers:");
    if (this.onlinePlayers == null) {
      sb.append("null");
    } else {
      sb.append(this.onlinePlayers);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TBGUpdateOnlinePlayersRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TBGUpdateOnlinePlayersRequestStandardScheme getScheme() {
      return new TBGUpdateOnlinePlayersRequestStandardScheme();
    }
  }

  private static class TBGUpdateOnlinePlayersRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<TBGUpdateOnlinePlayersRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TBGUpdateOnlinePlayersRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ONLINE_PLAYERS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list204 = iprot.readListBegin();
                struct.onlinePlayers = new java.util.ArrayList<TBGOnlinePlayer>(_list204.size);
                TBGOnlinePlayer _elem205;
                for (int _i206 = 0; _i206 < _list204.size; ++_i206)
                {
                  _elem205 = new TBGOnlinePlayer();
                  _elem205.read(iprot);
                  struct.onlinePlayers.add(_elem205);
                }
                iprot.readListEnd();
              }
              struct.setOnlinePlayersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TBGUpdateOnlinePlayersRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.onlinePlayers != null) {
        oprot.writeFieldBegin(ONLINE_PLAYERS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.onlinePlayers.size()));
          for (TBGOnlinePlayer _iter207 : struct.onlinePlayers)
          {
            _iter207.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TBGUpdateOnlinePlayersRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TBGUpdateOnlinePlayersRequestTupleScheme getScheme() {
      return new TBGUpdateOnlinePlayersRequestTupleScheme();
    }
  }

  private static class TBGUpdateOnlinePlayersRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<TBGUpdateOnlinePlayersRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TBGUpdateOnlinePlayersRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetOnlinePlayers()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetOnlinePlayers()) {
        {
          oprot.writeI32(struct.onlinePlayers.size());
          for (TBGOnlinePlayer _iter208 : struct.onlinePlayers)
          {
            _iter208.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TBGUpdateOnlinePlayersRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list209 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.onlinePlayers = new java.util.ArrayList<TBGOnlinePlayer>(_list209.size);
          TBGOnlinePlayer _elem210;
          for (int _i211 = 0; _i211 < _list209.size; ++_i211)
          {
            _elem210 = new TBGOnlinePlayer();
            _elem210.read(iprot);
            struct.onlinePlayers.add(_elem210);
          }
        }
        struct.setOnlinePlayersIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

