/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dgphoenix.casino.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TBGUpdateRoomRequest implements org.apache.thrift.TBase<TBGUpdateRoomRequest, TBGUpdateRoomRequest._Fields>, java.io.Serializable, Cloneable, Comparable<TBGUpdateRoomRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TBGUpdateRoomRequest");

  private static final org.apache.thrift.protocol.TField PRIVATE_ROOM_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("privateRoomId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PLAYERS_FIELD_DESC = new org.apache.thrift.protocol.TField("players", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField BANK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("bankId", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TBGUpdateRoomRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TBGUpdateRoomRequestTupleSchemeFactory();

  public java.lang.String privateRoomId; // required
  public java.util.List<TBGPlayer> players; // required
  public int bankId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PRIVATE_ROOM_ID((short)1, "privateRoomId"),
    PLAYERS((short)2, "players"),
    BANK_ID((short)3, "bankId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PRIVATE_ROOM_ID
          return PRIVATE_ROOM_ID;
        case 2: // PLAYERS
          return PLAYERS;
        case 3: // BANK_ID
          return BANK_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BANKID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PRIVATE_ROOM_ID, new org.apache.thrift.meta_data.FieldMetaData("privateRoomId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PLAYERS, new org.apache.thrift.meta_data.FieldMetaData("players", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TBGPlayer.class))));
    tmpMap.put(_Fields.BANK_ID, new org.apache.thrift.meta_data.FieldMetaData("bankId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TBGUpdateRoomRequest.class, metaDataMap);
  }

  public TBGUpdateRoomRequest() {
  }

  public TBGUpdateRoomRequest(
    java.lang.String privateRoomId,
    java.util.List<TBGPlayer> players,
    int bankId)
  {
    this();
    this.privateRoomId = privateRoomId;
    this.players = players;
    this.bankId = bankId;
    setBankIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TBGUpdateRoomRequest(TBGUpdateRoomRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetPrivateRoomId()) {
      this.privateRoomId = other.privateRoomId;
    }
    if (other.isSetPlayers()) {
      java.util.List<TBGPlayer> __this__players = new java.util.ArrayList<TBGPlayer>(other.players.size());
      for (TBGPlayer other_element : other.players) {
        __this__players.add(new TBGPlayer(other_element));
      }
      this.players = __this__players;
    }
    this.bankId = other.bankId;
  }

  public TBGUpdateRoomRequest deepCopy() {
    return new TBGUpdateRoomRequest(this);
  }

  @Override
  public void clear() {
    this.privateRoomId = null;
    this.players = null;
    setBankIdIsSet(false);
    this.bankId = 0;
  }

  public java.lang.String getPrivateRoomId() {
    return this.privateRoomId;
  }

  public TBGUpdateRoomRequest setPrivateRoomId(java.lang.String privateRoomId) {
    this.privateRoomId = privateRoomId;
    return this;
  }

  public void unsetPrivateRoomId() {
    this.privateRoomId = null;
  }

  /** Returns true if field privateRoomId is set (has been assigned a value) and false otherwise */
  public boolean isSetPrivateRoomId() {
    return this.privateRoomId != null;
  }

  public void setPrivateRoomIdIsSet(boolean value) {
    if (!value) {
      this.privateRoomId = null;
    }
  }

  public int getPlayersSize() {
    return (this.players == null) ? 0 : this.players.size();
  }

  public java.util.Iterator<TBGPlayer> getPlayersIterator() {
    return (this.players == null) ? null : this.players.iterator();
  }

  public void addToPlayers(TBGPlayer elem) {
    if (this.players == null) {
      this.players = new java.util.ArrayList<TBGPlayer>();
    }
    this.players.add(elem);
  }

  public java.util.List<TBGPlayer> getPlayers() {
    return this.players;
  }

  public TBGUpdateRoomRequest setPlayers(java.util.List<TBGPlayer> players) {
    this.players = players;
    return this;
  }

  public void unsetPlayers() {
    this.players = null;
  }

  /** Returns true if field players is set (has been assigned a value) and false otherwise */
  public boolean isSetPlayers() {
    return this.players != null;
  }

  public void setPlayersIsSet(boolean value) {
    if (!value) {
      this.players = null;
    }
  }

  public int getBankId() {
    return this.bankId;
  }

  public TBGUpdateRoomRequest setBankId(int bankId) {
    this.bankId = bankId;
    setBankIdIsSet(true);
    return this;
  }

  public void unsetBankId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BANKID_ISSET_ID);
  }

  /** Returns true if field bankId is set (has been assigned a value) and false otherwise */
  public boolean isSetBankId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BANKID_ISSET_ID);
  }

  public void setBankIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BANKID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case PRIVATE_ROOM_ID:
      if (value == null) {
        unsetPrivateRoomId();
      } else {
        setPrivateRoomId((java.lang.String)value);
      }
      break;

    case PLAYERS:
      if (value == null) {
        unsetPlayers();
      } else {
        setPlayers((java.util.List<TBGPlayer>)value);
      }
      break;

    case BANK_ID:
      if (value == null) {
        unsetBankId();
      } else {
        setBankId((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PRIVATE_ROOM_ID:
      return getPrivateRoomId();

    case PLAYERS:
      return getPlayers();

    case BANK_ID:
      return getBankId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PRIVATE_ROOM_ID:
      return isSetPrivateRoomId();
    case PLAYERS:
      return isSetPlayers();
    case BANK_ID:
      return isSetBankId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TBGUpdateRoomRequest)
      return this.equals((TBGUpdateRoomRequest)that);
    return false;
  }

  public boolean equals(TBGUpdateRoomRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_privateRoomId = true && this.isSetPrivateRoomId();
    boolean that_present_privateRoomId = true && that.isSetPrivateRoomId();
    if (this_present_privateRoomId || that_present_privateRoomId) {
      if (!(this_present_privateRoomId && that_present_privateRoomId))
        return false;
      if (!this.privateRoomId.equals(that.privateRoomId))
        return false;
    }

    boolean this_present_players = true && this.isSetPlayers();
    boolean that_present_players = true && that.isSetPlayers();
    if (this_present_players || that_present_players) {
      if (!(this_present_players && that_present_players))
        return false;
      if (!this.players.equals(that.players))
        return false;
    }

    boolean this_present_bankId = true;
    boolean that_present_bankId = true;
    if (this_present_bankId || that_present_bankId) {
      if (!(this_present_bankId && that_present_bankId))
        return false;
      if (this.bankId != that.bankId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPrivateRoomId()) ? 131071 : 524287);
    if (isSetPrivateRoomId())
      hashCode = hashCode * 8191 + privateRoomId.hashCode();

    hashCode = hashCode * 8191 + ((isSetPlayers()) ? 131071 : 524287);
    if (isSetPlayers())
      hashCode = hashCode * 8191 + players.hashCode();

    hashCode = hashCode * 8191 + bankId;

    return hashCode;
  }

  @Override
  public int compareTo(TBGUpdateRoomRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetPrivateRoomId()).compareTo(other.isSetPrivateRoomId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrivateRoomId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.privateRoomId, other.privateRoomId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPlayers()).compareTo(other.isSetPlayers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.players, other.players);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBankId()).compareTo(other.isSetBankId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBankId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bankId, other.bankId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TBGUpdateRoomRequest(");
    boolean first = true;

    sb.append("privateRoomId:");
    if (this.privateRoomId == null) {
      sb.append("null");
    } else {
      sb.append(this.privateRoomId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("players:");
    if (this.players == null) {
      sb.append("null");
    } else {
      sb.append(this.players);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("bankId:");
    sb.append(this.bankId);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TBGUpdateRoomRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TBGUpdateRoomRequestStandardScheme getScheme() {
      return new TBGUpdateRoomRequestStandardScheme();
    }
  }

  private static class TBGUpdateRoomRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<TBGUpdateRoomRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TBGUpdateRoomRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PRIVATE_ROOM_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.privateRoomId = iprot.readString();
              struct.setPrivateRoomIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PLAYERS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list172 = iprot.readListBegin();
                struct.players = new java.util.ArrayList<TBGPlayer>(_list172.size);
                TBGPlayer _elem173;
                for (int _i174 = 0; _i174 < _list172.size; ++_i174)
                {
                  _elem173 = new TBGPlayer();
                  _elem173.read(iprot);
                  struct.players.add(_elem173);
                }
                iprot.readListEnd();
              }
              struct.setPlayersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // BANK_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.bankId = iprot.readI32();
              struct.setBankIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TBGUpdateRoomRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.privateRoomId != null) {
        oprot.writeFieldBegin(PRIVATE_ROOM_ID_FIELD_DESC);
        oprot.writeString(struct.privateRoomId);
        oprot.writeFieldEnd();
      }
      if (struct.players != null) {
        oprot.writeFieldBegin(PLAYERS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.players.size()));
          for (TBGPlayer _iter175 : struct.players)
          {
            _iter175.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(BANK_ID_FIELD_DESC);
      oprot.writeI32(struct.bankId);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TBGUpdateRoomRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TBGUpdateRoomRequestTupleScheme getScheme() {
      return new TBGUpdateRoomRequestTupleScheme();
    }
  }

  private static class TBGUpdateRoomRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<TBGUpdateRoomRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TBGUpdateRoomRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPrivateRoomId()) {
        optionals.set(0);
      }
      if (struct.isSetPlayers()) {
        optionals.set(1);
      }
      if (struct.isSetBankId()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetPrivateRoomId()) {
        oprot.writeString(struct.privateRoomId);
      }
      if (struct.isSetPlayers()) {
        {
          oprot.writeI32(struct.players.size());
          for (TBGPlayer _iter176 : struct.players)
          {
            _iter176.write(oprot);
          }
        }
      }
      if (struct.isSetBankId()) {
        oprot.writeI32(struct.bankId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TBGUpdateRoomRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.privateRoomId = iprot.readString();
        struct.setPrivateRoomIdIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list177 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.players = new java.util.ArrayList<TBGPlayer>(_list177.size);
          TBGPlayer _elem178;
          for (int _i179 = 0; _i179 < _list177.size; ++_i179)
          {
            _elem178 = new TBGPlayer();
            _elem178.read(iprot);
            struct.players.add(_elem178);
          }
        }
        struct.setPlayersIsSet(true);
      }
      if (incoming.get(2)) {
        struct.bankId = iprot.readI32();
        struct.setBankIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

