/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dgphoenix.casino.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TBGUpdateOnlinePlayersResult implements org.apache.thrift.TBase<TBGUpdateOnlinePlayersResult, TBGUpdateOnlinePlayersResult._Fields>, java.io.Serializable, Cloneable, Comparable<TBGUpdateOnlinePlayersResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TBGUpdateOnlinePlayersResult");

  private static final org.apache.thrift.protocol.TField CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("code", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("message", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ONLINE_PLAYERS_FIELD_DESC = new org.apache.thrift.protocol.TField("onlinePlayers", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TBGUpdateOnlinePlayersResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TBGUpdateOnlinePlayersResultTupleSchemeFactory();

  public int code; // required
  public java.lang.String message; // required
  public java.util.List<TBGOnlinePlayer> onlinePlayers; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CODE((short)1, "code"),
    MESSAGE((short)2, "message"),
    ONLINE_PLAYERS((short)3, "onlinePlayers");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CODE
          return CODE;
        case 2: // MESSAGE
          return MESSAGE;
        case 3: // ONLINE_PLAYERS
          return ONLINE_PLAYERS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CODE, new org.apache.thrift.meta_data.FieldMetaData("code", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("message", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ONLINE_PLAYERS, new org.apache.thrift.meta_data.FieldMetaData("onlinePlayers", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TBGOnlinePlayer.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TBGUpdateOnlinePlayersResult.class, metaDataMap);
  }

  public TBGUpdateOnlinePlayersResult() {
  }

  public TBGUpdateOnlinePlayersResult(
    int code,
    java.lang.String message,
    java.util.List<TBGOnlinePlayer> onlinePlayers)
  {
    this();
    this.code = code;
    setCodeIsSet(true);
    this.message = message;
    this.onlinePlayers = onlinePlayers;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TBGUpdateOnlinePlayersResult(TBGUpdateOnlinePlayersResult other) {
    __isset_bitfield = other.__isset_bitfield;
    this.code = other.code;
    if (other.isSetMessage()) {
      this.message = other.message;
    }
    if (other.isSetOnlinePlayers()) {
      java.util.List<TBGOnlinePlayer> __this__onlinePlayers = new java.util.ArrayList<TBGOnlinePlayer>(other.onlinePlayers.size());
      for (TBGOnlinePlayer other_element : other.onlinePlayers) {
        __this__onlinePlayers.add(new TBGOnlinePlayer(other_element));
      }
      this.onlinePlayers = __this__onlinePlayers;
    }
  }

  public TBGUpdateOnlinePlayersResult deepCopy() {
    return new TBGUpdateOnlinePlayersResult(this);
  }

  @Override
  public void clear() {
    setCodeIsSet(false);
    this.code = 0;
    this.message = null;
    this.onlinePlayers = null;
  }

  public int getCode() {
    return this.code;
  }

  public TBGUpdateOnlinePlayersResult setCode(int code) {
    this.code = code;
    setCodeIsSet(true);
    return this;
  }

  public void unsetCode() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CODE_ISSET_ID);
  }

  /** Returns true if field code is set (has been assigned a value) and false otherwise */
  public boolean isSetCode() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CODE_ISSET_ID);
  }

  public void setCodeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CODE_ISSET_ID, value);
  }

  public java.lang.String getMessage() {
    return this.message;
  }

  public TBGUpdateOnlinePlayersResult setMessage(java.lang.String message) {
    this.message = message;
    return this;
  }

  public void unsetMessage() {
    this.message = null;
  }

  /** Returns true if field message is set (has been assigned a value) and false otherwise */
  public boolean isSetMessage() {
    return this.message != null;
  }

  public void setMessageIsSet(boolean value) {
    if (!value) {
      this.message = null;
    }
  }

  public int getOnlinePlayersSize() {
    return (this.onlinePlayers == null) ? 0 : this.onlinePlayers.size();
  }

  public java.util.Iterator<TBGOnlinePlayer> getOnlinePlayersIterator() {
    return (this.onlinePlayers == null) ? null : this.onlinePlayers.iterator();
  }

  public void addToOnlinePlayers(TBGOnlinePlayer elem) {
    if (this.onlinePlayers == null) {
      this.onlinePlayers = new java.util.ArrayList<TBGOnlinePlayer>();
    }
    this.onlinePlayers.add(elem);
  }

  public java.util.List<TBGOnlinePlayer> getOnlinePlayers() {
    return this.onlinePlayers;
  }

  public TBGUpdateOnlinePlayersResult setOnlinePlayers(java.util.List<TBGOnlinePlayer> onlinePlayers) {
    this.onlinePlayers = onlinePlayers;
    return this;
  }

  public void unsetOnlinePlayers() {
    this.onlinePlayers = null;
  }

  /** Returns true if field onlinePlayers is set (has been assigned a value) and false otherwise */
  public boolean isSetOnlinePlayers() {
    return this.onlinePlayers != null;
  }

  public void setOnlinePlayersIsSet(boolean value) {
    if (!value) {
      this.onlinePlayers = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case CODE:
      if (value == null) {
        unsetCode();
      } else {
        setCode((java.lang.Integer)value);
      }
      break;

    case MESSAGE:
      if (value == null) {
        unsetMessage();
      } else {
        setMessage((java.lang.String)value);
      }
      break;

    case ONLINE_PLAYERS:
      if (value == null) {
        unsetOnlinePlayers();
      } else {
        setOnlinePlayers((java.util.List<TBGOnlinePlayer>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CODE:
      return getCode();

    case MESSAGE:
      return getMessage();

    case ONLINE_PLAYERS:
      return getOnlinePlayers();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CODE:
      return isSetCode();
    case MESSAGE:
      return isSetMessage();
    case ONLINE_PLAYERS:
      return isSetOnlinePlayers();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TBGUpdateOnlinePlayersResult)
      return this.equals((TBGUpdateOnlinePlayersResult)that);
    return false;
  }

  public boolean equals(TBGUpdateOnlinePlayersResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_code = true;
    boolean that_present_code = true;
    if (this_present_code || that_present_code) {
      if (!(this_present_code && that_present_code))
        return false;
      if (this.code != that.code)
        return false;
    }

    boolean this_present_message = true && this.isSetMessage();
    boolean that_present_message = true && that.isSetMessage();
    if (this_present_message || that_present_message) {
      if (!(this_present_message && that_present_message))
        return false;
      if (!this.message.equals(that.message))
        return false;
    }

    boolean this_present_onlinePlayers = true && this.isSetOnlinePlayers();
    boolean that_present_onlinePlayers = true && that.isSetOnlinePlayers();
    if (this_present_onlinePlayers || that_present_onlinePlayers) {
      if (!(this_present_onlinePlayers && that_present_onlinePlayers))
        return false;
      if (!this.onlinePlayers.equals(that.onlinePlayers))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + code;

    hashCode = hashCode * 8191 + ((isSetMessage()) ? 131071 : 524287);
    if (isSetMessage())
      hashCode = hashCode * 8191 + message.hashCode();

    hashCode = hashCode * 8191 + ((isSetOnlinePlayers()) ? 131071 : 524287);
    if (isSetOnlinePlayers())
      hashCode = hashCode * 8191 + onlinePlayers.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TBGUpdateOnlinePlayersResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCode()).compareTo(other.isSetCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.code, other.code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMessage()).compareTo(other.isSetMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.message, other.message);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOnlinePlayers()).compareTo(other.isSetOnlinePlayers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOnlinePlayers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.onlinePlayers, other.onlinePlayers);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TBGUpdateOnlinePlayersResult(");
    boolean first = true;

    sb.append("code:");
    sb.append(this.code);
    first = false;
    if (!first) sb.append(", ");
    sb.append("message:");
    if (this.message == null) {
      sb.append("null");
    } else {
      sb.append(this.message);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("onlinePlayers:");
    if (this.onlinePlayers == null) {
      sb.append("null");
    } else {
      sb.append(this.onlinePlayers);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TBGUpdateOnlinePlayersResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TBGUpdateOnlinePlayersResultStandardScheme getScheme() {
      return new TBGUpdateOnlinePlayersResultStandardScheme();
    }
  }

  private static class TBGUpdateOnlinePlayersResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<TBGUpdateOnlinePlayersResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TBGUpdateOnlinePlayersResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.code = iprot.readI32();
              struct.setCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.message = iprot.readString();
              struct.setMessageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ONLINE_PLAYERS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list212 = iprot.readListBegin();
                struct.onlinePlayers = new java.util.ArrayList<TBGOnlinePlayer>(_list212.size);
                TBGOnlinePlayer _elem213;
                for (int _i214 = 0; _i214 < _list212.size; ++_i214)
                {
                  _elem213 = new TBGOnlinePlayer();
                  _elem213.read(iprot);
                  struct.onlinePlayers.add(_elem213);
                }
                iprot.readListEnd();
              }
              struct.setOnlinePlayersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TBGUpdateOnlinePlayersResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CODE_FIELD_DESC);
      oprot.writeI32(struct.code);
      oprot.writeFieldEnd();
      if (struct.message != null) {
        oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
        oprot.writeString(struct.message);
        oprot.writeFieldEnd();
      }
      if (struct.onlinePlayers != null) {
        oprot.writeFieldBegin(ONLINE_PLAYERS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.onlinePlayers.size()));
          for (TBGOnlinePlayer _iter215 : struct.onlinePlayers)
          {
            _iter215.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TBGUpdateOnlinePlayersResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TBGUpdateOnlinePlayersResultTupleScheme getScheme() {
      return new TBGUpdateOnlinePlayersResultTupleScheme();
    }
  }

  private static class TBGUpdateOnlinePlayersResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<TBGUpdateOnlinePlayersResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TBGUpdateOnlinePlayersResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCode()) {
        optionals.set(0);
      }
      if (struct.isSetMessage()) {
        optionals.set(1);
      }
      if (struct.isSetOnlinePlayers()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetCode()) {
        oprot.writeI32(struct.code);
      }
      if (struct.isSetMessage()) {
        oprot.writeString(struct.message);
      }
      if (struct.isSetOnlinePlayers()) {
        {
          oprot.writeI32(struct.onlinePlayers.size());
          for (TBGOnlinePlayer _iter216 : struct.onlinePlayers)
          {
            _iter216.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TBGUpdateOnlinePlayersResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.code = iprot.readI32();
        struct.setCodeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.message = iprot.readString();
        struct.setMessageIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list217 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.onlinePlayers = new java.util.ArrayList<TBGOnlinePlayer>(_list217.size);
          TBGOnlinePlayer _elem218;
          for (int _i219 = 0; _i219 < _list217.size; ++_i219)
          {
            _elem218 = new TBGOnlinePlayer();
            _elem218.read(iprot);
            struct.onlinePlayers.add(_elem218);
          }
        }
        struct.setOnlinePlayersIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

