/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dgphoenix.casino.thrift;

import org.apache.thrift.protocol.TType;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TBotConfigInfo implements org.apache.thrift.TBase<TBotConfigInfo, TBotConfigInfo._Fields>, java.io.Serializable, Cloneable, Comparable<TBotConfigInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TBotConfigInfo");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField BANK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("bankId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField ALLOWED_GAMES_FIELD_DESC = new org.apache.thrift.protocol.TField("allowedGames", org.apache.thrift.protocol.TType.SET, (short)3);
  private static final org.apache.thrift.protocol.TField ACTIVE_FIELD_DESC = new org.apache.thrift.protocol.TField("active", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField USERNAME_FIELD_DESC = new org.apache.thrift.protocol.TField("username", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField PASSWORD_FIELD_DESC = new org.apache.thrift.protocol.TField("password", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField MQ_NICKNAME_FIELD_DESC = new org.apache.thrift.protocol.TField("mqNickname", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField MMC_BALANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("mmcBalance", org.apache.thrift.protocol.TType.I64, (short)8);
  private static final org.apache.thrift.protocol.TField MQC_BALANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("mqcBalance", org.apache.thrift.protocol.TType.I64, (short)9);
  private static final org.apache.thrift.protocol.TField TIME_FRAMES_FIELD_DESC = new org.apache.thrift.protocol.TField("timeFrames", org.apache.thrift.protocol.TType.SET, (short)10);
  private static final org.apache.thrift.protocol.TField ALLOWED_BANK_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("allowedBankIds", org.apache.thrift.protocol.TType.SET, (short)11);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TBotConfigInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TBotConfigInfoTupleSchemeFactory();

  public long id; // required
  public long bankId; // required
  public java.util.Set<java.lang.Long> allowedGames; // required
  public boolean active; // required
  public java.lang.String username; // required
  public java.lang.String password; // required
  public java.lang.String mqNickname; // required
  public long mmcBalance; // required
  public long mqcBalance; // required
  public java.util.Set<TTimeFrame> timeFrames; // required
  public java.util.Set<java.lang.Long> allowedBankIds; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    BANK_ID((short)2, "bankId"),
    ALLOWED_GAMES((short)3, "allowedGames"),
    ACTIVE((short)4, "active"),
    USERNAME((short)5, "username"),
    PASSWORD((short)6, "password"),
    MQ_NICKNAME((short)7, "mqNickname"),
    MMC_BALANCE((short)8, "mmcBalance"),
    MQC_BALANCE((short)9, "mqcBalance"),
    TIME_FRAMES((short)10, "timeFrames"),
    ALLOWED_BANK_IDS((short)11, "allowedBankIds");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // BANK_ID
          return BANK_ID;
        case 3: // ALLOWED_GAMES
          return ALLOWED_GAMES;
        case 4: // ACTIVE
          return ACTIVE;
        case 5: // USERNAME
          return USERNAME;
        case 6: // PASSWORD
          return PASSWORD;
        case 7: // MQ_NICKNAME
          return MQ_NICKNAME;
        case 8: // MMC_BALANCE
          return MMC_BALANCE;
        case 9: // MQC_BALANCE
          return MQC_BALANCE;
        case 10: // TIME_FRAMES
          return TIME_FRAMES;
        case 11: // ALLOWED_BANK_IDS
          return ALLOWED_BANK_IDS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __BANKID_ISSET_ID = 1;
  private static final int __ACTIVE_ISSET_ID = 2;
  private static final int __MMCBALANCE_ISSET_ID = 3;
  private static final int __MQCBALANCE_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.BANK_ID, new org.apache.thrift.meta_data.FieldMetaData("bankId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.ALLOWED_GAMES, new org.apache.thrift.meta_data.FieldMetaData("allowedGames", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64            , "long"))));
    tmpMap.put(_Fields.ACTIVE, new org.apache.thrift.meta_data.FieldMetaData("active", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.USERNAME, new org.apache.thrift.meta_data.FieldMetaData("username", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PASSWORD, new org.apache.thrift.meta_data.FieldMetaData("password", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MQ_NICKNAME, new org.apache.thrift.meta_data.FieldMetaData("mqNickname", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MMC_BALANCE, new org.apache.thrift.meta_data.FieldMetaData("mmcBalance", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.MQC_BALANCE, new org.apache.thrift.meta_data.FieldMetaData("mqcBalance", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.TIME_FRAMES, new org.apache.thrift.meta_data.FieldMetaData("timeFrames", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TTimeFrame.class))));
    tmpMap.put(_Fields.ALLOWED_BANK_IDS, new org.apache.thrift.meta_data.FieldMetaData("allowedBankIds", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64            , "long"))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TBotConfigInfo.class, metaDataMap);
  }

  public TBotConfigInfo() {
  }

  public TBotConfigInfo(
    long id,
    long bankId,
    java.util.Set<java.lang.Long> allowedGames,
    boolean active,
    java.lang.String username,
    java.lang.String password,
    java.lang.String mqNickname,
    long mmcBalance,
    long mqcBalance,
    java.util.Set<TTimeFrame> timeFrames,
    java.util.Set<java.lang.Long> allowedBankIds)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.bankId = bankId;
    setBankIdIsSet(true);
    this.allowedGames = allowedGames;
    this.active = active;
    setActiveIsSet(true);
    this.username = username;
    this.password = password;
    this.mqNickname = mqNickname;
    this.mmcBalance = mmcBalance;
    setMmcBalanceIsSet(true);
    this.mqcBalance = mqcBalance;
    setMqcBalanceIsSet(true);
    this.timeFrames = timeFrames;
    this.allowedBankIds = allowedBankIds;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TBotConfigInfo(TBotConfigInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    this.bankId = other.bankId;
    if (other.isSetAllowedGames()) {
      java.util.Set<java.lang.Long> __this__allowedGames = new java.util.HashSet<java.lang.Long>(other.allowedGames.size());
      for (java.lang.Long other_element : other.allowedGames) {
        __this__allowedGames.add(other_element);
      }
      this.allowedGames = __this__allowedGames;
    }
    this.active = other.active;
    if (other.isSetUsername()) {
      this.username = other.username;
    }
    if (other.isSetPassword()) {
      this.password = other.password;
    }
    if (other.isSetMqNickname()) {
      this.mqNickname = other.mqNickname;
    }
    this.mmcBalance = other.mmcBalance;
    this.mqcBalance = other.mqcBalance;
    if (other.isSetTimeFrames()) {
      java.util.Set<TTimeFrame> __this__timeFrames = new java.util.HashSet<TTimeFrame>(other.timeFrames.size());
      for (TTimeFrame other_element : other.timeFrames) {
        __this__timeFrames.add(new TTimeFrame(other_element));
      }
      this.timeFrames = __this__timeFrames;
    }
    if (other.isSetAllowedBankIds()) {
      java.util.Set<java.lang.Long> __this__allowedBankIds = new java.util.HashSet<java.lang.Long>(other.allowedBankIds.size());
      for (java.lang.Long other_element : other.allowedBankIds) {
        __this__allowedBankIds.add(other_element);
      }
      this.allowedBankIds = __this__allowedBankIds;
    }
  }

  @Override
  public TBotConfigInfo deepCopy() {
    return new TBotConfigInfo(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    setBankIdIsSet(false);
    this.bankId = 0;
    this.allowedGames = null;
    setActiveIsSet(false);
    this.active = false;
    this.username = null;
    this.password = null;
    this.mqNickname = null;
    setMmcBalanceIsSet(false);
    this.mmcBalance = 0;
    setMqcBalanceIsSet(false);
    this.mqcBalance = 0;
    this.timeFrames = null;
    this.allowedBankIds = null;
  }

  public long getId() {
    return this.id;
  }

  public TBotConfigInfo setId(long id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public long getBankId() {
    return this.bankId;
  }

  public TBotConfigInfo setBankId(long bankId) {
    this.bankId = bankId;
    setBankIdIsSet(true);
    return this;
  }

  public void unsetBankId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BANKID_ISSET_ID);
  }

  /** Returns true if field bankId is set (has been assigned a value) and false otherwise */
  public boolean isSetBankId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BANKID_ISSET_ID);
  }

  public void setBankIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BANKID_ISSET_ID, value);
  }

  public int getAllowedGamesSize() {
    return (this.allowedGames == null) ? 0 : this.allowedGames.size();
  }

  public java.util.Iterator<java.lang.Long> getAllowedGamesIterator() {
    return (this.allowedGames == null) ? null : this.allowedGames.iterator();
  }

  public void addToAllowedGames(long elem) {
    if (this.allowedGames == null) {
      this.allowedGames = new java.util.HashSet<java.lang.Long>();
    }
    this.allowedGames.add(elem);
  }

  public java.util.Set<java.lang.Long> getAllowedGames() {
    return this.allowedGames;
  }

  public TBotConfigInfo setAllowedGames(java.util.Set<java.lang.Long> allowedGames) {
    this.allowedGames = allowedGames;
    return this;
  }

  public void unsetAllowedGames() {
    this.allowedGames = null;
  }

  /** Returns true if field allowedGames is set (has been assigned a value) and false otherwise */
  public boolean isSetAllowedGames() {
    return this.allowedGames != null;
  }

  public void setAllowedGamesIsSet(boolean value) {
    if (!value) {
      this.allowedGames = null;
    }
  }

  public boolean isActive() {
    return this.active;
  }

  public TBotConfigInfo setActive(boolean active) {
    this.active = active;
    setActiveIsSet(true);
    return this;
  }

  public void unsetActive() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ACTIVE_ISSET_ID);
  }

  /** Returns true if field active is set (has been assigned a value) and false otherwise */
  public boolean isSetActive() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ACTIVE_ISSET_ID);
  }

  public void setActiveIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ACTIVE_ISSET_ID, value);
  }

  public java.lang.String getUsername() {
    return this.username;
  }

  public TBotConfigInfo setUsername(java.lang.String username) {
    this.username = username;
    return this;
  }

  public void unsetUsername() {
    this.username = null;
  }

  /** Returns true if field username is set (has been assigned a value) and false otherwise */
  public boolean isSetUsername() {
    return this.username != null;
  }

  public void setUsernameIsSet(boolean value) {
    if (!value) {
      this.username = null;
    }
  }

  public java.lang.String getPassword() {
    return this.password;
  }

  public TBotConfigInfo setPassword(java.lang.String password) {
    this.password = password;
    return this;
  }

  public void unsetPassword() {
    this.password = null;
  }

  /** Returns true if field password is set (has been assigned a value) and false otherwise */
  public boolean isSetPassword() {
    return this.password != null;
  }

  public void setPasswordIsSet(boolean value) {
    if (!value) {
      this.password = null;
    }
  }

  public java.lang.String getMqNickname() {
    return this.mqNickname;
  }

  public TBotConfigInfo setMqNickname(java.lang.String mqNickname) {
    this.mqNickname = mqNickname;
    return this;
  }

  public void unsetMqNickname() {
    this.mqNickname = null;
  }

  /** Returns true if field mqNickname is set (has been assigned a value) and false otherwise */
  public boolean isSetMqNickname() {
    return this.mqNickname != null;
  }

  public void setMqNicknameIsSet(boolean value) {
    if (!value) {
      this.mqNickname = null;
    }
  }

  public long getMmcBalance() {
    return this.mmcBalance;
  }

  public TBotConfigInfo setMmcBalance(long mmcBalance) {
    this.mmcBalance = mmcBalance;
    setMmcBalanceIsSet(true);
    return this;
  }

  public void unsetMmcBalance() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MMCBALANCE_ISSET_ID);
  }

  /** Returns true if field mmcBalance is set (has been assigned a value) and false otherwise */
  public boolean isSetMmcBalance() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MMCBALANCE_ISSET_ID);
  }

  public void setMmcBalanceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MMCBALANCE_ISSET_ID, value);
  }

  public long getMqcBalance() {
    return this.mqcBalance;
  }

  public TBotConfigInfo setMqcBalance(long mqcBalance) {
    this.mqcBalance = mqcBalance;
    setMqcBalanceIsSet(true);
    return this;
  }

  public void unsetMqcBalance() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MQCBALANCE_ISSET_ID);
  }

  /** Returns true if field mqcBalance is set (has been assigned a value) and false otherwise */
  public boolean isSetMqcBalance() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MQCBALANCE_ISSET_ID);
  }

  public void setMqcBalanceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MQCBALANCE_ISSET_ID, value);
  }

  public int getTimeFramesSize() {
    return (this.timeFrames == null) ? 0 : this.timeFrames.size();
  }

  public java.util.Iterator<TTimeFrame> getTimeFramesIterator() {
    return (this.timeFrames == null) ? null : this.timeFrames.iterator();
  }

  public void addToTimeFrames(TTimeFrame elem) {
    if (this.timeFrames == null) {
      this.timeFrames = new java.util.HashSet<TTimeFrame>();
    }
    this.timeFrames.add(elem);
  }

  public java.util.Set<TTimeFrame> getTimeFrames() {
    return this.timeFrames;
  }

  public TBotConfigInfo setTimeFrames(java.util.Set<TTimeFrame> timeFrames) {
    this.timeFrames = timeFrames;
    return this;
  }

  public void unsetTimeFrames() {
    this.timeFrames = null;
  }

  /** Returns true if field timeFrames is set (has been assigned a value) and false otherwise */
  public boolean isSetTimeFrames() {
    return this.timeFrames != null;
  }

  public void setTimeFramesIsSet(boolean value) {
    if (!value) {
      this.timeFrames = null;
    }
  }

  public int getAllowedBankIdsSize() {
    return (this.allowedBankIds == null) ? 0 : this.allowedBankIds.size();
  }

  public java.util.Iterator<java.lang.Long> getAllowedBankIdsIterator() {
    return (this.allowedBankIds == null) ? null : this.allowedBankIds.iterator();
  }

  public void addToAllowedBankIds(long elem) {
    if (this.allowedBankIds == null) {
      this.allowedBankIds = new java.util.HashSet<java.lang.Long>();
    }
    this.allowedBankIds.add(elem);
  }

  public java.util.Set<java.lang.Long> getAllowedBankIds() {
    return this.allowedBankIds;
  }

  public TBotConfigInfo setAllowedBankIds(java.util.Set<java.lang.Long> allowedBankIds) {
    this.allowedBankIds = allowedBankIds;
    return this;
  }

  public void unsetAllowedBankIds() {
    this.allowedBankIds = null;
  }

  /** Returns true if field allowedBankIds is set (has been assigned a value) and false otherwise */
  public boolean isSetAllowedBankIds() {
    return this.allowedBankIds != null;
  }

  public void setAllowedBankIdsIsSet(boolean value) {
    if (!value) {
      this.allowedBankIds = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Long)value);
      }
      break;

    case BANK_ID:
      if (value == null) {
        unsetBankId();
      } else {
        setBankId((java.lang.Long)value);
      }
      break;

    case ALLOWED_GAMES:
      if (value == null) {
        unsetAllowedGames();
      } else {
        setAllowedGames((java.util.Set<java.lang.Long>)value);
      }
      break;

    case ACTIVE:
      if (value == null) {
        unsetActive();
      } else {
        setActive((java.lang.Boolean)value);
      }
      break;

    case USERNAME:
      if (value == null) {
        unsetUsername();
      } else {
        setUsername((java.lang.String)value);
      }
      break;

    case PASSWORD:
      if (value == null) {
        unsetPassword();
      } else {
        setPassword((java.lang.String)value);
      }
      break;

    case MQ_NICKNAME:
      if (value == null) {
        unsetMqNickname();
      } else {
        setMqNickname((java.lang.String)value);
      }
      break;

    case MMC_BALANCE:
      if (value == null) {
        unsetMmcBalance();
      } else {
        setMmcBalance((java.lang.Long)value);
      }
      break;

    case MQC_BALANCE:
      if (value == null) {
        unsetMqcBalance();
      } else {
        setMqcBalance((java.lang.Long)value);
      }
      break;

    case TIME_FRAMES:
      if (value == null) {
        unsetTimeFrames();
      } else {
        setTimeFrames((java.util.Set<TTimeFrame>)value);
      }
      break;

    case ALLOWED_BANK_IDS:
      if (value == null) {
        unsetAllowedBankIds();
      } else {
        setAllowedBankIds((java.util.Set<java.lang.Long>)value);
      }
      break;

    }
  }

  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case BANK_ID:
      return getBankId();

    case ALLOWED_GAMES:
      return getAllowedGames();

    case ACTIVE:
      return isActive();

    case USERNAME:
      return getUsername();

    case PASSWORD:
      return getPassword();

    case MQ_NICKNAME:
      return getMqNickname();

    case MMC_BALANCE:
      return getMmcBalance();

    case MQC_BALANCE:
      return getMqcBalance();

    case TIME_FRAMES:
      return getTimeFrames();

    case ALLOWED_BANK_IDS:
      return getAllowedBankIds();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case BANK_ID:
      return isSetBankId();
    case ALLOWED_GAMES:
      return isSetAllowedGames();
    case ACTIVE:
      return isSetActive();
    case USERNAME:
      return isSetUsername();
    case PASSWORD:
      return isSetPassword();
    case MQ_NICKNAME:
      return isSetMqNickname();
    case MMC_BALANCE:
      return isSetMmcBalance();
    case MQC_BALANCE:
      return isSetMqcBalance();
    case TIME_FRAMES:
      return isSetTimeFrames();
    case ALLOWED_BANK_IDS:
      return isSetAllowedBankIds();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TBotConfigInfo)
      return this.equals((TBotConfigInfo)that);
    return false;
  }

  public boolean equals(TBotConfigInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_bankId = true;
    boolean that_present_bankId = true;
    if (this_present_bankId || that_present_bankId) {
      if (!(this_present_bankId && that_present_bankId))
        return false;
      if (this.bankId != that.bankId)
        return false;
    }

    boolean this_present_allowedGames = true && this.isSetAllowedGames();
    boolean that_present_allowedGames = true && that.isSetAllowedGames();
    if (this_present_allowedGames || that_present_allowedGames) {
      if (!(this_present_allowedGames && that_present_allowedGames))
        return false;
      if (!this.allowedGames.equals(that.allowedGames))
        return false;
    }

    boolean this_present_active = true;
    boolean that_present_active = true;
    if (this_present_active || that_present_active) {
      if (!(this_present_active && that_present_active))
        return false;
      if (this.active != that.active)
        return false;
    }

    boolean this_present_username = true && this.isSetUsername();
    boolean that_present_username = true && that.isSetUsername();
    if (this_present_username || that_present_username) {
      if (!(this_present_username && that_present_username))
        return false;
      if (!this.username.equals(that.username))
        return false;
    }

    boolean this_present_password = true && this.isSetPassword();
    boolean that_present_password = true && that.isSetPassword();
    if (this_present_password || that_present_password) {
      if (!(this_present_password && that_present_password))
        return false;
      if (!this.password.equals(that.password))
        return false;
    }

    boolean this_present_mqNickname = true && this.isSetMqNickname();
    boolean that_present_mqNickname = true && that.isSetMqNickname();
    if (this_present_mqNickname || that_present_mqNickname) {
      if (!(this_present_mqNickname && that_present_mqNickname))
        return false;
      if (!this.mqNickname.equals(that.mqNickname))
        return false;
    }

    boolean this_present_mmcBalance = true;
    boolean that_present_mmcBalance = true;
    if (this_present_mmcBalance || that_present_mmcBalance) {
      if (!(this_present_mmcBalance && that_present_mmcBalance))
        return false;
      if (this.mmcBalance != that.mmcBalance)
        return false;
    }

    boolean this_present_mqcBalance = true;
    boolean that_present_mqcBalance = true;
    if (this_present_mqcBalance || that_present_mqcBalance) {
      if (!(this_present_mqcBalance && that_present_mqcBalance))
        return false;
      if (this.mqcBalance != that.mqcBalance)
        return false;
    }

    boolean this_present_timeFrames = true && this.isSetTimeFrames();
    boolean that_present_timeFrames = true && that.isSetTimeFrames();
    if (this_present_timeFrames || that_present_timeFrames) {
      if (!(this_present_timeFrames && that_present_timeFrames))
        return false;
      if (!this.timeFrames.equals(that.timeFrames))
        return false;
    }

    boolean this_present_allowedBankIds = true && this.isSetAllowedBankIds();
    boolean that_present_allowedBankIds = true && that.isSetAllowedBankIds();
    if (this_present_allowedBankIds || that_present_allowedBankIds) {
      if (!(this_present_allowedBankIds && that_present_allowedBankIds))
        return false;
      if (!this.allowedBankIds.equals(that.allowedBankIds))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(id);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(bankId);

    hashCode = hashCode * 8191 + ((isSetAllowedGames()) ? 131071 : 524287);
    if (isSetAllowedGames())
      hashCode = hashCode * 8191 + allowedGames.hashCode();

    hashCode = hashCode * 8191 + ((active) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetUsername()) ? 131071 : 524287);
    if (isSetUsername())
      hashCode = hashCode * 8191 + username.hashCode();

    hashCode = hashCode * 8191 + ((isSetPassword()) ? 131071 : 524287);
    if (isSetPassword())
      hashCode = hashCode * 8191 + password.hashCode();

    hashCode = hashCode * 8191 + ((isSetMqNickname()) ? 131071 : 524287);
    if (isSetMqNickname())
      hashCode = hashCode * 8191 + mqNickname.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(mmcBalance);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(mqcBalance);

    hashCode = hashCode * 8191 + ((isSetTimeFrames()) ? 131071 : 524287);
    if (isSetTimeFrames())
      hashCode = hashCode * 8191 + timeFrames.hashCode();

    hashCode = hashCode * 8191 + ((isSetAllowedBankIds()) ? 131071 : 524287);
    if (isSetAllowedBankIds())
      hashCode = hashCode * 8191 + allowedBankIds.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TBotConfigInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetId(), other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBankId(), other.isSetBankId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBankId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bankId, other.bankId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAllowedGames(), other.isSetAllowedGames());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAllowedGames()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.allowedGames, other.allowedGames);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetActive(), other.isSetActive());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetActive()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.active, other.active);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUsername(), other.isSetUsername());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsername()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.username, other.username);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPassword(), other.isSetPassword());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPassword()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.password, other.password);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMqNickname(), other.isSetMqNickname());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMqNickname()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mqNickname, other.mqNickname);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMmcBalance(), other.isSetMmcBalance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMmcBalance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mmcBalance, other.mmcBalance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMqcBalance(), other.isSetMqcBalance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMqcBalance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mqcBalance, other.mqcBalance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTimeFrames(), other.isSetTimeFrames());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimeFrames()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timeFrames, other.timeFrames);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAllowedBankIds(), other.isSetAllowedBankIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAllowedBankIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.allowedBankIds, other.allowedBankIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TBotConfigInfo(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("bankId:");
    sb.append(this.bankId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("allowedGames:");
    if (this.allowedGames == null) {
      sb.append("null");
    } else {
      sb.append(this.allowedGames);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("active:");
    sb.append(this.active);
    first = false;
    if (!first) sb.append(", ");
    sb.append("username:");
    if (this.username == null) {
      sb.append("null");
    } else {
      sb.append(this.username);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("password:");
    if (this.password == null) {
      sb.append("null");
    } else {
      sb.append(this.password);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("mqNickname:");
    if (this.mqNickname == null) {
      sb.append("null");
    } else {
      sb.append(this.mqNickname);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("mmcBalance:");
    sb.append(this.mmcBalance);
    first = false;
    if (!first) sb.append(", ");
    sb.append("mqcBalance:");
    sb.append(this.mqcBalance);
    first = false;
    if (!first) sb.append(", ");
    sb.append("timeFrames:");
    if (this.timeFrames == null) {
      sb.append("null");
    } else {
      sb.append(this.timeFrames);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("allowedBankIds:");
    if (this.allowedBankIds == null) {
      sb.append("null");
    } else {
      sb.append(this.allowedBankIds);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TBotConfigInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TBotConfigInfoStandardScheme getScheme() {
      return new TBotConfigInfoStandardScheme();
    }
  }

  private static class TBotConfigInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<TBotConfigInfo> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, TBotConfigInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BANK_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.bankId = iprot.readI64();
              struct.setBankIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ALLOWED_GAMES
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set228 = iprot.readSetBegin();
                struct.allowedGames = new java.util.HashSet<java.lang.Long>(2*_set228.size);
                long _elem229;
                for (int _i230 = 0; _i230 < _set228.size; ++_i230)
                {
                  _elem229 = iprot.readI64();
                  struct.allowedGames.add(_elem229);
                }
                iprot.readSetEnd();
              }
              struct.setAllowedGamesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ACTIVE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.active = iprot.readBool();
              struct.setActiveIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // USERNAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.username = iprot.readString();
              struct.setUsernameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // PASSWORD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.password = iprot.readString();
              struct.setPasswordIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // MQ_NICKNAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mqNickname = iprot.readString();
              struct.setMqNicknameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // MMC_BALANCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.mmcBalance = iprot.readI64();
              struct.setMmcBalanceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // MQC_BALANCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.mqcBalance = iprot.readI64();
              struct.setMqcBalanceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // TIME_FRAMES
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set231 = iprot.readSetBegin();
                struct.timeFrames = new java.util.HashSet<TTimeFrame>(2*_set231.size);
                TTimeFrame _elem232;
                for (int _i233 = 0; _i233 < _set231.size; ++_i233)
                {
                  _elem232 = new TTimeFrame();
                  _elem232.read(iprot);
                  struct.timeFrames.add(_elem232);
                }
                iprot.readSetEnd();
              }
              struct.setTimeFramesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // ALLOWED_BANK_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set234 = iprot.readSetBegin();
                struct.allowedBankIds = new java.util.HashSet<java.lang.Long>(2*_set234.size);
                long _elem235;
                for (int _i236 = 0; _i236 < _set234.size; ++_i236)
                {
                  _elem235 = iprot.readI64();
                  struct.allowedBankIds.add(_elem235);
                }
                iprot.readSetEnd();
              }
              struct.setAllowedBankIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, TBotConfigInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI64(struct.id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BANK_ID_FIELD_DESC);
      oprot.writeI64(struct.bankId);
      oprot.writeFieldEnd();
      if (struct.allowedGames != null) {
        oprot.writeFieldBegin(ALLOWED_GAMES_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I64, struct.allowedGames.size()));
          for (long _iter237 : struct.allowedGames)
          {
            oprot.writeI64(_iter237);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ACTIVE_FIELD_DESC);
      oprot.writeBool(struct.active);
      oprot.writeFieldEnd();
      if (struct.username != null) {
        oprot.writeFieldBegin(USERNAME_FIELD_DESC);
        oprot.writeString(struct.username);
        oprot.writeFieldEnd();
      }
      if (struct.password != null) {
        oprot.writeFieldBegin(PASSWORD_FIELD_DESC);
        oprot.writeString(struct.password);
        oprot.writeFieldEnd();
      }
      if (struct.mqNickname != null) {
        oprot.writeFieldBegin(MQ_NICKNAME_FIELD_DESC);
        oprot.writeString(struct.mqNickname);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(MMC_BALANCE_FIELD_DESC);
      oprot.writeI64(struct.mmcBalance);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MQC_BALANCE_FIELD_DESC);
      oprot.writeI64(struct.mqcBalance);
      oprot.writeFieldEnd();
      if (struct.timeFrames != null) {
        oprot.writeFieldBegin(TIME_FRAMES_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, struct.timeFrames.size()));
          for (TTimeFrame _iter238 : struct.timeFrames)
          {
            _iter238.write(oprot);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.allowedBankIds != null) {
        oprot.writeFieldBegin(ALLOWED_BANK_IDS_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I64, struct.allowedBankIds.size()));
          for (long _iter239 : struct.allowedBankIds)
          {
            oprot.writeI64(_iter239);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TBotConfigInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TBotConfigInfoTupleScheme getScheme() {
      return new TBotConfigInfoTupleScheme();
    }
  }

  private static class TBotConfigInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<TBotConfigInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TBotConfigInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetBankId()) {
        optionals.set(1);
      }
      if (struct.isSetAllowedGames()) {
        optionals.set(2);
      }
      if (struct.isSetActive()) {
        optionals.set(3);
      }
      if (struct.isSetUsername()) {
        optionals.set(4);
      }
      if (struct.isSetPassword()) {
        optionals.set(5);
      }
      if (struct.isSetMqNickname()) {
        optionals.set(6);
      }
      if (struct.isSetMmcBalance()) {
        optionals.set(7);
      }
      if (struct.isSetMqcBalance()) {
        optionals.set(8);
      }
      if (struct.isSetTimeFrames()) {
        optionals.set(9);
      }
      if (struct.isSetAllowedBankIds()) {
        optionals.set(10);
      }
      oprot.writeBitSet(optionals, 11);
      if (struct.isSetId()) {
        oprot.writeI64(struct.id);
      }
      if (struct.isSetBankId()) {
        oprot.writeI64(struct.bankId);
      }
      if (struct.isSetAllowedGames()) {
        {
          oprot.writeI32(struct.allowedGames.size());
          for (long _iter240 : struct.allowedGames)
          {
            oprot.writeI64(_iter240);
          }
        }
      }
      if (struct.isSetActive()) {
        oprot.writeBool(struct.active);
      }
      if (struct.isSetUsername()) {
        oprot.writeString(struct.username);
      }
      if (struct.isSetPassword()) {
        oprot.writeString(struct.password);
      }
      if (struct.isSetMqNickname()) {
        oprot.writeString(struct.mqNickname);
      }
      if (struct.isSetMmcBalance()) {
        oprot.writeI64(struct.mmcBalance);
      }
      if (struct.isSetMqcBalance()) {
        oprot.writeI64(struct.mqcBalance);
      }
      if (struct.isSetTimeFrames()) {
        {
          oprot.writeI32(struct.timeFrames.size());
          for (TTimeFrame _iter241 : struct.timeFrames)
          {
            _iter241.write(oprot);
          }
        }
      }
      if (struct.isSetAllowedBankIds()) {
        {
          oprot.writeI32(struct.allowedBankIds.size());
          for (long _iter242 : struct.allowedBankIds)
          {
            oprot.writeI64(_iter242);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TBotConfigInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(11);
      if (incoming.get(0)) {
        struct.id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.bankId = iprot.readI64();
        struct.setBankIdIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TSet _set243 = new org.apache.thrift.protocol.TSet(TType.I64, iprot.readI32());
          struct.allowedGames = new java.util.HashSet<java.lang.Long>(2*_set243.size);
          long _elem244;
          for (int _i245 = 0; _i245 < _set243.size; ++_i245)
          {
            _elem244 = iprot.readI64();
            struct.allowedGames.add(_elem244);
          }
        }
        struct.setAllowedGamesIsSet(true);
      }
      if (incoming.get(3)) {
        struct.active = iprot.readBool();
        struct.setActiveIsSet(true);
      }
      if (incoming.get(4)) {
        struct.username = iprot.readString();
        struct.setUsernameIsSet(true);
      }
      if (incoming.get(5)) {
        struct.password = iprot.readString();
        struct.setPasswordIsSet(true);
      }
      if (incoming.get(6)) {
        struct.mqNickname = iprot.readString();
        struct.setMqNicknameIsSet(true);
      }
      if (incoming.get(7)) {
        struct.mmcBalance = iprot.readI64();
        struct.setMmcBalanceIsSet(true);
      }
      if (incoming.get(8)) {
        struct.mqcBalance = iprot.readI64();
        struct.setMqcBalanceIsSet(true);
      }
      if (incoming.get(9)) {
        {
          org.apache.thrift.protocol.TSet _set246 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.timeFrames = new java.util.HashSet<TTimeFrame>(2*_set246.size);
          TTimeFrame _elem247;
          for (int _i248 = 0; _i248 < _set246.size; ++_i248)
          {
            _elem247 = new TTimeFrame();
            _elem247.read(iprot);
            struct.timeFrames.add(_elem247);
          }
        }
        struct.setTimeFramesIsSet(true);
      }
      if (incoming.get(10)) {
        {
          org.apache.thrift.protocol.TSet _set249 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.allowedBankIds = new java.util.HashSet<java.lang.Long>(2*_set249.size);
          long _elem250;
          for (int _i251 = 0; _i251 < _set249.size; ++_i251)
          {
            _elem250 = iprot.readI64();
            struct.allowedBankIds.add(_elem250);
          }
        }
        struct.setAllowedBankIdsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

