/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dgphoenix.casino.thrift;


public enum TBotState implements org.apache.thrift.TEnum {
  idle(0),
  observing(1),
  waiting_for_response(2),
  playing(3),
  wait_battle_players(4),
  need_sit_out(5);

  private final int value;

  private TBotState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TBotState findByValue(int value) {
    switch (value) {
      case 0:
        return idle;
      case 1:
        return observing;
      case 2:
        return waiting_for_response;
      case 3:
        return playing;
      case 4:
        return wait_battle_players;
      case 5:
        return need_sit_out;
      default:
        return null;
    }
  }
}
