/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dgphoenix.casino.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TBotStatus implements org.apache.thrift.TBase<TBotStatus, TBotStatus._Fields>, java.io.Serializable, Cloneable, Comparable<TBotStatus> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TBotStatus");

  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField MMC_BALANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("mmcBalance", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField MQC_BALANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("mqcBalance", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField ERROR_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("errorCode", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField ERROR_DETAILS_FIELD_DESC = new org.apache.thrift.protocol.TField("errorDetails", org.apache.thrift.protocol.TType.STRING, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TBotStatusStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TBotStatusTupleSchemeFactory();

  public int status; // required
  public long mmcBalance; // required
  public long mqcBalance; // required
  public boolean success; // required
  public int errorCode; // required
  public java.lang.String errorDetails; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STATUS((short)1, "status"),
    MMC_BALANCE((short)2, "mmcBalance"),
    MQC_BALANCE((short)3, "mqcBalance"),
    SUCCESS((short)4, "success"),
    ERROR_CODE((short)5, "errorCode"),
    ERROR_DETAILS((short)6, "errorDetails");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STATUS
          return STATUS;
        case 2: // MMC_BALANCE
          return MMC_BALANCE;
        case 3: // MQC_BALANCE
          return MQC_BALANCE;
        case 4: // SUCCESS
          return SUCCESS;
        case 5: // ERROR_CODE
          return ERROR_CODE;
        case 6: // ERROR_DETAILS
          return ERROR_DETAILS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __STATUS_ISSET_ID = 0;
  private static final int __MMCBALANCE_ISSET_ID = 1;
  private static final int __MQCBALANCE_ISSET_ID = 2;
  private static final int __SUCCESS_ISSET_ID = 3;
  private static final int __ERRORCODE_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.MMC_BALANCE, new org.apache.thrift.meta_data.FieldMetaData("mmcBalance", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.MQC_BALANCE, new org.apache.thrift.meta_data.FieldMetaData("mqcBalance", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ERROR_CODE, new org.apache.thrift.meta_data.FieldMetaData("errorCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.ERROR_DETAILS, new org.apache.thrift.meta_data.FieldMetaData("errorDetails", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TBotStatus.class, metaDataMap);
  }

  public TBotStatus() {
  }

  public TBotStatus(
    int status,
    long mmcBalance,
    long mqcBalance,
    boolean success,
    int errorCode,
    java.lang.String errorDetails)
  {
    this();
    this.status = status;
    setStatusIsSet(true);
    this.mmcBalance = mmcBalance;
    setMmcBalanceIsSet(true);
    this.mqcBalance = mqcBalance;
    setMqcBalanceIsSet(true);
    this.success = success;
    setSuccessIsSet(true);
    this.errorCode = errorCode;
    setErrorCodeIsSet(true);
    this.errorDetails = errorDetails;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TBotStatus(TBotStatus other) {
    __isset_bitfield = other.__isset_bitfield;
    this.status = other.status;
    this.mmcBalance = other.mmcBalance;
    this.mqcBalance = other.mqcBalance;
    this.success = other.success;
    this.errorCode = other.errorCode;
    if (other.isSetErrorDetails()) {
      this.errorDetails = other.errorDetails;
    }
  }

  public TBotStatus deepCopy() {
    return new TBotStatus(this);
  }

  @Override
  public void clear() {
    setStatusIsSet(false);
    this.status = 0;
    setMmcBalanceIsSet(false);
    this.mmcBalance = 0;
    setMqcBalanceIsSet(false);
    this.mqcBalance = 0;
    setSuccessIsSet(false);
    this.success = false;
    setErrorCodeIsSet(false);
    this.errorCode = 0;
    this.errorDetails = null;
  }

  public int getStatus() {
    return this.status;
  }

  public TBotStatus setStatus(int status) {
    this.status = status;
    setStatusIsSet(true);
    return this;
  }

  public void unsetStatus() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  public void setStatusIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STATUS_ISSET_ID, value);
  }

  public long getMmcBalance() {
    return this.mmcBalance;
  }

  public TBotStatus setMmcBalance(long mmcBalance) {
    this.mmcBalance = mmcBalance;
    setMmcBalanceIsSet(true);
    return this;
  }

  public void unsetMmcBalance() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MMCBALANCE_ISSET_ID);
  }

  /** Returns true if field mmcBalance is set (has been assigned a value) and false otherwise */
  public boolean isSetMmcBalance() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MMCBALANCE_ISSET_ID);
  }

  public void setMmcBalanceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MMCBALANCE_ISSET_ID, value);
  }

  public long getMqcBalance() {
    return this.mqcBalance;
  }

  public TBotStatus setMqcBalance(long mqcBalance) {
    this.mqcBalance = mqcBalance;
    setMqcBalanceIsSet(true);
    return this;
  }

  public void unsetMqcBalance() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MQCBALANCE_ISSET_ID);
  }

  /** Returns true if field mqcBalance is set (has been assigned a value) and false otherwise */
  public boolean isSetMqcBalance() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MQCBALANCE_ISSET_ID);
  }

  public void setMqcBalanceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MQCBALANCE_ISSET_ID, value);
  }

  public boolean isSuccess() {
    return this.success;
  }

  public TBotStatus setSuccess(boolean success) {
    this.success = success;
    setSuccessIsSet(true);
    return this;
  }

  public void unsetSuccess() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SUCCESS_ISSET_ID);
  }

  /** Returns true if field success is set (has been assigned a value) and false otherwise */
  public boolean isSetSuccess() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SUCCESS_ISSET_ID);
  }

  public void setSuccessIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SUCCESS_ISSET_ID, value);
  }

  public int getErrorCode() {
    return this.errorCode;
  }

  public TBotStatus setErrorCode(int errorCode) {
    this.errorCode = errorCode;
    setErrorCodeIsSet(true);
    return this;
  }

  public void unsetErrorCode() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ERRORCODE_ISSET_ID);
  }

  /** Returns true if field errorCode is set (has been assigned a value) and false otherwise */
  public boolean isSetErrorCode() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ERRORCODE_ISSET_ID);
  }

  public void setErrorCodeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ERRORCODE_ISSET_ID, value);
  }

  public java.lang.String getErrorDetails() {
    return this.errorDetails;
  }

  public TBotStatus setErrorDetails(java.lang.String errorDetails) {
    this.errorDetails = errorDetails;
    return this;
  }

  public void unsetErrorDetails() {
    this.errorDetails = null;
  }

  /** Returns true if field errorDetails is set (has been assigned a value) and false otherwise */
  public boolean isSetErrorDetails() {
    return this.errorDetails != null;
  }

  public void setErrorDetailsIsSet(boolean value) {
    if (!value) {
      this.errorDetails = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((java.lang.Integer)value);
      }
      break;

    case MMC_BALANCE:
      if (value == null) {
        unsetMmcBalance();
      } else {
        setMmcBalance((java.lang.Long)value);
      }
      break;

    case MQC_BALANCE:
      if (value == null) {
        unsetMqcBalance();
      } else {
        setMqcBalance((java.lang.Long)value);
      }
      break;

    case SUCCESS:
      if (value == null) {
        unsetSuccess();
      } else {
        setSuccess((java.lang.Boolean)value);
      }
      break;

    case ERROR_CODE:
      if (value == null) {
        unsetErrorCode();
      } else {
        setErrorCode((java.lang.Integer)value);
      }
      break;

    case ERROR_DETAILS:
      if (value == null) {
        unsetErrorDetails();
      } else {
        setErrorDetails((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case STATUS:
      return getStatus();

    case MMC_BALANCE:
      return getMmcBalance();

    case MQC_BALANCE:
      return getMqcBalance();

    case SUCCESS:
      return isSuccess();

    case ERROR_CODE:
      return getErrorCode();

    case ERROR_DETAILS:
      return getErrorDetails();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case STATUS:
      return isSetStatus();
    case MMC_BALANCE:
      return isSetMmcBalance();
    case MQC_BALANCE:
      return isSetMqcBalance();
    case SUCCESS:
      return isSetSuccess();
    case ERROR_CODE:
      return isSetErrorCode();
    case ERROR_DETAILS:
      return isSetErrorDetails();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TBotStatus)
      return this.equals((TBotStatus)that);
    return false;
  }

  public boolean equals(TBotStatus that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_status = true;
    boolean that_present_status = true;
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (this.status != that.status)
        return false;
    }

    boolean this_present_mmcBalance = true;
    boolean that_present_mmcBalance = true;
    if (this_present_mmcBalance || that_present_mmcBalance) {
      if (!(this_present_mmcBalance && that_present_mmcBalance))
        return false;
      if (this.mmcBalance != that.mmcBalance)
        return false;
    }

    boolean this_present_mqcBalance = true;
    boolean that_present_mqcBalance = true;
    if (this_present_mqcBalance || that_present_mqcBalance) {
      if (!(this_present_mqcBalance && that_present_mqcBalance))
        return false;
      if (this.mqcBalance != that.mqcBalance)
        return false;
    }

    boolean this_present_success = true;
    boolean that_present_success = true;
    if (this_present_success || that_present_success) {
      if (!(this_present_success && that_present_success))
        return false;
      if (this.success != that.success)
        return false;
    }

    boolean this_present_errorCode = true;
    boolean that_present_errorCode = true;
    if (this_present_errorCode || that_present_errorCode) {
      if (!(this_present_errorCode && that_present_errorCode))
        return false;
      if (this.errorCode != that.errorCode)
        return false;
    }

    boolean this_present_errorDetails = true && this.isSetErrorDetails();
    boolean that_present_errorDetails = true && that.isSetErrorDetails();
    if (this_present_errorDetails || that_present_errorDetails) {
      if (!(this_present_errorDetails && that_present_errorDetails))
        return false;
      if (!this.errorDetails.equals(that.errorDetails))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + status;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(mmcBalance);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(mqcBalance);

    hashCode = hashCode * 8191 + ((success) ? 131071 : 524287);

    hashCode = hashCode * 8191 + errorCode;

    hashCode = hashCode * 8191 + ((isSetErrorDetails()) ? 131071 : 524287);
    if (isSetErrorDetails())
      hashCode = hashCode * 8191 + errorDetails.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TBotStatus other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetStatus()).compareTo(other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMmcBalance()).compareTo(other.isSetMmcBalance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMmcBalance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mmcBalance, other.mmcBalance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMqcBalance()).compareTo(other.isSetMqcBalance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMqcBalance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mqcBalance, other.mqcBalance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSuccess()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetErrorCode()).compareTo(other.isSetErrorCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetErrorCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.errorCode, other.errorCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetErrorDetails()).compareTo(other.isSetErrorDetails());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetErrorDetails()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.errorDetails, other.errorDetails);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TBotStatus(");
    boolean first = true;

    sb.append("status:");
    sb.append(this.status);
    first = false;
    if (!first) sb.append(", ");
    sb.append("mmcBalance:");
    sb.append(this.mmcBalance);
    first = false;
    if (!first) sb.append(", ");
    sb.append("mqcBalance:");
    sb.append(this.mqcBalance);
    first = false;
    if (!first) sb.append(", ");
    sb.append("success:");
    sb.append(this.success);
    first = false;
    if (!first) sb.append(", ");
    sb.append("errorCode:");
    sb.append(this.errorCode);
    first = false;
    if (!first) sb.append(", ");
    sb.append("errorDetails:");
    if (this.errorDetails == null) {
      sb.append("null");
    } else {
      sb.append(this.errorDetails);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TBotStatusStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TBotStatusStandardScheme getScheme() {
      return new TBotStatusStandardScheme();
    }
  }

  private static class TBotStatusStandardScheme extends org.apache.thrift.scheme.StandardScheme<TBotStatus> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TBotStatus struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status = iprot.readI32();
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MMC_BALANCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.mmcBalance = iprot.readI64();
              struct.setMmcBalanceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // MQC_BALANCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.mqcBalance = iprot.readI64();
              struct.setMqcBalanceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SUCCESS
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.success = iprot.readBool();
              struct.setSuccessIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ERROR_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.errorCode = iprot.readI32();
              struct.setErrorCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ERROR_DETAILS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.errorDetails = iprot.readString();
              struct.setErrorDetailsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TBotStatus struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(STATUS_FIELD_DESC);
      oprot.writeI32(struct.status);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MMC_BALANCE_FIELD_DESC);
      oprot.writeI64(struct.mmcBalance);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MQC_BALANCE_FIELD_DESC);
      oprot.writeI64(struct.mqcBalance);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
      oprot.writeBool(struct.success);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ERROR_CODE_FIELD_DESC);
      oprot.writeI32(struct.errorCode);
      oprot.writeFieldEnd();
      if (struct.errorDetails != null) {
        oprot.writeFieldBegin(ERROR_DETAILS_FIELD_DESC);
        oprot.writeString(struct.errorDetails);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TBotStatusTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TBotStatusTupleScheme getScheme() {
      return new TBotStatusTupleScheme();
    }
  }

  private static class TBotStatusTupleScheme extends org.apache.thrift.scheme.TupleScheme<TBotStatus> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TBotStatus struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetStatus()) {
        optionals.set(0);
      }
      if (struct.isSetMmcBalance()) {
        optionals.set(1);
      }
      if (struct.isSetMqcBalance()) {
        optionals.set(2);
      }
      if (struct.isSetSuccess()) {
        optionals.set(3);
      }
      if (struct.isSetErrorCode()) {
        optionals.set(4);
      }
      if (struct.isSetErrorDetails()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetStatus()) {
        oprot.writeI32(struct.status);
      }
      if (struct.isSetMmcBalance()) {
        oprot.writeI64(struct.mmcBalance);
      }
      if (struct.isSetMqcBalance()) {
        oprot.writeI64(struct.mqcBalance);
      }
      if (struct.isSetSuccess()) {
        oprot.writeBool(struct.success);
      }
      if (struct.isSetErrorCode()) {
        oprot.writeI32(struct.errorCode);
      }
      if (struct.isSetErrorDetails()) {
        oprot.writeString(struct.errorDetails);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TBotStatus struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.status = iprot.readI32();
        struct.setStatusIsSet(true);
      }
      if (incoming.get(1)) {
        struct.mmcBalance = iprot.readI64();
        struct.setMmcBalanceIsSet(true);
      }
      if (incoming.get(2)) {
        struct.mqcBalance = iprot.readI64();
        struct.setMqcBalanceIsSet(true);
      }
      if (incoming.get(3)) {
        struct.success = iprot.readBool();
        struct.setSuccessIsSet(true);
      }
      if (incoming.get(4)) {
        struct.errorCode = iprot.readI32();
        struct.setErrorCodeIsSet(true);
      }
      if (incoming.get(5)) {
        struct.errorDetails = iprot.readString();
        struct.setErrorDetailsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

