/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dgphoenix.casino.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TLeaderboardResult implements org.apache.thrift.TBase<TLeaderboardResult, TLeaderboardResult._Fields>, java.io.Serializable, Cloneable, Comparable<TLeaderboardResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TLeaderboardResult");

  private static final org.apache.thrift.protocol.TField LEADERBOARD_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("leaderboardId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField START_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("startDate", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField END_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("endDate", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField CURRENCY_FIELD_DESC = new org.apache.thrift.protocol.TField("currency", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField BANKS_FIELD_DESC = new org.apache.thrift.protocol.TField("banks", org.apache.thrift.protocol.TType.LIST, (short)5);
  private static final org.apache.thrift.protocol.TField GAMES_FIELD_DESC = new org.apache.thrift.protocol.TField("games", org.apache.thrift.protocol.TType.LIST, (short)6);
  private static final org.apache.thrift.protocol.TField WINNERS_FIELD_DESC = new org.apache.thrift.protocol.TField("winners", org.apache.thrift.protocol.TType.LIST, (short)7);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TLeaderboardResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TLeaderboardResultTupleSchemeFactory();

  public long leaderboardId; // required
  public long startDate; // required
  public long endDate; // required
  public java.lang.String currency; // required
  public java.util.List<java.lang.Long> banks; // required
  public java.util.List<java.lang.Long> games; // required
  public java.util.List<TLeaderboardWin> winners; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LEADERBOARD_ID((short)1, "leaderboardId"),
    START_DATE((short)2, "startDate"),
    END_DATE((short)3, "endDate"),
    CURRENCY((short)4, "currency"),
    BANKS((short)5, "banks"),
    GAMES((short)6, "games"),
    WINNERS((short)7, "winners");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LEADERBOARD_ID
          return LEADERBOARD_ID;
        case 2: // START_DATE
          return START_DATE;
        case 3: // END_DATE
          return END_DATE;
        case 4: // CURRENCY
          return CURRENCY;
        case 5: // BANKS
          return BANKS;
        case 6: // GAMES
          return GAMES;
        case 7: // WINNERS
          return WINNERS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LEADERBOARDID_ISSET_ID = 0;
  private static final int __STARTDATE_ISSET_ID = 1;
  private static final int __ENDDATE_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LEADERBOARD_ID, new org.apache.thrift.meta_data.FieldMetaData("leaderboardId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.START_DATE, new org.apache.thrift.meta_data.FieldMetaData("startDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.END_DATE, new org.apache.thrift.meta_data.FieldMetaData("endDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.CURRENCY, new org.apache.thrift.meta_data.FieldMetaData("currency", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BANKS, new org.apache.thrift.meta_data.FieldMetaData("banks", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64            , "long"))));
    tmpMap.put(_Fields.GAMES, new org.apache.thrift.meta_data.FieldMetaData("games", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64            , "long"))));
    tmpMap.put(_Fields.WINNERS, new org.apache.thrift.meta_data.FieldMetaData("winners", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TLeaderboardWin.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TLeaderboardResult.class, metaDataMap);
  }

  public TLeaderboardResult() {
  }

  public TLeaderboardResult(
    long leaderboardId,
    long startDate,
    long endDate,
    java.lang.String currency,
    java.util.List<java.lang.Long> banks,
    java.util.List<java.lang.Long> games,
    java.util.List<TLeaderboardWin> winners)
  {
    this();
    this.leaderboardId = leaderboardId;
    setLeaderboardIdIsSet(true);
    this.startDate = startDate;
    setStartDateIsSet(true);
    this.endDate = endDate;
    setEndDateIsSet(true);
    this.currency = currency;
    this.banks = banks;
    this.games = games;
    this.winners = winners;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TLeaderboardResult(TLeaderboardResult other) {
    __isset_bitfield = other.__isset_bitfield;
    this.leaderboardId = other.leaderboardId;
    this.startDate = other.startDate;
    this.endDate = other.endDate;
    if (other.isSetCurrency()) {
      this.currency = other.currency;
    }
    if (other.isSetBanks()) {
      java.util.List<java.lang.Long> __this__banks = new java.util.ArrayList<java.lang.Long>(other.banks.size());
      for (java.lang.Long other_element : other.banks) {
        __this__banks.add(other_element);
      }
      this.banks = __this__banks;
    }
    if (other.isSetGames()) {
      java.util.List<java.lang.Long> __this__games = new java.util.ArrayList<java.lang.Long>(other.games.size());
      for (java.lang.Long other_element : other.games) {
        __this__games.add(other_element);
      }
      this.games = __this__games;
    }
    if (other.isSetWinners()) {
      java.util.List<TLeaderboardWin> __this__winners = new java.util.ArrayList<TLeaderboardWin>(other.winners.size());
      for (TLeaderboardWin other_element : other.winners) {
        __this__winners.add(new TLeaderboardWin(other_element));
      }
      this.winners = __this__winners;
    }
  }

  public TLeaderboardResult deepCopy() {
    return new TLeaderboardResult(this);
  }

  @Override
  public void clear() {
    setLeaderboardIdIsSet(false);
    this.leaderboardId = 0;
    setStartDateIsSet(false);
    this.startDate = 0;
    setEndDateIsSet(false);
    this.endDate = 0;
    this.currency = null;
    this.banks = null;
    this.games = null;
    this.winners = null;
  }

  public long getLeaderboardId() {
    return this.leaderboardId;
  }

  public TLeaderboardResult setLeaderboardId(long leaderboardId) {
    this.leaderboardId = leaderboardId;
    setLeaderboardIdIsSet(true);
    return this;
  }

  public void unsetLeaderboardId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LEADERBOARDID_ISSET_ID);
  }

  /** Returns true if field leaderboardId is set (has been assigned a value) and false otherwise */
  public boolean isSetLeaderboardId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LEADERBOARDID_ISSET_ID);
  }

  public void setLeaderboardIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LEADERBOARDID_ISSET_ID, value);
  }

  public long getStartDate() {
    return this.startDate;
  }

  public TLeaderboardResult setStartDate(long startDate) {
    this.startDate = startDate;
    setStartDateIsSet(true);
    return this;
  }

  public void unsetStartDate() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STARTDATE_ISSET_ID);
  }

  /** Returns true if field startDate is set (has been assigned a value) and false otherwise */
  public boolean isSetStartDate() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STARTDATE_ISSET_ID);
  }

  public void setStartDateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STARTDATE_ISSET_ID, value);
  }

  public long getEndDate() {
    return this.endDate;
  }

  public TLeaderboardResult setEndDate(long endDate) {
    this.endDate = endDate;
    setEndDateIsSet(true);
    return this;
  }

  public void unsetEndDate() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ENDDATE_ISSET_ID);
  }

  /** Returns true if field endDate is set (has been assigned a value) and false otherwise */
  public boolean isSetEndDate() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ENDDATE_ISSET_ID);
  }

  public void setEndDateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ENDDATE_ISSET_ID, value);
  }

  public java.lang.String getCurrency() {
    return this.currency;
  }

  public TLeaderboardResult setCurrency(java.lang.String currency) {
    this.currency = currency;
    return this;
  }

  public void unsetCurrency() {
    this.currency = null;
  }

  /** Returns true if field currency is set (has been assigned a value) and false otherwise */
  public boolean isSetCurrency() {
    return this.currency != null;
  }

  public void setCurrencyIsSet(boolean value) {
    if (!value) {
      this.currency = null;
    }
  }

  public int getBanksSize() {
    return (this.banks == null) ? 0 : this.banks.size();
  }

  public java.util.Iterator<java.lang.Long> getBanksIterator() {
    return (this.banks == null) ? null : this.banks.iterator();
  }

  public void addToBanks(long elem) {
    if (this.banks == null) {
      this.banks = new java.util.ArrayList<java.lang.Long>();
    }
    this.banks.add(elem);
  }

  public java.util.List<java.lang.Long> getBanks() {
    return this.banks;
  }

  public TLeaderboardResult setBanks(java.util.List<java.lang.Long> banks) {
    this.banks = banks;
    return this;
  }

  public void unsetBanks() {
    this.banks = null;
  }

  /** Returns true if field banks is set (has been assigned a value) and false otherwise */
  public boolean isSetBanks() {
    return this.banks != null;
  }

  public void setBanksIsSet(boolean value) {
    if (!value) {
      this.banks = null;
    }
  }

  public int getGamesSize() {
    return (this.games == null) ? 0 : this.games.size();
  }

  public java.util.Iterator<java.lang.Long> getGamesIterator() {
    return (this.games == null) ? null : this.games.iterator();
  }

  public void addToGames(long elem) {
    if (this.games == null) {
      this.games = new java.util.ArrayList<java.lang.Long>();
    }
    this.games.add(elem);
  }

  public java.util.List<java.lang.Long> getGames() {
    return this.games;
  }

  public TLeaderboardResult setGames(java.util.List<java.lang.Long> games) {
    this.games = games;
    return this;
  }

  public void unsetGames() {
    this.games = null;
  }

  /** Returns true if field games is set (has been assigned a value) and false otherwise */
  public boolean isSetGames() {
    return this.games != null;
  }

  public void setGamesIsSet(boolean value) {
    if (!value) {
      this.games = null;
    }
  }

  public int getWinnersSize() {
    return (this.winners == null) ? 0 : this.winners.size();
  }

  public java.util.Iterator<TLeaderboardWin> getWinnersIterator() {
    return (this.winners == null) ? null : this.winners.iterator();
  }

  public void addToWinners(TLeaderboardWin elem) {
    if (this.winners == null) {
      this.winners = new java.util.ArrayList<TLeaderboardWin>();
    }
    this.winners.add(elem);
  }

  public java.util.List<TLeaderboardWin> getWinners() {
    return this.winners;
  }

  public TLeaderboardResult setWinners(java.util.List<TLeaderboardWin> winners) {
    this.winners = winners;
    return this;
  }

  public void unsetWinners() {
    this.winners = null;
  }

  /** Returns true if field winners is set (has been assigned a value) and false otherwise */
  public boolean isSetWinners() {
    return this.winners != null;
  }

  public void setWinnersIsSet(boolean value) {
    if (!value) {
      this.winners = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case LEADERBOARD_ID:
      if (value == null) {
        unsetLeaderboardId();
      } else {
        setLeaderboardId((java.lang.Long)value);
      }
      break;

    case START_DATE:
      if (value == null) {
        unsetStartDate();
      } else {
        setStartDate((java.lang.Long)value);
      }
      break;

    case END_DATE:
      if (value == null) {
        unsetEndDate();
      } else {
        setEndDate((java.lang.Long)value);
      }
      break;

    case CURRENCY:
      if (value == null) {
        unsetCurrency();
      } else {
        setCurrency((java.lang.String)value);
      }
      break;

    case BANKS:
      if (value == null) {
        unsetBanks();
      } else {
        setBanks((java.util.List<java.lang.Long>)value);
      }
      break;

    case GAMES:
      if (value == null) {
        unsetGames();
      } else {
        setGames((java.util.List<java.lang.Long>)value);
      }
      break;

    case WINNERS:
      if (value == null) {
        unsetWinners();
      } else {
        setWinners((java.util.List<TLeaderboardWin>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LEADERBOARD_ID:
      return getLeaderboardId();

    case START_DATE:
      return getStartDate();

    case END_DATE:
      return getEndDate();

    case CURRENCY:
      return getCurrency();

    case BANKS:
      return getBanks();

    case GAMES:
      return getGames();

    case WINNERS:
      return getWinners();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LEADERBOARD_ID:
      return isSetLeaderboardId();
    case START_DATE:
      return isSetStartDate();
    case END_DATE:
      return isSetEndDate();
    case CURRENCY:
      return isSetCurrency();
    case BANKS:
      return isSetBanks();
    case GAMES:
      return isSetGames();
    case WINNERS:
      return isSetWinners();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TLeaderboardResult)
      return this.equals((TLeaderboardResult)that);
    return false;
  }

  public boolean equals(TLeaderboardResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_leaderboardId = true;
    boolean that_present_leaderboardId = true;
    if (this_present_leaderboardId || that_present_leaderboardId) {
      if (!(this_present_leaderboardId && that_present_leaderboardId))
        return false;
      if (this.leaderboardId != that.leaderboardId)
        return false;
    }

    boolean this_present_startDate = true;
    boolean that_present_startDate = true;
    if (this_present_startDate || that_present_startDate) {
      if (!(this_present_startDate && that_present_startDate))
        return false;
      if (this.startDate != that.startDate)
        return false;
    }

    boolean this_present_endDate = true;
    boolean that_present_endDate = true;
    if (this_present_endDate || that_present_endDate) {
      if (!(this_present_endDate && that_present_endDate))
        return false;
      if (this.endDate != that.endDate)
        return false;
    }

    boolean this_present_currency = true && this.isSetCurrency();
    boolean that_present_currency = true && that.isSetCurrency();
    if (this_present_currency || that_present_currency) {
      if (!(this_present_currency && that_present_currency))
        return false;
      if (!this.currency.equals(that.currency))
        return false;
    }

    boolean this_present_banks = true && this.isSetBanks();
    boolean that_present_banks = true && that.isSetBanks();
    if (this_present_banks || that_present_banks) {
      if (!(this_present_banks && that_present_banks))
        return false;
      if (!this.banks.equals(that.banks))
        return false;
    }

    boolean this_present_games = true && this.isSetGames();
    boolean that_present_games = true && that.isSetGames();
    if (this_present_games || that_present_games) {
      if (!(this_present_games && that_present_games))
        return false;
      if (!this.games.equals(that.games))
        return false;
    }

    boolean this_present_winners = true && this.isSetWinners();
    boolean that_present_winners = true && that.isSetWinners();
    if (this_present_winners || that_present_winners) {
      if (!(this_present_winners && that_present_winners))
        return false;
      if (!this.winners.equals(that.winners))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(leaderboardId);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(startDate);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(endDate);

    hashCode = hashCode * 8191 + ((isSetCurrency()) ? 131071 : 524287);
    if (isSetCurrency())
      hashCode = hashCode * 8191 + currency.hashCode();

    hashCode = hashCode * 8191 + ((isSetBanks()) ? 131071 : 524287);
    if (isSetBanks())
      hashCode = hashCode * 8191 + banks.hashCode();

    hashCode = hashCode * 8191 + ((isSetGames()) ? 131071 : 524287);
    if (isSetGames())
      hashCode = hashCode * 8191 + games.hashCode();

    hashCode = hashCode * 8191 + ((isSetWinners()) ? 131071 : 524287);
    if (isSetWinners())
      hashCode = hashCode * 8191 + winners.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TLeaderboardResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetLeaderboardId()).compareTo(other.isSetLeaderboardId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLeaderboardId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.leaderboardId, other.leaderboardId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetStartDate()).compareTo(other.isSetStartDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.startDate, other.startDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetEndDate()).compareTo(other.isSetEndDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endDate, other.endDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCurrency()).compareTo(other.isSetCurrency());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCurrency()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.currency, other.currency);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBanks()).compareTo(other.isSetBanks());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBanks()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.banks, other.banks);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetGames()).compareTo(other.isSetGames());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGames()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.games, other.games);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetWinners()).compareTo(other.isSetWinners());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWinners()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.winners, other.winners);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TLeaderboardResult(");
    boolean first = true;

    sb.append("leaderboardId:");
    sb.append(this.leaderboardId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("startDate:");
    sb.append(this.startDate);
    first = false;
    if (!first) sb.append(", ");
    sb.append("endDate:");
    sb.append(this.endDate);
    first = false;
    if (!first) sb.append(", ");
    sb.append("currency:");
    if (this.currency == null) {
      sb.append("null");
    } else {
      sb.append(this.currency);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("banks:");
    if (this.banks == null) {
      sb.append("null");
    } else {
      sb.append(this.banks);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("games:");
    if (this.games == null) {
      sb.append("null");
    } else {
      sb.append(this.games);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("winners:");
    if (this.winners == null) {
      sb.append("null");
    } else {
      sb.append(this.winners);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TLeaderboardResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TLeaderboardResultStandardScheme getScheme() {
      return new TLeaderboardResultStandardScheme();
    }
  }

  private static class TLeaderboardResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<TLeaderboardResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TLeaderboardResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LEADERBOARD_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.leaderboardId = iprot.readI64();
              struct.setLeaderboardIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // START_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.startDate = iprot.readI64();
              struct.setStartDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // END_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.endDate = iprot.readI64();
              struct.setEndDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CURRENCY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.currency = iprot.readString();
              struct.setCurrencyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // BANKS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list52 = iprot.readListBegin();
                struct.banks = new java.util.ArrayList<java.lang.Long>(_list52.size);
                long _elem53;
                for (int _i54 = 0; _i54 < _list52.size; ++_i54)
                {
                  _elem53 = iprot.readI64();
                  struct.banks.add(_elem53);
                }
                iprot.readListEnd();
              }
              struct.setBanksIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // GAMES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list55 = iprot.readListBegin();
                struct.games = new java.util.ArrayList<java.lang.Long>(_list55.size);
                long _elem56;
                for (int _i57 = 0; _i57 < _list55.size; ++_i57)
                {
                  _elem56 = iprot.readI64();
                  struct.games.add(_elem56);
                }
                iprot.readListEnd();
              }
              struct.setGamesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // WINNERS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list58 = iprot.readListBegin();
                struct.winners = new java.util.ArrayList<TLeaderboardWin>(_list58.size);
                TLeaderboardWin _elem59;
                for (int _i60 = 0; _i60 < _list58.size; ++_i60)
                {
                  _elem59 = new TLeaderboardWin();
                  _elem59.read(iprot);
                  struct.winners.add(_elem59);
                }
                iprot.readListEnd();
              }
              struct.setWinnersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TLeaderboardResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(LEADERBOARD_ID_FIELD_DESC);
      oprot.writeI64(struct.leaderboardId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(START_DATE_FIELD_DESC);
      oprot.writeI64(struct.startDate);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(END_DATE_FIELD_DESC);
      oprot.writeI64(struct.endDate);
      oprot.writeFieldEnd();
      if (struct.currency != null) {
        oprot.writeFieldBegin(CURRENCY_FIELD_DESC);
        oprot.writeString(struct.currency);
        oprot.writeFieldEnd();
      }
      if (struct.banks != null) {
        oprot.writeFieldBegin(BANKS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.banks.size()));
          for (long _iter61 : struct.banks)
          {
            oprot.writeI64(_iter61);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.games != null) {
        oprot.writeFieldBegin(GAMES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.games.size()));
          for (long _iter62 : struct.games)
          {
            oprot.writeI64(_iter62);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.winners != null) {
        oprot.writeFieldBegin(WINNERS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.winners.size()));
          for (TLeaderboardWin _iter63 : struct.winners)
          {
            _iter63.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TLeaderboardResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TLeaderboardResultTupleScheme getScheme() {
      return new TLeaderboardResultTupleScheme();
    }
  }

  private static class TLeaderboardResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<TLeaderboardResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TLeaderboardResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetLeaderboardId()) {
        optionals.set(0);
      }
      if (struct.isSetStartDate()) {
        optionals.set(1);
      }
      if (struct.isSetEndDate()) {
        optionals.set(2);
      }
      if (struct.isSetCurrency()) {
        optionals.set(3);
      }
      if (struct.isSetBanks()) {
        optionals.set(4);
      }
      if (struct.isSetGames()) {
        optionals.set(5);
      }
      if (struct.isSetWinners()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetLeaderboardId()) {
        oprot.writeI64(struct.leaderboardId);
      }
      if (struct.isSetStartDate()) {
        oprot.writeI64(struct.startDate);
      }
      if (struct.isSetEndDate()) {
        oprot.writeI64(struct.endDate);
      }
      if (struct.isSetCurrency()) {
        oprot.writeString(struct.currency);
      }
      if (struct.isSetBanks()) {
        {
          oprot.writeI32(struct.banks.size());
          for (long _iter64 : struct.banks)
          {
            oprot.writeI64(_iter64);
          }
        }
      }
      if (struct.isSetGames()) {
        {
          oprot.writeI32(struct.games.size());
          for (long _iter65 : struct.games)
          {
            oprot.writeI64(_iter65);
          }
        }
      }
      if (struct.isSetWinners()) {
        {
          oprot.writeI32(struct.winners.size());
          for (TLeaderboardWin _iter66 : struct.winners)
          {
            _iter66.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TLeaderboardResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.leaderboardId = iprot.readI64();
        struct.setLeaderboardIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.startDate = iprot.readI64();
        struct.setStartDateIsSet(true);
      }
      if (incoming.get(2)) {
        struct.endDate = iprot.readI64();
        struct.setEndDateIsSet(true);
      }
      if (incoming.get(3)) {
        struct.currency = iprot.readString();
        struct.setCurrencyIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list67 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.banks = new java.util.ArrayList<java.lang.Long>(_list67.size);
          long _elem68;
          for (int _i69 = 0; _i69 < _list67.size; ++_i69)
          {
            _elem68 = iprot.readI64();
            struct.banks.add(_elem68);
          }
        }
        struct.setBanksIsSet(true);
      }
      if (incoming.get(5)) {
        {
          org.apache.thrift.protocol.TList _list70 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.games = new java.util.ArrayList<java.lang.Long>(_list70.size);
          long _elem71;
          for (int _i72 = 0; _i72 < _list70.size; ++_i72)
          {
            _elem71 = iprot.readI64();
            struct.games.add(_elem71);
          }
        }
        struct.setGamesIsSet(true);
      }
      if (incoming.get(6)) {
        {
          org.apache.thrift.protocol.TList _list73 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.winners = new java.util.ArrayList<TLeaderboardWin>(_list73.size);
          TLeaderboardWin _elem74;
          for (int _i75 = 0; _i75 < _list73.size; ++_i75)
          {
            _elem74 = new TLeaderboardWin();
            _elem74.read(iprot);
            struct.winners.add(_elem74);
          }
        }
        struct.setWinnersIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

