/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dgphoenix.casino.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TMQQuestData implements org.apache.thrift.TBase<TMQQuestData, TMQQuestData._Fields>, java.io.Serializable, Cloneable, Comparable<TMQQuestData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TMQQuestData");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField ROOM_COIN_FIELD_DESC = new org.apache.thrift.protocol.TField("roomCoin", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField NEED_RESET_FIELD_DESC = new org.apache.thrift.protocol.TField("needReset", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField COLLECTED_AMOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("collectedAmount", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField QUEST_PRIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("questPrize", org.apache.thrift.protocol.TType.STRUCT, (short)7);
  private static final org.apache.thrift.protocol.TField TREASURES_FIELD_DESC = new org.apache.thrift.protocol.TField("treasures", org.apache.thrift.protocol.TType.LIST, (short)8);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TMQQuestDataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TMQQuestDataTupleSchemeFactory();

  public long id; // required
  public int type; // required
  public long roomCoin; // required
  public boolean needReset; // required
  public long collectedAmount; // required
  public java.lang.String name; // required
  public TMQuestPrize questPrize; // required
  public java.util.List<TMQTreasureQuestProgress> treasures; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    TYPE((short)2, "type"),
    ROOM_COIN((short)3, "roomCoin"),
    NEED_RESET((short)4, "needReset"),
    COLLECTED_AMOUNT((short)5, "collectedAmount"),
    NAME((short)6, "name"),
    QUEST_PRIZE((short)7, "questPrize"),
    TREASURES((short)8, "treasures");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // TYPE
          return TYPE;
        case 3: // ROOM_COIN
          return ROOM_COIN;
        case 4: // NEED_RESET
          return NEED_RESET;
        case 5: // COLLECTED_AMOUNT
          return COLLECTED_AMOUNT;
        case 6: // NAME
          return NAME;
        case 7: // QUEST_PRIZE
          return QUEST_PRIZE;
        case 8: // TREASURES
          return TREASURES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __TYPE_ISSET_ID = 1;
  private static final int __ROOMCOIN_ISSET_ID = 2;
  private static final int __NEEDRESET_ISSET_ID = 3;
  private static final int __COLLECTEDAMOUNT_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.ROOM_COIN, new org.apache.thrift.meta_data.FieldMetaData("roomCoin", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.NEED_RESET, new org.apache.thrift.meta_data.FieldMetaData("needReset", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.COLLECTED_AMOUNT, new org.apache.thrift.meta_data.FieldMetaData("collectedAmount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.QUEST_PRIZE, new org.apache.thrift.meta_data.FieldMetaData("questPrize", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TMQuestPrize.class)));
    tmpMap.put(_Fields.TREASURES, new org.apache.thrift.meta_data.FieldMetaData("treasures", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TMQTreasureQuestProgress.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TMQQuestData.class, metaDataMap);
  }

  public TMQQuestData() {
  }

  public TMQQuestData(
    long id,
    int type,
    long roomCoin,
    boolean needReset,
    long collectedAmount,
    java.lang.String name,
    TMQuestPrize questPrize,
    java.util.List<TMQTreasureQuestProgress> treasures)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.type = type;
    setTypeIsSet(true);
    this.roomCoin = roomCoin;
    setRoomCoinIsSet(true);
    this.needReset = needReset;
    setNeedResetIsSet(true);
    this.collectedAmount = collectedAmount;
    setCollectedAmountIsSet(true);
    this.name = name;
    this.questPrize = questPrize;
    this.treasures = treasures;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TMQQuestData(TMQQuestData other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    this.type = other.type;
    this.roomCoin = other.roomCoin;
    this.needReset = other.needReset;
    this.collectedAmount = other.collectedAmount;
    if (other.isSetName()) {
      this.name = other.name;
    }
    if (other.isSetQuestPrize()) {
      this.questPrize = new TMQuestPrize(other.questPrize);
    }
    if (other.isSetTreasures()) {
      java.util.List<TMQTreasureQuestProgress> __this__treasures = new java.util.ArrayList<TMQTreasureQuestProgress>(other.treasures.size());
      for (TMQTreasureQuestProgress other_element : other.treasures) {
        __this__treasures.add(new TMQTreasureQuestProgress(other_element));
      }
      this.treasures = __this__treasures;
    }
  }

  public TMQQuestData deepCopy() {
    return new TMQQuestData(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    setTypeIsSet(false);
    this.type = 0;
    setRoomCoinIsSet(false);
    this.roomCoin = 0;
    setNeedResetIsSet(false);
    this.needReset = false;
    setCollectedAmountIsSet(false);
    this.collectedAmount = 0;
    this.name = null;
    this.questPrize = null;
    this.treasures = null;
  }

  public long getId() {
    return this.id;
  }

  public TMQQuestData setId(long id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public int getType() {
    return this.type;
  }

  public TMQQuestData setType(int type) {
    this.type = type;
    setTypeIsSet(true);
    return this;
  }

  public void unsetType() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TYPE_ISSET_ID);
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TYPE_ISSET_ID);
  }

  public void setTypeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TYPE_ISSET_ID, value);
  }

  public long getRoomCoin() {
    return this.roomCoin;
  }

  public TMQQuestData setRoomCoin(long roomCoin) {
    this.roomCoin = roomCoin;
    setRoomCoinIsSet(true);
    return this;
  }

  public void unsetRoomCoin() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ROOMCOIN_ISSET_ID);
  }

  /** Returns true if field roomCoin is set (has been assigned a value) and false otherwise */
  public boolean isSetRoomCoin() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ROOMCOIN_ISSET_ID);
  }

  public void setRoomCoinIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ROOMCOIN_ISSET_ID, value);
  }

  public boolean isNeedReset() {
    return this.needReset;
  }

  public TMQQuestData setNeedReset(boolean needReset) {
    this.needReset = needReset;
    setNeedResetIsSet(true);
    return this;
  }

  public void unsetNeedReset() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NEEDRESET_ISSET_ID);
  }

  /** Returns true if field needReset is set (has been assigned a value) and false otherwise */
  public boolean isSetNeedReset() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NEEDRESET_ISSET_ID);
  }

  public void setNeedResetIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NEEDRESET_ISSET_ID, value);
  }

  public long getCollectedAmount() {
    return this.collectedAmount;
  }

  public TMQQuestData setCollectedAmount(long collectedAmount) {
    this.collectedAmount = collectedAmount;
    setCollectedAmountIsSet(true);
    return this;
  }

  public void unsetCollectedAmount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __COLLECTEDAMOUNT_ISSET_ID);
  }

  /** Returns true if field collectedAmount is set (has been assigned a value) and false otherwise */
  public boolean isSetCollectedAmount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __COLLECTEDAMOUNT_ISSET_ID);
  }

  public void setCollectedAmountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __COLLECTEDAMOUNT_ISSET_ID, value);
  }

  public java.lang.String getName() {
    return this.name;
  }

  public TMQQuestData setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public TMQuestPrize getQuestPrize() {
    return this.questPrize;
  }

  public TMQQuestData setQuestPrize(TMQuestPrize questPrize) {
    this.questPrize = questPrize;
    return this;
  }

  public void unsetQuestPrize() {
    this.questPrize = null;
  }

  /** Returns true if field questPrize is set (has been assigned a value) and false otherwise */
  public boolean isSetQuestPrize() {
    return this.questPrize != null;
  }

  public void setQuestPrizeIsSet(boolean value) {
    if (!value) {
      this.questPrize = null;
    }
  }

  public int getTreasuresSize() {
    return (this.treasures == null) ? 0 : this.treasures.size();
  }

  public java.util.Iterator<TMQTreasureQuestProgress> getTreasuresIterator() {
    return (this.treasures == null) ? null : this.treasures.iterator();
  }

  public void addToTreasures(TMQTreasureQuestProgress elem) {
    if (this.treasures == null) {
      this.treasures = new java.util.ArrayList<TMQTreasureQuestProgress>();
    }
    this.treasures.add(elem);
  }

  public java.util.List<TMQTreasureQuestProgress> getTreasures() {
    return this.treasures;
  }

  public TMQQuestData setTreasures(java.util.List<TMQTreasureQuestProgress> treasures) {
    this.treasures = treasures;
    return this;
  }

  public void unsetTreasures() {
    this.treasures = null;
  }

  /** Returns true if field treasures is set (has been assigned a value) and false otherwise */
  public boolean isSetTreasures() {
    return this.treasures != null;
  }

  public void setTreasuresIsSet(boolean value) {
    if (!value) {
      this.treasures = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Long)value);
      }
      break;

    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((java.lang.Integer)value);
      }
      break;

    case ROOM_COIN:
      if (value == null) {
        unsetRoomCoin();
      } else {
        setRoomCoin((java.lang.Long)value);
      }
      break;

    case NEED_RESET:
      if (value == null) {
        unsetNeedReset();
      } else {
        setNeedReset((java.lang.Boolean)value);
      }
      break;

    case COLLECTED_AMOUNT:
      if (value == null) {
        unsetCollectedAmount();
      } else {
        setCollectedAmount((java.lang.Long)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((java.lang.String)value);
      }
      break;

    case QUEST_PRIZE:
      if (value == null) {
        unsetQuestPrize();
      } else {
        setQuestPrize((TMQuestPrize)value);
      }
      break;

    case TREASURES:
      if (value == null) {
        unsetTreasures();
      } else {
        setTreasures((java.util.List<TMQTreasureQuestProgress>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case TYPE:
      return getType();

    case ROOM_COIN:
      return getRoomCoin();

    case NEED_RESET:
      return isNeedReset();

    case COLLECTED_AMOUNT:
      return getCollectedAmount();

    case NAME:
      return getName();

    case QUEST_PRIZE:
      return getQuestPrize();

    case TREASURES:
      return getTreasures();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case TYPE:
      return isSetType();
    case ROOM_COIN:
      return isSetRoomCoin();
    case NEED_RESET:
      return isSetNeedReset();
    case COLLECTED_AMOUNT:
      return isSetCollectedAmount();
    case NAME:
      return isSetName();
    case QUEST_PRIZE:
      return isSetQuestPrize();
    case TREASURES:
      return isSetTreasures();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TMQQuestData)
      return this.equals((TMQQuestData)that);
    return false;
  }

  public boolean equals(TMQQuestData that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_type = true;
    boolean that_present_type = true;
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (this.type != that.type)
        return false;
    }

    boolean this_present_roomCoin = true;
    boolean that_present_roomCoin = true;
    if (this_present_roomCoin || that_present_roomCoin) {
      if (!(this_present_roomCoin && that_present_roomCoin))
        return false;
      if (this.roomCoin != that.roomCoin)
        return false;
    }

    boolean this_present_needReset = true;
    boolean that_present_needReset = true;
    if (this_present_needReset || that_present_needReset) {
      if (!(this_present_needReset && that_present_needReset))
        return false;
      if (this.needReset != that.needReset)
        return false;
    }

    boolean this_present_collectedAmount = true;
    boolean that_present_collectedAmount = true;
    if (this_present_collectedAmount || that_present_collectedAmount) {
      if (!(this_present_collectedAmount && that_present_collectedAmount))
        return false;
      if (this.collectedAmount != that.collectedAmount)
        return false;
    }

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_questPrize = true && this.isSetQuestPrize();
    boolean that_present_questPrize = true && that.isSetQuestPrize();
    if (this_present_questPrize || that_present_questPrize) {
      if (!(this_present_questPrize && that_present_questPrize))
        return false;
      if (!this.questPrize.equals(that.questPrize))
        return false;
    }

    boolean this_present_treasures = true && this.isSetTreasures();
    boolean that_present_treasures = true && that.isSetTreasures();
    if (this_present_treasures || that_present_treasures) {
      if (!(this_present_treasures && that_present_treasures))
        return false;
      if (!this.treasures.equals(that.treasures))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(id);

    hashCode = hashCode * 8191 + type;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(roomCoin);

    hashCode = hashCode * 8191 + ((needReset) ? 131071 : 524287);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(collectedAmount);

    hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
    if (isSetName())
      hashCode = hashCode * 8191 + name.hashCode();

    hashCode = hashCode * 8191 + ((isSetQuestPrize()) ? 131071 : 524287);
    if (isSetQuestPrize())
      hashCode = hashCode * 8191 + questPrize.hashCode();

    hashCode = hashCode * 8191 + ((isSetTreasures()) ? 131071 : 524287);
    if (isSetTreasures())
      hashCode = hashCode * 8191 + treasures.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TMQQuestData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetType()).compareTo(other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, other.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRoomCoin()).compareTo(other.isSetRoomCoin());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoomCoin()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roomCoin, other.roomCoin);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNeedReset()).compareTo(other.isSetNeedReset());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNeedReset()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.needReset, other.needReset);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCollectedAmount()).compareTo(other.isSetCollectedAmount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCollectedAmount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.collectedAmount, other.collectedAmount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetQuestPrize()).compareTo(other.isSetQuestPrize());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQuestPrize()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.questPrize, other.questPrize);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTreasures()).compareTo(other.isSetTreasures());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTreasures()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.treasures, other.treasures);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TMQQuestData(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("type:");
    sb.append(this.type);
    first = false;
    if (!first) sb.append(", ");
    sb.append("roomCoin:");
    sb.append(this.roomCoin);
    first = false;
    if (!first) sb.append(", ");
    sb.append("needReset:");
    sb.append(this.needReset);
    first = false;
    if (!first) sb.append(", ");
    sb.append("collectedAmount:");
    sb.append(this.collectedAmount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("questPrize:");
    if (this.questPrize == null) {
      sb.append("null");
    } else {
      sb.append(this.questPrize);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("treasures:");
    if (this.treasures == null) {
      sb.append("null");
    } else {
      sb.append(this.treasures);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (questPrize != null) {
      questPrize.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TMQQuestDataStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TMQQuestDataStandardScheme getScheme() {
      return new TMQQuestDataStandardScheme();
    }
  }

  private static class TMQQuestDataStandardScheme extends org.apache.thrift.scheme.StandardScheme<TMQQuestData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TMQQuestData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = iprot.readI32();
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ROOM_COIN
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.roomCoin = iprot.readI64();
              struct.setRoomCoinIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // NEED_RESET
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.needReset = iprot.readBool();
              struct.setNeedResetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // COLLECTED_AMOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.collectedAmount = iprot.readI64();
              struct.setCollectedAmountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // QUEST_PRIZE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.questPrize = new TMQuestPrize();
              struct.questPrize.read(iprot);
              struct.setQuestPrizeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // TREASURES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list76 = iprot.readListBegin();
                struct.treasures = new java.util.ArrayList<TMQTreasureQuestProgress>(_list76.size);
                TMQTreasureQuestProgress _elem77;
                for (int _i78 = 0; _i78 < _list76.size; ++_i78)
                {
                  _elem77 = new TMQTreasureQuestProgress();
                  _elem77.read(iprot);
                  struct.treasures.add(_elem77);
                }
                iprot.readListEnd();
              }
              struct.setTreasuresIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TMQQuestData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI64(struct.id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TYPE_FIELD_DESC);
      oprot.writeI32(struct.type);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ROOM_COIN_FIELD_DESC);
      oprot.writeI64(struct.roomCoin);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NEED_RESET_FIELD_DESC);
      oprot.writeBool(struct.needReset);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(COLLECTED_AMOUNT_FIELD_DESC);
      oprot.writeI64(struct.collectedAmount);
      oprot.writeFieldEnd();
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      if (struct.questPrize != null) {
        oprot.writeFieldBegin(QUEST_PRIZE_FIELD_DESC);
        struct.questPrize.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.treasures != null) {
        oprot.writeFieldBegin(TREASURES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.treasures.size()));
          for (TMQTreasureQuestProgress _iter79 : struct.treasures)
          {
            _iter79.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TMQQuestDataTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TMQQuestDataTupleScheme getScheme() {
      return new TMQQuestDataTupleScheme();
    }
  }

  private static class TMQQuestDataTupleScheme extends org.apache.thrift.scheme.TupleScheme<TMQQuestData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TMQQuestData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetType()) {
        optionals.set(1);
      }
      if (struct.isSetRoomCoin()) {
        optionals.set(2);
      }
      if (struct.isSetNeedReset()) {
        optionals.set(3);
      }
      if (struct.isSetCollectedAmount()) {
        optionals.set(4);
      }
      if (struct.isSetName()) {
        optionals.set(5);
      }
      if (struct.isSetQuestPrize()) {
        optionals.set(6);
      }
      if (struct.isSetTreasures()) {
        optionals.set(7);
      }
      oprot.writeBitSet(optionals, 8);
      if (struct.isSetId()) {
        oprot.writeI64(struct.id);
      }
      if (struct.isSetType()) {
        oprot.writeI32(struct.type);
      }
      if (struct.isSetRoomCoin()) {
        oprot.writeI64(struct.roomCoin);
      }
      if (struct.isSetNeedReset()) {
        oprot.writeBool(struct.needReset);
      }
      if (struct.isSetCollectedAmount()) {
        oprot.writeI64(struct.collectedAmount);
      }
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetQuestPrize()) {
        struct.questPrize.write(oprot);
      }
      if (struct.isSetTreasures()) {
        {
          oprot.writeI32(struct.treasures.size());
          for (TMQTreasureQuestProgress _iter80 : struct.treasures)
          {
            _iter80.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TMQQuestData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(8);
      if (incoming.get(0)) {
        struct.id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.type = iprot.readI32();
        struct.setTypeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.roomCoin = iprot.readI64();
        struct.setRoomCoinIsSet(true);
      }
      if (incoming.get(3)) {
        struct.needReset = iprot.readBool();
        struct.setNeedResetIsSet(true);
      }
      if (incoming.get(4)) {
        struct.collectedAmount = iprot.readI64();
        struct.setCollectedAmountIsSet(true);
      }
      if (incoming.get(5)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(6)) {
        struct.questPrize = new TMQuestPrize();
        struct.questPrize.read(iprot);
        struct.setQuestPrizeIsSet(true);
      }
      if (incoming.get(7)) {
        {
          org.apache.thrift.protocol.TList _list81 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.treasures = new java.util.ArrayList<TMQTreasureQuestProgress>(_list81.size);
          TMQTreasureQuestProgress _elem82;
          for (int _i83 = 0; _i83 < _list81.size; ++_i83)
          {
            _elem82 = new TMQTreasureQuestProgress();
            _elem82.read(iprot);
            struct.treasures.add(_elem82);
          }
        }
        struct.setTreasuresIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

