/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dgphoenix.casino.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TRoundInfoResult implements org.apache.thrift.TBase<TRoundInfoResult, TRoundInfoResult._Fields>, java.io.Serializable, Cloneable, Comparable<TRoundInfoResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TRoundInfoResult");

  private static final org.apache.thrift.protocol.TField ACCOUNT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("accountId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("time", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField BET_FIELD_DESC = new org.apache.thrift.protocol.TField("bet", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField PAYOUT_FIELD_DESC = new org.apache.thrift.protocol.TField("payout", org.apache.thrift.protocol.TType.DOUBLE, (short)4);
  private static final org.apache.thrift.protocol.TField ARCHIVE_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("archiveData", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField BATTLEGROUND_ROUND_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("battlegroundRoundInfo", org.apache.thrift.protocol.TType.STRUCT, (short)6);
  private static final org.apache.thrift.protocol.TField ROUND_START_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("roundStartTime", org.apache.thrift.protocol.TType.I64, (short)7);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TRoundInfoResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TRoundInfoResultTupleSchemeFactory();

  public long accountId; // required
  public long time; // required
  public double bet; // required
  public double payout; // required
  public java.lang.String archiveData; // required
  public TBattlegroundRoundInfo battlegroundRoundInfo; // required
  public long roundStartTime; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ACCOUNT_ID((short)1, "accountId"),
    TIME((short)2, "time"),
    BET((short)3, "bet"),
    PAYOUT((short)4, "payout"),
    ARCHIVE_DATA((short)5, "archiveData"),
    BATTLEGROUND_ROUND_INFO((short)6, "battlegroundRoundInfo"),
    ROUND_START_TIME((short)7, "roundStartTime");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ACCOUNT_ID
          return ACCOUNT_ID;
        case 2: // TIME
          return TIME;
        case 3: // BET
          return BET;
        case 4: // PAYOUT
          return PAYOUT;
        case 5: // ARCHIVE_DATA
          return ARCHIVE_DATA;
        case 6: // BATTLEGROUND_ROUND_INFO
          return BATTLEGROUND_ROUND_INFO;
        case 7: // ROUND_START_TIME
          return ROUND_START_TIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ACCOUNTID_ISSET_ID = 0;
  private static final int __TIME_ISSET_ID = 1;
  private static final int __BET_ISSET_ID = 2;
  private static final int __PAYOUT_ISSET_ID = 3;
  private static final int __ROUNDSTARTTIME_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ACCOUNT_ID, new org.apache.thrift.meta_data.FieldMetaData("accountId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.TIME, new org.apache.thrift.meta_data.FieldMetaData("time", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.BET, new org.apache.thrift.meta_data.FieldMetaData("bet", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.PAYOUT, new org.apache.thrift.meta_data.FieldMetaData("payout", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.ARCHIVE_DATA, new org.apache.thrift.meta_data.FieldMetaData("archiveData", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BATTLEGROUND_ROUND_INFO, new org.apache.thrift.meta_data.FieldMetaData("battlegroundRoundInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "TBattlegroundRoundInfo")));
    tmpMap.put(_Fields.ROUND_START_TIME, new org.apache.thrift.meta_data.FieldMetaData("roundStartTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TRoundInfoResult.class, metaDataMap);
  }

  public TRoundInfoResult() {
  }

  public TRoundInfoResult(
    long accountId,
    long time,
    double bet,
    double payout,
    java.lang.String archiveData,
    TBattlegroundRoundInfo battlegroundRoundInfo,
    long roundStartTime)
  {
    this();
    this.accountId = accountId;
    setAccountIdIsSet(true);
    this.time = time;
    setTimeIsSet(true);
    this.bet = bet;
    setBetIsSet(true);
    this.payout = payout;
    setPayoutIsSet(true);
    this.archiveData = archiveData;
    this.battlegroundRoundInfo = battlegroundRoundInfo;
    this.roundStartTime = roundStartTime;
    setRoundStartTimeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TRoundInfoResult(TRoundInfoResult other) {
    __isset_bitfield = other.__isset_bitfield;
    this.accountId = other.accountId;
    this.time = other.time;
    this.bet = other.bet;
    this.payout = other.payout;
    if (other.isSetArchiveData()) {
      this.archiveData = other.archiveData;
    }
    if (other.isSetBattlegroundRoundInfo()) {
      this.battlegroundRoundInfo = new TBattlegroundRoundInfo(other.battlegroundRoundInfo);
    }
    this.roundStartTime = other.roundStartTime;
  }

  public TRoundInfoResult deepCopy() {
    return new TRoundInfoResult(this);
  }

  @Override
  public void clear() {
    setAccountIdIsSet(false);
    this.accountId = 0;
    setTimeIsSet(false);
    this.time = 0;
    setBetIsSet(false);
    this.bet = 0.0;
    setPayoutIsSet(false);
    this.payout = 0.0;
    this.archiveData = null;
    this.battlegroundRoundInfo = null;
    setRoundStartTimeIsSet(false);
    this.roundStartTime = 0;
  }

  public long getAccountId() {
    return this.accountId;
  }

  public TRoundInfoResult setAccountId(long accountId) {
    this.accountId = accountId;
    setAccountIdIsSet(true);
    return this;
  }

  public void unsetAccountId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ACCOUNTID_ISSET_ID);
  }

  /** Returns true if field accountId is set (has been assigned a value) and false otherwise */
  public boolean isSetAccountId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ACCOUNTID_ISSET_ID);
  }

  public void setAccountIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ACCOUNTID_ISSET_ID, value);
  }

  public long getTime() {
    return this.time;
  }

  public TRoundInfoResult setTime(long time) {
    this.time = time;
    setTimeIsSet(true);
    return this;
  }

  public void unsetTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TIME_ISSET_ID);
  }

  /** Returns true if field time is set (has been assigned a value) and false otherwise */
  public boolean isSetTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TIME_ISSET_ID);
  }

  public void setTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TIME_ISSET_ID, value);
  }

  public double getBet() {
    return this.bet;
  }

  public TRoundInfoResult setBet(double bet) {
    this.bet = bet;
    setBetIsSet(true);
    return this;
  }

  public void unsetBet() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BET_ISSET_ID);
  }

  /** Returns true if field bet is set (has been assigned a value) and false otherwise */
  public boolean isSetBet() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BET_ISSET_ID);
  }

  public void setBetIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BET_ISSET_ID, value);
  }

  public double getPayout() {
    return this.payout;
  }

  public TRoundInfoResult setPayout(double payout) {
    this.payout = payout;
    setPayoutIsSet(true);
    return this;
  }

  public void unsetPayout() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PAYOUT_ISSET_ID);
  }

  /** Returns true if field payout is set (has been assigned a value) and false otherwise */
  public boolean isSetPayout() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PAYOUT_ISSET_ID);
  }

  public void setPayoutIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PAYOUT_ISSET_ID, value);
  }

  public java.lang.String getArchiveData() {
    return this.archiveData;
  }

  public TRoundInfoResult setArchiveData(java.lang.String archiveData) {
    this.archiveData = archiveData;
    return this;
  }

  public void unsetArchiveData() {
    this.archiveData = null;
  }

  /** Returns true if field archiveData is set (has been assigned a value) and false otherwise */
  public boolean isSetArchiveData() {
    return this.archiveData != null;
  }

  public void setArchiveDataIsSet(boolean value) {
    if (!value) {
      this.archiveData = null;
    }
  }

  public TBattlegroundRoundInfo getBattlegroundRoundInfo() {
    return this.battlegroundRoundInfo;
  }

  public TRoundInfoResult setBattlegroundRoundInfo(TBattlegroundRoundInfo battlegroundRoundInfo) {
    this.battlegroundRoundInfo = battlegroundRoundInfo;
    return this;
  }

  public void unsetBattlegroundRoundInfo() {
    this.battlegroundRoundInfo = null;
  }

  /** Returns true if field battlegroundRoundInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetBattlegroundRoundInfo() {
    return this.battlegroundRoundInfo != null;
  }

  public void setBattlegroundRoundInfoIsSet(boolean value) {
    if (!value) {
      this.battlegroundRoundInfo = null;
    }
  }

  public long getRoundStartTime() {
    return this.roundStartTime;
  }

  public TRoundInfoResult setRoundStartTime(long roundStartTime) {
    this.roundStartTime = roundStartTime;
    setRoundStartTimeIsSet(true);
    return this;
  }

  public void unsetRoundStartTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ROUNDSTARTTIME_ISSET_ID);
  }

  /** Returns true if field roundStartTime is set (has been assigned a value) and false otherwise */
  public boolean isSetRoundStartTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ROUNDSTARTTIME_ISSET_ID);
  }

  public void setRoundStartTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ROUNDSTARTTIME_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ACCOUNT_ID:
      if (value == null) {
        unsetAccountId();
      } else {
        setAccountId((java.lang.Long)value);
      }
      break;

    case TIME:
      if (value == null) {
        unsetTime();
      } else {
        setTime((java.lang.Long)value);
      }
      break;

    case BET:
      if (value == null) {
        unsetBet();
      } else {
        setBet((java.lang.Double)value);
      }
      break;

    case PAYOUT:
      if (value == null) {
        unsetPayout();
      } else {
        setPayout((java.lang.Double)value);
      }
      break;

    case ARCHIVE_DATA:
      if (value == null) {
        unsetArchiveData();
      } else {
        setArchiveData((java.lang.String)value);
      }
      break;

    case BATTLEGROUND_ROUND_INFO:
      if (value == null) {
        unsetBattlegroundRoundInfo();
      } else {
        setBattlegroundRoundInfo((TBattlegroundRoundInfo)value);
      }
      break;

    case ROUND_START_TIME:
      if (value == null) {
        unsetRoundStartTime();
      } else {
        setRoundStartTime((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ACCOUNT_ID:
      return getAccountId();

    case TIME:
      return getTime();

    case BET:
      return getBet();

    case PAYOUT:
      return getPayout();

    case ARCHIVE_DATA:
      return getArchiveData();

    case BATTLEGROUND_ROUND_INFO:
      return getBattlegroundRoundInfo();

    case ROUND_START_TIME:
      return getRoundStartTime();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ACCOUNT_ID:
      return isSetAccountId();
    case TIME:
      return isSetTime();
    case BET:
      return isSetBet();
    case PAYOUT:
      return isSetPayout();
    case ARCHIVE_DATA:
      return isSetArchiveData();
    case BATTLEGROUND_ROUND_INFO:
      return isSetBattlegroundRoundInfo();
    case ROUND_START_TIME:
      return isSetRoundStartTime();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TRoundInfoResult)
      return this.equals((TRoundInfoResult)that);
    return false;
  }

  public boolean equals(TRoundInfoResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_accountId = true;
    boolean that_present_accountId = true;
    if (this_present_accountId || that_present_accountId) {
      if (!(this_present_accountId && that_present_accountId))
        return false;
      if (this.accountId != that.accountId)
        return false;
    }

    boolean this_present_time = true;
    boolean that_present_time = true;
    if (this_present_time || that_present_time) {
      if (!(this_present_time && that_present_time))
        return false;
      if (this.time != that.time)
        return false;
    }

    boolean this_present_bet = true;
    boolean that_present_bet = true;
    if (this_present_bet || that_present_bet) {
      if (!(this_present_bet && that_present_bet))
        return false;
      if (this.bet != that.bet)
        return false;
    }

    boolean this_present_payout = true;
    boolean that_present_payout = true;
    if (this_present_payout || that_present_payout) {
      if (!(this_present_payout && that_present_payout))
        return false;
      if (this.payout != that.payout)
        return false;
    }

    boolean this_present_archiveData = true && this.isSetArchiveData();
    boolean that_present_archiveData = true && that.isSetArchiveData();
    if (this_present_archiveData || that_present_archiveData) {
      if (!(this_present_archiveData && that_present_archiveData))
        return false;
      if (!this.archiveData.equals(that.archiveData))
        return false;
    }

    boolean this_present_battlegroundRoundInfo = true && this.isSetBattlegroundRoundInfo();
    boolean that_present_battlegroundRoundInfo = true && that.isSetBattlegroundRoundInfo();
    if (this_present_battlegroundRoundInfo || that_present_battlegroundRoundInfo) {
      if (!(this_present_battlegroundRoundInfo && that_present_battlegroundRoundInfo))
        return false;
      if (!this.battlegroundRoundInfo.equals(that.battlegroundRoundInfo))
        return false;
    }

    boolean this_present_roundStartTime = true;
    boolean that_present_roundStartTime = true;
    if (this_present_roundStartTime || that_present_roundStartTime) {
      if (!(this_present_roundStartTime && that_present_roundStartTime))
        return false;
      if (this.roundStartTime != that.roundStartTime)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(accountId);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(time);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(bet);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(payout);

    hashCode = hashCode * 8191 + ((isSetArchiveData()) ? 131071 : 524287);
    if (isSetArchiveData())
      hashCode = hashCode * 8191 + archiveData.hashCode();

    hashCode = hashCode * 8191 + ((isSetBattlegroundRoundInfo()) ? 131071 : 524287);
    if (isSetBattlegroundRoundInfo())
      hashCode = hashCode * 8191 + battlegroundRoundInfo.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(roundStartTime);

    return hashCode;
  }

  @Override
  public int compareTo(TRoundInfoResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetAccountId()).compareTo(other.isSetAccountId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccountId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accountId, other.accountId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTime()).compareTo(other.isSetTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.time, other.time);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBet()).compareTo(other.isSetBet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bet, other.bet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPayout()).compareTo(other.isSetPayout());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPayout()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.payout, other.payout);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetArchiveData()).compareTo(other.isSetArchiveData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetArchiveData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.archiveData, other.archiveData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBattlegroundRoundInfo()).compareTo(other.isSetBattlegroundRoundInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBattlegroundRoundInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.battlegroundRoundInfo, other.battlegroundRoundInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRoundStartTime()).compareTo(other.isSetRoundStartTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoundStartTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roundStartTime, other.roundStartTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TRoundInfoResult(");
    boolean first = true;

    sb.append("accountId:");
    sb.append(this.accountId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("time:");
    sb.append(this.time);
    first = false;
    if (!first) sb.append(", ");
    sb.append("bet:");
    sb.append(this.bet);
    first = false;
    if (!first) sb.append(", ");
    sb.append("payout:");
    sb.append(this.payout);
    first = false;
    if (!first) sb.append(", ");
    sb.append("archiveData:");
    if (this.archiveData == null) {
      sb.append("null");
    } else {
      sb.append(this.archiveData);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("battlegroundRoundInfo:");
    if (this.battlegroundRoundInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.battlegroundRoundInfo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("roundStartTime:");
    sb.append(this.roundStartTime);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TRoundInfoResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TRoundInfoResultStandardScheme getScheme() {
      return new TRoundInfoResultStandardScheme();
    }
  }

  private static class TRoundInfoResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<TRoundInfoResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TRoundInfoResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ACCOUNT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.accountId = iprot.readI64();
              struct.setAccountIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.time = iprot.readI64();
              struct.setTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // BET
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.bet = iprot.readDouble();
              struct.setBetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PAYOUT
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.payout = iprot.readDouble();
              struct.setPayoutIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ARCHIVE_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.archiveData = iprot.readString();
              struct.setArchiveDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // BATTLEGROUND_ROUND_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.battlegroundRoundInfo = new TBattlegroundRoundInfo();
              struct.battlegroundRoundInfo.read(iprot);
              struct.setBattlegroundRoundInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // ROUND_START_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.roundStartTime = iprot.readI64();
              struct.setRoundStartTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TRoundInfoResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ACCOUNT_ID_FIELD_DESC);
      oprot.writeI64(struct.accountId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TIME_FIELD_DESC);
      oprot.writeI64(struct.time);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BET_FIELD_DESC);
      oprot.writeDouble(struct.bet);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PAYOUT_FIELD_DESC);
      oprot.writeDouble(struct.payout);
      oprot.writeFieldEnd();
      if (struct.archiveData != null) {
        oprot.writeFieldBegin(ARCHIVE_DATA_FIELD_DESC);
        oprot.writeString(struct.archiveData);
        oprot.writeFieldEnd();
      }
      if (struct.battlegroundRoundInfo != null) {
        oprot.writeFieldBegin(BATTLEGROUND_ROUND_INFO_FIELD_DESC);
        struct.battlegroundRoundInfo.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ROUND_START_TIME_FIELD_DESC);
      oprot.writeI64(struct.roundStartTime);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TRoundInfoResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TRoundInfoResultTupleScheme getScheme() {
      return new TRoundInfoResultTupleScheme();
    }
  }

  private static class TRoundInfoResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<TRoundInfoResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TRoundInfoResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetAccountId()) {
        optionals.set(0);
      }
      if (struct.isSetTime()) {
        optionals.set(1);
      }
      if (struct.isSetBet()) {
        optionals.set(2);
      }
      if (struct.isSetPayout()) {
        optionals.set(3);
      }
      if (struct.isSetArchiveData()) {
        optionals.set(4);
      }
      if (struct.isSetBattlegroundRoundInfo()) {
        optionals.set(5);
      }
      if (struct.isSetRoundStartTime()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetAccountId()) {
        oprot.writeI64(struct.accountId);
      }
      if (struct.isSetTime()) {
        oprot.writeI64(struct.time);
      }
      if (struct.isSetBet()) {
        oprot.writeDouble(struct.bet);
      }
      if (struct.isSetPayout()) {
        oprot.writeDouble(struct.payout);
      }
      if (struct.isSetArchiveData()) {
        oprot.writeString(struct.archiveData);
      }
      if (struct.isSetBattlegroundRoundInfo()) {
        struct.battlegroundRoundInfo.write(oprot);
      }
      if (struct.isSetRoundStartTime()) {
        oprot.writeI64(struct.roundStartTime);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TRoundInfoResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.accountId = iprot.readI64();
        struct.setAccountIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.time = iprot.readI64();
        struct.setTimeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.bet = iprot.readDouble();
        struct.setBetIsSet(true);
      }
      if (incoming.get(3)) {
        struct.payout = iprot.readDouble();
        struct.setPayoutIsSet(true);
      }
      if (incoming.get(4)) {
        struct.archiveData = iprot.readString();
        struct.setArchiveDataIsSet(true);
      }
      if (incoming.get(5)) {
        struct.battlegroundRoundInfo = new TBattlegroundRoundInfo();
        struct.battlegroundRoundInfo.read(iprot);
        struct.setBattlegroundRoundInfoIsSet(true);
      }
      if (incoming.get(6)) {
        struct.roundStartTime = iprot.readI64();
        struct.setRoundStartTimeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

