/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dgphoenix.casino.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TSitInResult implements org.apache.thrift.TBase<TSitInResult, TSitInResult._Fields>, java.io.Serializable, Cloneable, Comparable<TSitInResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TSitInResult");

  private static final org.apache.thrift.protocol.TField GAME_SESSION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("gameSessionId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField AMOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("amount", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField BALANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("balance", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField PLAYER_ROUND_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("playerRoundId", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.BOOL, (short)5);
  private static final org.apache.thrift.protocol.TField ERROR_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("errorCode", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField ERROR_DETAILS_FIELD_DESC = new org.apache.thrift.protocol.TField("errorDetails", org.apache.thrift.protocol.TType.STRING, (short)7);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TSitInResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TSitInResultTupleSchemeFactory();

  public long gameSessionId; // required
  public long amount; // required
  public long balance; // required
  public long playerRoundId; // required
  public boolean success; // required
  public int errorCode; // required
  public java.lang.String errorDetails; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GAME_SESSION_ID((short)1, "gameSessionId"),
    AMOUNT((short)2, "amount"),
    BALANCE((short)3, "balance"),
    PLAYER_ROUND_ID((short)4, "playerRoundId"),
    SUCCESS((short)5, "success"),
    ERROR_CODE((short)6, "errorCode"),
    ERROR_DETAILS((short)7, "errorDetails");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GAME_SESSION_ID
          return GAME_SESSION_ID;
        case 2: // AMOUNT
          return AMOUNT;
        case 3: // BALANCE
          return BALANCE;
        case 4: // PLAYER_ROUND_ID
          return PLAYER_ROUND_ID;
        case 5: // SUCCESS
          return SUCCESS;
        case 6: // ERROR_CODE
          return ERROR_CODE;
        case 7: // ERROR_DETAILS
          return ERROR_DETAILS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __GAMESESSIONID_ISSET_ID = 0;
  private static final int __AMOUNT_ISSET_ID = 1;
  private static final int __BALANCE_ISSET_ID = 2;
  private static final int __PLAYERROUNDID_ISSET_ID = 3;
  private static final int __SUCCESS_ISSET_ID = 4;
  private static final int __ERRORCODE_ISSET_ID = 5;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GAME_SESSION_ID, new org.apache.thrift.meta_data.FieldMetaData("gameSessionId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.AMOUNT, new org.apache.thrift.meta_data.FieldMetaData("amount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.BALANCE, new org.apache.thrift.meta_data.FieldMetaData("balance", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.PLAYER_ROUND_ID, new org.apache.thrift.meta_data.FieldMetaData("playerRoundId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ERROR_CODE, new org.apache.thrift.meta_data.FieldMetaData("errorCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.ERROR_DETAILS, new org.apache.thrift.meta_data.FieldMetaData("errorDetails", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TSitInResult.class, metaDataMap);
  }

  public TSitInResult() {
  }

  public TSitInResult(
    long gameSessionId,
    long amount,
    long balance,
    long playerRoundId,
    boolean success,
    int errorCode,
    java.lang.String errorDetails)
  {
    this();
    this.gameSessionId = gameSessionId;
    setGameSessionIdIsSet(true);
    this.amount = amount;
    setAmountIsSet(true);
    this.balance = balance;
    setBalanceIsSet(true);
    this.playerRoundId = playerRoundId;
    setPlayerRoundIdIsSet(true);
    this.success = success;
    setSuccessIsSet(true);
    this.errorCode = errorCode;
    setErrorCodeIsSet(true);
    this.errorDetails = errorDetails;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TSitInResult(TSitInResult other) {
    __isset_bitfield = other.__isset_bitfield;
    this.gameSessionId = other.gameSessionId;
    this.amount = other.amount;
    this.balance = other.balance;
    this.playerRoundId = other.playerRoundId;
    this.success = other.success;
    this.errorCode = other.errorCode;
    if (other.isSetErrorDetails()) {
      this.errorDetails = other.errorDetails;
    }
  }

  public TSitInResult deepCopy() {
    return new TSitInResult(this);
  }

  @Override
  public void clear() {
    setGameSessionIdIsSet(false);
    this.gameSessionId = 0;
    setAmountIsSet(false);
    this.amount = 0;
    setBalanceIsSet(false);
    this.balance = 0;
    setPlayerRoundIdIsSet(false);
    this.playerRoundId = 0;
    setSuccessIsSet(false);
    this.success = false;
    setErrorCodeIsSet(false);
    this.errorCode = 0;
    this.errorDetails = null;
  }

  public long getGameSessionId() {
    return this.gameSessionId;
  }

  public TSitInResult setGameSessionId(long gameSessionId) {
    this.gameSessionId = gameSessionId;
    setGameSessionIdIsSet(true);
    return this;
  }

  public void unsetGameSessionId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __GAMESESSIONID_ISSET_ID);
  }

  /** Returns true if field gameSessionId is set (has been assigned a value) and false otherwise */
  public boolean isSetGameSessionId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __GAMESESSIONID_ISSET_ID);
  }

  public void setGameSessionIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __GAMESESSIONID_ISSET_ID, value);
  }

  public long getAmount() {
    return this.amount;
  }

  public TSitInResult setAmount(long amount) {
    this.amount = amount;
    setAmountIsSet(true);
    return this;
  }

  public void unsetAmount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __AMOUNT_ISSET_ID);
  }

  /** Returns true if field amount is set (has been assigned a value) and false otherwise */
  public boolean isSetAmount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __AMOUNT_ISSET_ID);
  }

  public void setAmountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __AMOUNT_ISSET_ID, value);
  }

  public long getBalance() {
    return this.balance;
  }

  public TSitInResult setBalance(long balance) {
    this.balance = balance;
    setBalanceIsSet(true);
    return this;
  }

  public void unsetBalance() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BALANCE_ISSET_ID);
  }

  /** Returns true if field balance is set (has been assigned a value) and false otherwise */
  public boolean isSetBalance() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BALANCE_ISSET_ID);
  }

  public void setBalanceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BALANCE_ISSET_ID, value);
  }

  public long getPlayerRoundId() {
    return this.playerRoundId;
  }

  public TSitInResult setPlayerRoundId(long playerRoundId) {
    this.playerRoundId = playerRoundId;
    setPlayerRoundIdIsSet(true);
    return this;
  }

  public void unsetPlayerRoundId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PLAYERROUNDID_ISSET_ID);
  }

  /** Returns true if field playerRoundId is set (has been assigned a value) and false otherwise */
  public boolean isSetPlayerRoundId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PLAYERROUNDID_ISSET_ID);
  }

  public void setPlayerRoundIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PLAYERROUNDID_ISSET_ID, value);
  }

  public boolean isSuccess() {
    return this.success;
  }

  public TSitInResult setSuccess(boolean success) {
    this.success = success;
    setSuccessIsSet(true);
    return this;
  }

  public void unsetSuccess() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SUCCESS_ISSET_ID);
  }

  /** Returns true if field success is set (has been assigned a value) and false otherwise */
  public boolean isSetSuccess() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SUCCESS_ISSET_ID);
  }

  public void setSuccessIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SUCCESS_ISSET_ID, value);
  }

  public int getErrorCode() {
    return this.errorCode;
  }

  public TSitInResult setErrorCode(int errorCode) {
    this.errorCode = errorCode;
    setErrorCodeIsSet(true);
    return this;
  }

  public void unsetErrorCode() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ERRORCODE_ISSET_ID);
  }

  /** Returns true if field errorCode is set (has been assigned a value) and false otherwise */
  public boolean isSetErrorCode() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ERRORCODE_ISSET_ID);
  }

  public void setErrorCodeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ERRORCODE_ISSET_ID, value);
  }

  public java.lang.String getErrorDetails() {
    return this.errorDetails;
  }

  public TSitInResult setErrorDetails(java.lang.String errorDetails) {
    this.errorDetails = errorDetails;
    return this;
  }

  public void unsetErrorDetails() {
    this.errorDetails = null;
  }

  /** Returns true if field errorDetails is set (has been assigned a value) and false otherwise */
  public boolean isSetErrorDetails() {
    return this.errorDetails != null;
  }

  public void setErrorDetailsIsSet(boolean value) {
    if (!value) {
      this.errorDetails = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case GAME_SESSION_ID:
      if (value == null) {
        unsetGameSessionId();
      } else {
        setGameSessionId((java.lang.Long)value);
      }
      break;

    case AMOUNT:
      if (value == null) {
        unsetAmount();
      } else {
        setAmount((java.lang.Long)value);
      }
      break;

    case BALANCE:
      if (value == null) {
        unsetBalance();
      } else {
        setBalance((java.lang.Long)value);
      }
      break;

    case PLAYER_ROUND_ID:
      if (value == null) {
        unsetPlayerRoundId();
      } else {
        setPlayerRoundId((java.lang.Long)value);
      }
      break;

    case SUCCESS:
      if (value == null) {
        unsetSuccess();
      } else {
        setSuccess((java.lang.Boolean)value);
      }
      break;

    case ERROR_CODE:
      if (value == null) {
        unsetErrorCode();
      } else {
        setErrorCode((java.lang.Integer)value);
      }
      break;

    case ERROR_DETAILS:
      if (value == null) {
        unsetErrorDetails();
      } else {
        setErrorDetails((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case GAME_SESSION_ID:
      return getGameSessionId();

    case AMOUNT:
      return getAmount();

    case BALANCE:
      return getBalance();

    case PLAYER_ROUND_ID:
      return getPlayerRoundId();

    case SUCCESS:
      return isSuccess();

    case ERROR_CODE:
      return getErrorCode();

    case ERROR_DETAILS:
      return getErrorDetails();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case GAME_SESSION_ID:
      return isSetGameSessionId();
    case AMOUNT:
      return isSetAmount();
    case BALANCE:
      return isSetBalance();
    case PLAYER_ROUND_ID:
      return isSetPlayerRoundId();
    case SUCCESS:
      return isSetSuccess();
    case ERROR_CODE:
      return isSetErrorCode();
    case ERROR_DETAILS:
      return isSetErrorDetails();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TSitInResult)
      return this.equals((TSitInResult)that);
    return false;
  }

  public boolean equals(TSitInResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_gameSessionId = true;
    boolean that_present_gameSessionId = true;
    if (this_present_gameSessionId || that_present_gameSessionId) {
      if (!(this_present_gameSessionId && that_present_gameSessionId))
        return false;
      if (this.gameSessionId != that.gameSessionId)
        return false;
    }

    boolean this_present_amount = true;
    boolean that_present_amount = true;
    if (this_present_amount || that_present_amount) {
      if (!(this_present_amount && that_present_amount))
        return false;
      if (this.amount != that.amount)
        return false;
    }

    boolean this_present_balance = true;
    boolean that_present_balance = true;
    if (this_present_balance || that_present_balance) {
      if (!(this_present_balance && that_present_balance))
        return false;
      if (this.balance != that.balance)
        return false;
    }

    boolean this_present_playerRoundId = true;
    boolean that_present_playerRoundId = true;
    if (this_present_playerRoundId || that_present_playerRoundId) {
      if (!(this_present_playerRoundId && that_present_playerRoundId))
        return false;
      if (this.playerRoundId != that.playerRoundId)
        return false;
    }

    boolean this_present_success = true;
    boolean that_present_success = true;
    if (this_present_success || that_present_success) {
      if (!(this_present_success && that_present_success))
        return false;
      if (this.success != that.success)
        return false;
    }

    boolean this_present_errorCode = true;
    boolean that_present_errorCode = true;
    if (this_present_errorCode || that_present_errorCode) {
      if (!(this_present_errorCode && that_present_errorCode))
        return false;
      if (this.errorCode != that.errorCode)
        return false;
    }

    boolean this_present_errorDetails = true && this.isSetErrorDetails();
    boolean that_present_errorDetails = true && that.isSetErrorDetails();
    if (this_present_errorDetails || that_present_errorDetails) {
      if (!(this_present_errorDetails && that_present_errorDetails))
        return false;
      if (!this.errorDetails.equals(that.errorDetails))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(gameSessionId);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(amount);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(balance);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(playerRoundId);

    hashCode = hashCode * 8191 + ((success) ? 131071 : 524287);

    hashCode = hashCode * 8191 + errorCode;

    hashCode = hashCode * 8191 + ((isSetErrorDetails()) ? 131071 : 524287);
    if (isSetErrorDetails())
      hashCode = hashCode * 8191 + errorDetails.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TSitInResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetGameSessionId()).compareTo(other.isSetGameSessionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGameSessionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gameSessionId, other.gameSessionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetAmount()).compareTo(other.isSetAmount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAmount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.amount, other.amount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBalance()).compareTo(other.isSetBalance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBalance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.balance, other.balance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPlayerRoundId()).compareTo(other.isSetPlayerRoundId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayerRoundId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.playerRoundId, other.playerRoundId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSuccess()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetErrorCode()).compareTo(other.isSetErrorCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetErrorCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.errorCode, other.errorCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetErrorDetails()).compareTo(other.isSetErrorDetails());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetErrorDetails()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.errorDetails, other.errorDetails);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TSitInResult(");
    boolean first = true;

    sb.append("gameSessionId:");
    sb.append(this.gameSessionId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("amount:");
    sb.append(this.amount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("balance:");
    sb.append(this.balance);
    first = false;
    if (!first) sb.append(", ");
    sb.append("playerRoundId:");
    sb.append(this.playerRoundId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("success:");
    sb.append(this.success);
    first = false;
    if (!first) sb.append(", ");
    sb.append("errorCode:");
    sb.append(this.errorCode);
    first = false;
    if (!first) sb.append(", ");
    sb.append("errorDetails:");
    if (this.errorDetails == null) {
      sb.append("null");
    } else {
      sb.append(this.errorDetails);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TSitInResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TSitInResultStandardScheme getScheme() {
      return new TSitInResultStandardScheme();
    }
  }

  private static class TSitInResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<TSitInResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TSitInResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // GAME_SESSION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.gameSessionId = iprot.readI64();
              struct.setGameSessionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // AMOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.amount = iprot.readI64();
              struct.setAmountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // BALANCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.balance = iprot.readI64();
              struct.setBalanceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PLAYER_ROUND_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.playerRoundId = iprot.readI64();
              struct.setPlayerRoundIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // SUCCESS
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.success = iprot.readBool();
              struct.setSuccessIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ERROR_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.errorCode = iprot.readI32();
              struct.setErrorCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // ERROR_DETAILS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.errorDetails = iprot.readString();
              struct.setErrorDetailsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TSitInResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(GAME_SESSION_ID_FIELD_DESC);
      oprot.writeI64(struct.gameSessionId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(AMOUNT_FIELD_DESC);
      oprot.writeI64(struct.amount);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BALANCE_FIELD_DESC);
      oprot.writeI64(struct.balance);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PLAYER_ROUND_ID_FIELD_DESC);
      oprot.writeI64(struct.playerRoundId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
      oprot.writeBool(struct.success);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ERROR_CODE_FIELD_DESC);
      oprot.writeI32(struct.errorCode);
      oprot.writeFieldEnd();
      if (struct.errorDetails != null) {
        oprot.writeFieldBegin(ERROR_DETAILS_FIELD_DESC);
        oprot.writeString(struct.errorDetails);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TSitInResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TSitInResultTupleScheme getScheme() {
      return new TSitInResultTupleScheme();
    }
  }

  private static class TSitInResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<TSitInResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TSitInResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetGameSessionId()) {
        optionals.set(0);
      }
      if (struct.isSetAmount()) {
        optionals.set(1);
      }
      if (struct.isSetBalance()) {
        optionals.set(2);
      }
      if (struct.isSetPlayerRoundId()) {
        optionals.set(3);
      }
      if (struct.isSetSuccess()) {
        optionals.set(4);
      }
      if (struct.isSetErrorCode()) {
        optionals.set(5);
      }
      if (struct.isSetErrorDetails()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetGameSessionId()) {
        oprot.writeI64(struct.gameSessionId);
      }
      if (struct.isSetAmount()) {
        oprot.writeI64(struct.amount);
      }
      if (struct.isSetBalance()) {
        oprot.writeI64(struct.balance);
      }
      if (struct.isSetPlayerRoundId()) {
        oprot.writeI64(struct.playerRoundId);
      }
      if (struct.isSetSuccess()) {
        oprot.writeBool(struct.success);
      }
      if (struct.isSetErrorCode()) {
        oprot.writeI32(struct.errorCode);
      }
      if (struct.isSetErrorDetails()) {
        oprot.writeString(struct.errorDetails);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TSitInResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.gameSessionId = iprot.readI64();
        struct.setGameSessionIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.amount = iprot.readI64();
        struct.setAmountIsSet(true);
      }
      if (incoming.get(2)) {
        struct.balance = iprot.readI64();
        struct.setBalanceIsSet(true);
      }
      if (incoming.get(3)) {
        struct.playerRoundId = iprot.readI64();
        struct.setPlayerRoundIdIsSet(true);
      }
      if (incoming.get(4)) {
        struct.success = iprot.readBool();
        struct.setSuccessIsSet(true);
      }
      if (incoming.get(5)) {
        struct.errorCode = iprot.readI32();
        struct.setErrorCodeIsSet(true);
      }
      if (incoming.get(6)) {
        struct.errorDetails = iprot.readString();
        struct.setErrorDetailsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

