/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dgphoenix.casino.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TTournamentInfo implements org.apache.thrift.TBase<TTournamentInfo, TTournamentInfo._Fields>, java.io.Serializable, Cloneable, Comparable<TTournamentInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TTournamentInfo");

  private static final org.apache.thrift.protocol.TField TOURNAMENT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("tournamentId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField STATE_FIELD_DESC = new org.apache.thrift.protocol.TField("state", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField START_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("startDate", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField END_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("endDate", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField BALANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("balance", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField BUY_IN_PRICE_FIELD_DESC = new org.apache.thrift.protocol.TField("buyInPrice", org.apache.thrift.protocol.TType.I64, (short)7);
  private static final org.apache.thrift.protocol.TField BUY_IN_AMOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("buyInAmount", org.apache.thrift.protocol.TType.I64, (short)8);
  private static final org.apache.thrift.protocol.TField RE_BUY_ALLOWED_FIELD_DESC = new org.apache.thrift.protocol.TField("reBuyAllowed", org.apache.thrift.protocol.TType.BOOL, (short)9);
  private static final org.apache.thrift.protocol.TField RE_BUY_PRICE_FIELD_DESC = new org.apache.thrift.protocol.TField("reBuyPrice", org.apache.thrift.protocol.TType.I64, (short)10);
  private static final org.apache.thrift.protocol.TField RE_BUY_AMOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("reBuyAmount", org.apache.thrift.protocol.TType.I64, (short)11);
  private static final org.apache.thrift.protocol.TField RE_BUY_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("reBuyCount", org.apache.thrift.protocol.TType.I32, (short)12);
  private static final org.apache.thrift.protocol.TField RE_BUY_LIMIT_FIELD_DESC = new org.apache.thrift.protocol.TField("reBuyLimit", org.apache.thrift.protocol.TType.I32, (short)13);
  private static final org.apache.thrift.protocol.TField RESET_BALANCE_AFTER_REBUY_FIELD_DESC = new org.apache.thrift.protocol.TField("resetBalanceAfterRebuy", org.apache.thrift.protocol.TType.BOOL, (short)14);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TTournamentInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TTournamentInfoTupleSchemeFactory();

  public long tournamentId; // required
  public java.lang.String name; // required
  public java.lang.String state; // required
  public long startDate; // required
  public long endDate; // required
  public long balance; // required
  public long buyInPrice; // required
  public long buyInAmount; // required
  public boolean reBuyAllowed; // required
  public long reBuyPrice; // required
  public long reBuyAmount; // required
  public int reBuyCount; // required
  public int reBuyLimit; // required
  public boolean resetBalanceAfterRebuy; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TOURNAMENT_ID((short)1, "tournamentId"),
    NAME((short)2, "name"),
    STATE((short)3, "state"),
    START_DATE((short)4, "startDate"),
    END_DATE((short)5, "endDate"),
    BALANCE((short)6, "balance"),
    BUY_IN_PRICE((short)7, "buyInPrice"),
    BUY_IN_AMOUNT((short)8, "buyInAmount"),
    RE_BUY_ALLOWED((short)9, "reBuyAllowed"),
    RE_BUY_PRICE((short)10, "reBuyPrice"),
    RE_BUY_AMOUNT((short)11, "reBuyAmount"),
    RE_BUY_COUNT((short)12, "reBuyCount"),
    RE_BUY_LIMIT((short)13, "reBuyLimit"),
    RESET_BALANCE_AFTER_REBUY((short)14, "resetBalanceAfterRebuy");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TOURNAMENT_ID
          return TOURNAMENT_ID;
        case 2: // NAME
          return NAME;
        case 3: // STATE
          return STATE;
        case 4: // START_DATE
          return START_DATE;
        case 5: // END_DATE
          return END_DATE;
        case 6: // BALANCE
          return BALANCE;
        case 7: // BUY_IN_PRICE
          return BUY_IN_PRICE;
        case 8: // BUY_IN_AMOUNT
          return BUY_IN_AMOUNT;
        case 9: // RE_BUY_ALLOWED
          return RE_BUY_ALLOWED;
        case 10: // RE_BUY_PRICE
          return RE_BUY_PRICE;
        case 11: // RE_BUY_AMOUNT
          return RE_BUY_AMOUNT;
        case 12: // RE_BUY_COUNT
          return RE_BUY_COUNT;
        case 13: // RE_BUY_LIMIT
          return RE_BUY_LIMIT;
        case 14: // RESET_BALANCE_AFTER_REBUY
          return RESET_BALANCE_AFTER_REBUY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TOURNAMENTID_ISSET_ID = 0;
  private static final int __STARTDATE_ISSET_ID = 1;
  private static final int __ENDDATE_ISSET_ID = 2;
  private static final int __BALANCE_ISSET_ID = 3;
  private static final int __BUYINPRICE_ISSET_ID = 4;
  private static final int __BUYINAMOUNT_ISSET_ID = 5;
  private static final int __REBUYALLOWED_ISSET_ID = 6;
  private static final int __REBUYPRICE_ISSET_ID = 7;
  private static final int __REBUYAMOUNT_ISSET_ID = 8;
  private static final int __REBUYCOUNT_ISSET_ID = 9;
  private static final int __REBUYLIMIT_ISSET_ID = 10;
  private static final int __RESETBALANCEAFTERREBUY_ISSET_ID = 11;
  private short __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TOURNAMENT_ID, new org.apache.thrift.meta_data.FieldMetaData("tournamentId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STATE, new org.apache.thrift.meta_data.FieldMetaData("state", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.START_DATE, new org.apache.thrift.meta_data.FieldMetaData("startDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.END_DATE, new org.apache.thrift.meta_data.FieldMetaData("endDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.BALANCE, new org.apache.thrift.meta_data.FieldMetaData("balance", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.BUY_IN_PRICE, new org.apache.thrift.meta_data.FieldMetaData("buyInPrice", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.BUY_IN_AMOUNT, new org.apache.thrift.meta_data.FieldMetaData("buyInAmount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.RE_BUY_ALLOWED, new org.apache.thrift.meta_data.FieldMetaData("reBuyAllowed", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.RE_BUY_PRICE, new org.apache.thrift.meta_data.FieldMetaData("reBuyPrice", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.RE_BUY_AMOUNT, new org.apache.thrift.meta_data.FieldMetaData("reBuyAmount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.RE_BUY_COUNT, new org.apache.thrift.meta_data.FieldMetaData("reBuyCount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.RE_BUY_LIMIT, new org.apache.thrift.meta_data.FieldMetaData("reBuyLimit", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.RESET_BALANCE_AFTER_REBUY, new org.apache.thrift.meta_data.FieldMetaData("resetBalanceAfterRebuy", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TTournamentInfo.class, metaDataMap);
  }

  public TTournamentInfo() {
  }

  public TTournamentInfo(
    long tournamentId,
    java.lang.String name,
    java.lang.String state,
    long startDate,
    long endDate,
    long balance,
    long buyInPrice,
    long buyInAmount,
    boolean reBuyAllowed,
    long reBuyPrice,
    long reBuyAmount,
    int reBuyCount,
    int reBuyLimit,
    boolean resetBalanceAfterRebuy)
  {
    this();
    this.tournamentId = tournamentId;
    setTournamentIdIsSet(true);
    this.name = name;
    this.state = state;
    this.startDate = startDate;
    setStartDateIsSet(true);
    this.endDate = endDate;
    setEndDateIsSet(true);
    this.balance = balance;
    setBalanceIsSet(true);
    this.buyInPrice = buyInPrice;
    setBuyInPriceIsSet(true);
    this.buyInAmount = buyInAmount;
    setBuyInAmountIsSet(true);
    this.reBuyAllowed = reBuyAllowed;
    setReBuyAllowedIsSet(true);
    this.reBuyPrice = reBuyPrice;
    setReBuyPriceIsSet(true);
    this.reBuyAmount = reBuyAmount;
    setReBuyAmountIsSet(true);
    this.reBuyCount = reBuyCount;
    setReBuyCountIsSet(true);
    this.reBuyLimit = reBuyLimit;
    setReBuyLimitIsSet(true);
    this.resetBalanceAfterRebuy = resetBalanceAfterRebuy;
    setResetBalanceAfterRebuyIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TTournamentInfo(TTournamentInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.tournamentId = other.tournamentId;
    if (other.isSetName()) {
      this.name = other.name;
    }
    if (other.isSetState()) {
      this.state = other.state;
    }
    this.startDate = other.startDate;
    this.endDate = other.endDate;
    this.balance = other.balance;
    this.buyInPrice = other.buyInPrice;
    this.buyInAmount = other.buyInAmount;
    this.reBuyAllowed = other.reBuyAllowed;
    this.reBuyPrice = other.reBuyPrice;
    this.reBuyAmount = other.reBuyAmount;
    this.reBuyCount = other.reBuyCount;
    this.reBuyLimit = other.reBuyLimit;
    this.resetBalanceAfterRebuy = other.resetBalanceAfterRebuy;
  }

  public TTournamentInfo deepCopy() {
    return new TTournamentInfo(this);
  }

  @Override
  public void clear() {
    setTournamentIdIsSet(false);
    this.tournamentId = 0;
    this.name = null;
    this.state = null;
    setStartDateIsSet(false);
    this.startDate = 0;
    setEndDateIsSet(false);
    this.endDate = 0;
    setBalanceIsSet(false);
    this.balance = 0;
    setBuyInPriceIsSet(false);
    this.buyInPrice = 0;
    setBuyInAmountIsSet(false);
    this.buyInAmount = 0;
    setReBuyAllowedIsSet(false);
    this.reBuyAllowed = false;
    setReBuyPriceIsSet(false);
    this.reBuyPrice = 0;
    setReBuyAmountIsSet(false);
    this.reBuyAmount = 0;
    setReBuyCountIsSet(false);
    this.reBuyCount = 0;
    setReBuyLimitIsSet(false);
    this.reBuyLimit = 0;
    setResetBalanceAfterRebuyIsSet(false);
    this.resetBalanceAfterRebuy = false;
  }

  public long getTournamentId() {
    return this.tournamentId;
  }

  public TTournamentInfo setTournamentId(long tournamentId) {
    this.tournamentId = tournamentId;
    setTournamentIdIsSet(true);
    return this;
  }

  public void unsetTournamentId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TOURNAMENTID_ISSET_ID);
  }

  /** Returns true if field tournamentId is set (has been assigned a value) and false otherwise */
  public boolean isSetTournamentId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TOURNAMENTID_ISSET_ID);
  }

  public void setTournamentIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TOURNAMENTID_ISSET_ID, value);
  }

  public java.lang.String getName() {
    return this.name;
  }

  public TTournamentInfo setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public java.lang.String getState() {
    return this.state;
  }

  public TTournamentInfo setState(java.lang.String state) {
    this.state = state;
    return this;
  }

  public void unsetState() {
    this.state = null;
  }

  /** Returns true if field state is set (has been assigned a value) and false otherwise */
  public boolean isSetState() {
    return this.state != null;
  }

  public void setStateIsSet(boolean value) {
    if (!value) {
      this.state = null;
    }
  }

  public long getStartDate() {
    return this.startDate;
  }

  public TTournamentInfo setStartDate(long startDate) {
    this.startDate = startDate;
    setStartDateIsSet(true);
    return this;
  }

  public void unsetStartDate() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STARTDATE_ISSET_ID);
  }

  /** Returns true if field startDate is set (has been assigned a value) and false otherwise */
  public boolean isSetStartDate() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STARTDATE_ISSET_ID);
  }

  public void setStartDateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STARTDATE_ISSET_ID, value);
  }

  public long getEndDate() {
    return this.endDate;
  }

  public TTournamentInfo setEndDate(long endDate) {
    this.endDate = endDate;
    setEndDateIsSet(true);
    return this;
  }

  public void unsetEndDate() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ENDDATE_ISSET_ID);
  }

  /** Returns true if field endDate is set (has been assigned a value) and false otherwise */
  public boolean isSetEndDate() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ENDDATE_ISSET_ID);
  }

  public void setEndDateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ENDDATE_ISSET_ID, value);
  }

  public long getBalance() {
    return this.balance;
  }

  public TTournamentInfo setBalance(long balance) {
    this.balance = balance;
    setBalanceIsSet(true);
    return this;
  }

  public void unsetBalance() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BALANCE_ISSET_ID);
  }

  /** Returns true if field balance is set (has been assigned a value) and false otherwise */
  public boolean isSetBalance() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BALANCE_ISSET_ID);
  }

  public void setBalanceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BALANCE_ISSET_ID, value);
  }

  public long getBuyInPrice() {
    return this.buyInPrice;
  }

  public TTournamentInfo setBuyInPrice(long buyInPrice) {
    this.buyInPrice = buyInPrice;
    setBuyInPriceIsSet(true);
    return this;
  }

  public void unsetBuyInPrice() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BUYINPRICE_ISSET_ID);
  }

  /** Returns true if field buyInPrice is set (has been assigned a value) and false otherwise */
  public boolean isSetBuyInPrice() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BUYINPRICE_ISSET_ID);
  }

  public void setBuyInPriceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BUYINPRICE_ISSET_ID, value);
  }

  public long getBuyInAmount() {
    return this.buyInAmount;
  }

  public TTournamentInfo setBuyInAmount(long buyInAmount) {
    this.buyInAmount = buyInAmount;
    setBuyInAmountIsSet(true);
    return this;
  }

  public void unsetBuyInAmount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BUYINAMOUNT_ISSET_ID);
  }

  /** Returns true if field buyInAmount is set (has been assigned a value) and false otherwise */
  public boolean isSetBuyInAmount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BUYINAMOUNT_ISSET_ID);
  }

  public void setBuyInAmountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BUYINAMOUNT_ISSET_ID, value);
  }

  public boolean isReBuyAllowed() {
    return this.reBuyAllowed;
  }

  public TTournamentInfo setReBuyAllowed(boolean reBuyAllowed) {
    this.reBuyAllowed = reBuyAllowed;
    setReBuyAllowedIsSet(true);
    return this;
  }

  public void unsetReBuyAllowed() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __REBUYALLOWED_ISSET_ID);
  }

  /** Returns true if field reBuyAllowed is set (has been assigned a value) and false otherwise */
  public boolean isSetReBuyAllowed() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __REBUYALLOWED_ISSET_ID);
  }

  public void setReBuyAllowedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __REBUYALLOWED_ISSET_ID, value);
  }

  public long getReBuyPrice() {
    return this.reBuyPrice;
  }

  public TTournamentInfo setReBuyPrice(long reBuyPrice) {
    this.reBuyPrice = reBuyPrice;
    setReBuyPriceIsSet(true);
    return this;
  }

  public void unsetReBuyPrice() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __REBUYPRICE_ISSET_ID);
  }

  /** Returns true if field reBuyPrice is set (has been assigned a value) and false otherwise */
  public boolean isSetReBuyPrice() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __REBUYPRICE_ISSET_ID);
  }

  public void setReBuyPriceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __REBUYPRICE_ISSET_ID, value);
  }

  public long getReBuyAmount() {
    return this.reBuyAmount;
  }

  public TTournamentInfo setReBuyAmount(long reBuyAmount) {
    this.reBuyAmount = reBuyAmount;
    setReBuyAmountIsSet(true);
    return this;
  }

  public void unsetReBuyAmount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __REBUYAMOUNT_ISSET_ID);
  }

  /** Returns true if field reBuyAmount is set (has been assigned a value) and false otherwise */
  public boolean isSetReBuyAmount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __REBUYAMOUNT_ISSET_ID);
  }

  public void setReBuyAmountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __REBUYAMOUNT_ISSET_ID, value);
  }

  public int getReBuyCount() {
    return this.reBuyCount;
  }

  public TTournamentInfo setReBuyCount(int reBuyCount) {
    this.reBuyCount = reBuyCount;
    setReBuyCountIsSet(true);
    return this;
  }

  public void unsetReBuyCount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __REBUYCOUNT_ISSET_ID);
  }

  /** Returns true if field reBuyCount is set (has been assigned a value) and false otherwise */
  public boolean isSetReBuyCount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __REBUYCOUNT_ISSET_ID);
  }

  public void setReBuyCountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __REBUYCOUNT_ISSET_ID, value);
  }

  public int getReBuyLimit() {
    return this.reBuyLimit;
  }

  public TTournamentInfo setReBuyLimit(int reBuyLimit) {
    this.reBuyLimit = reBuyLimit;
    setReBuyLimitIsSet(true);
    return this;
  }

  public void unsetReBuyLimit() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __REBUYLIMIT_ISSET_ID);
  }

  /** Returns true if field reBuyLimit is set (has been assigned a value) and false otherwise */
  public boolean isSetReBuyLimit() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __REBUYLIMIT_ISSET_ID);
  }

  public void setReBuyLimitIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __REBUYLIMIT_ISSET_ID, value);
  }

  public boolean isResetBalanceAfterRebuy() {
    return this.resetBalanceAfterRebuy;
  }

  public TTournamentInfo setResetBalanceAfterRebuy(boolean resetBalanceAfterRebuy) {
    this.resetBalanceAfterRebuy = resetBalanceAfterRebuy;
    setResetBalanceAfterRebuyIsSet(true);
    return this;
  }

  public void unsetResetBalanceAfterRebuy() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RESETBALANCEAFTERREBUY_ISSET_ID);
  }

  /** Returns true if field resetBalanceAfterRebuy is set (has been assigned a value) and false otherwise */
  public boolean isSetResetBalanceAfterRebuy() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RESETBALANCEAFTERREBUY_ISSET_ID);
  }

  public void setResetBalanceAfterRebuyIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RESETBALANCEAFTERREBUY_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case TOURNAMENT_ID:
      if (value == null) {
        unsetTournamentId();
      } else {
        setTournamentId((java.lang.Long)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((java.lang.String)value);
      }
      break;

    case STATE:
      if (value == null) {
        unsetState();
      } else {
        setState((java.lang.String)value);
      }
      break;

    case START_DATE:
      if (value == null) {
        unsetStartDate();
      } else {
        setStartDate((java.lang.Long)value);
      }
      break;

    case END_DATE:
      if (value == null) {
        unsetEndDate();
      } else {
        setEndDate((java.lang.Long)value);
      }
      break;

    case BALANCE:
      if (value == null) {
        unsetBalance();
      } else {
        setBalance((java.lang.Long)value);
      }
      break;

    case BUY_IN_PRICE:
      if (value == null) {
        unsetBuyInPrice();
      } else {
        setBuyInPrice((java.lang.Long)value);
      }
      break;

    case BUY_IN_AMOUNT:
      if (value == null) {
        unsetBuyInAmount();
      } else {
        setBuyInAmount((java.lang.Long)value);
      }
      break;

    case RE_BUY_ALLOWED:
      if (value == null) {
        unsetReBuyAllowed();
      } else {
        setReBuyAllowed((java.lang.Boolean)value);
      }
      break;

    case RE_BUY_PRICE:
      if (value == null) {
        unsetReBuyPrice();
      } else {
        setReBuyPrice((java.lang.Long)value);
      }
      break;

    case RE_BUY_AMOUNT:
      if (value == null) {
        unsetReBuyAmount();
      } else {
        setReBuyAmount((java.lang.Long)value);
      }
      break;

    case RE_BUY_COUNT:
      if (value == null) {
        unsetReBuyCount();
      } else {
        setReBuyCount((java.lang.Integer)value);
      }
      break;

    case RE_BUY_LIMIT:
      if (value == null) {
        unsetReBuyLimit();
      } else {
        setReBuyLimit((java.lang.Integer)value);
      }
      break;

    case RESET_BALANCE_AFTER_REBUY:
      if (value == null) {
        unsetResetBalanceAfterRebuy();
      } else {
        setResetBalanceAfterRebuy((java.lang.Boolean)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TOURNAMENT_ID:
      return getTournamentId();

    case NAME:
      return getName();

    case STATE:
      return getState();

    case START_DATE:
      return getStartDate();

    case END_DATE:
      return getEndDate();

    case BALANCE:
      return getBalance();

    case BUY_IN_PRICE:
      return getBuyInPrice();

    case BUY_IN_AMOUNT:
      return getBuyInAmount();

    case RE_BUY_ALLOWED:
      return isReBuyAllowed();

    case RE_BUY_PRICE:
      return getReBuyPrice();

    case RE_BUY_AMOUNT:
      return getReBuyAmount();

    case RE_BUY_COUNT:
      return getReBuyCount();

    case RE_BUY_LIMIT:
      return getReBuyLimit();

    case RESET_BALANCE_AFTER_REBUY:
      return isResetBalanceAfterRebuy();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TOURNAMENT_ID:
      return isSetTournamentId();
    case NAME:
      return isSetName();
    case STATE:
      return isSetState();
    case START_DATE:
      return isSetStartDate();
    case END_DATE:
      return isSetEndDate();
    case BALANCE:
      return isSetBalance();
    case BUY_IN_PRICE:
      return isSetBuyInPrice();
    case BUY_IN_AMOUNT:
      return isSetBuyInAmount();
    case RE_BUY_ALLOWED:
      return isSetReBuyAllowed();
    case RE_BUY_PRICE:
      return isSetReBuyPrice();
    case RE_BUY_AMOUNT:
      return isSetReBuyAmount();
    case RE_BUY_COUNT:
      return isSetReBuyCount();
    case RE_BUY_LIMIT:
      return isSetReBuyLimit();
    case RESET_BALANCE_AFTER_REBUY:
      return isSetResetBalanceAfterRebuy();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TTournamentInfo)
      return this.equals((TTournamentInfo)that);
    return false;
  }

  public boolean equals(TTournamentInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_tournamentId = true;
    boolean that_present_tournamentId = true;
    if (this_present_tournamentId || that_present_tournamentId) {
      if (!(this_present_tournamentId && that_present_tournamentId))
        return false;
      if (this.tournamentId != that.tournamentId)
        return false;
    }

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_state = true && this.isSetState();
    boolean that_present_state = true && that.isSetState();
    if (this_present_state || that_present_state) {
      if (!(this_present_state && that_present_state))
        return false;
      if (!this.state.equals(that.state))
        return false;
    }

    boolean this_present_startDate = true;
    boolean that_present_startDate = true;
    if (this_present_startDate || that_present_startDate) {
      if (!(this_present_startDate && that_present_startDate))
        return false;
      if (this.startDate != that.startDate)
        return false;
    }

    boolean this_present_endDate = true;
    boolean that_present_endDate = true;
    if (this_present_endDate || that_present_endDate) {
      if (!(this_present_endDate && that_present_endDate))
        return false;
      if (this.endDate != that.endDate)
        return false;
    }

    boolean this_present_balance = true;
    boolean that_present_balance = true;
    if (this_present_balance || that_present_balance) {
      if (!(this_present_balance && that_present_balance))
        return false;
      if (this.balance != that.balance)
        return false;
    }

    boolean this_present_buyInPrice = true;
    boolean that_present_buyInPrice = true;
    if (this_present_buyInPrice || that_present_buyInPrice) {
      if (!(this_present_buyInPrice && that_present_buyInPrice))
        return false;
      if (this.buyInPrice != that.buyInPrice)
        return false;
    }

    boolean this_present_buyInAmount = true;
    boolean that_present_buyInAmount = true;
    if (this_present_buyInAmount || that_present_buyInAmount) {
      if (!(this_present_buyInAmount && that_present_buyInAmount))
        return false;
      if (this.buyInAmount != that.buyInAmount)
        return false;
    }

    boolean this_present_reBuyAllowed = true;
    boolean that_present_reBuyAllowed = true;
    if (this_present_reBuyAllowed || that_present_reBuyAllowed) {
      if (!(this_present_reBuyAllowed && that_present_reBuyAllowed))
        return false;
      if (this.reBuyAllowed != that.reBuyAllowed)
        return false;
    }

    boolean this_present_reBuyPrice = true;
    boolean that_present_reBuyPrice = true;
    if (this_present_reBuyPrice || that_present_reBuyPrice) {
      if (!(this_present_reBuyPrice && that_present_reBuyPrice))
        return false;
      if (this.reBuyPrice != that.reBuyPrice)
        return false;
    }

    boolean this_present_reBuyAmount = true;
    boolean that_present_reBuyAmount = true;
    if (this_present_reBuyAmount || that_present_reBuyAmount) {
      if (!(this_present_reBuyAmount && that_present_reBuyAmount))
        return false;
      if (this.reBuyAmount != that.reBuyAmount)
        return false;
    }

    boolean this_present_reBuyCount = true;
    boolean that_present_reBuyCount = true;
    if (this_present_reBuyCount || that_present_reBuyCount) {
      if (!(this_present_reBuyCount && that_present_reBuyCount))
        return false;
      if (this.reBuyCount != that.reBuyCount)
        return false;
    }

    boolean this_present_reBuyLimit = true;
    boolean that_present_reBuyLimit = true;
    if (this_present_reBuyLimit || that_present_reBuyLimit) {
      if (!(this_present_reBuyLimit && that_present_reBuyLimit))
        return false;
      if (this.reBuyLimit != that.reBuyLimit)
        return false;
    }

    boolean this_present_resetBalanceAfterRebuy = true;
    boolean that_present_resetBalanceAfterRebuy = true;
    if (this_present_resetBalanceAfterRebuy || that_present_resetBalanceAfterRebuy) {
      if (!(this_present_resetBalanceAfterRebuy && that_present_resetBalanceAfterRebuy))
        return false;
      if (this.resetBalanceAfterRebuy != that.resetBalanceAfterRebuy)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(tournamentId);

    hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
    if (isSetName())
      hashCode = hashCode * 8191 + name.hashCode();

    hashCode = hashCode * 8191 + ((isSetState()) ? 131071 : 524287);
    if (isSetState())
      hashCode = hashCode * 8191 + state.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(startDate);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(endDate);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(balance);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(buyInPrice);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(buyInAmount);

    hashCode = hashCode * 8191 + ((reBuyAllowed) ? 131071 : 524287);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(reBuyPrice);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(reBuyAmount);

    hashCode = hashCode * 8191 + reBuyCount;

    hashCode = hashCode * 8191 + reBuyLimit;

    hashCode = hashCode * 8191 + ((resetBalanceAfterRebuy) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(TTournamentInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetTournamentId()).compareTo(other.isSetTournamentId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTournamentId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tournamentId, other.tournamentId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetState()).compareTo(other.isSetState());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetState()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.state, other.state);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetStartDate()).compareTo(other.isSetStartDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.startDate, other.startDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetEndDate()).compareTo(other.isSetEndDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endDate, other.endDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBalance()).compareTo(other.isSetBalance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBalance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.balance, other.balance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBuyInPrice()).compareTo(other.isSetBuyInPrice());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBuyInPrice()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.buyInPrice, other.buyInPrice);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBuyInAmount()).compareTo(other.isSetBuyInAmount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBuyInAmount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.buyInAmount, other.buyInAmount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetReBuyAllowed()).compareTo(other.isSetReBuyAllowed());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReBuyAllowed()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reBuyAllowed, other.reBuyAllowed);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetReBuyPrice()).compareTo(other.isSetReBuyPrice());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReBuyPrice()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reBuyPrice, other.reBuyPrice);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetReBuyAmount()).compareTo(other.isSetReBuyAmount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReBuyAmount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reBuyAmount, other.reBuyAmount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetReBuyCount()).compareTo(other.isSetReBuyCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReBuyCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reBuyCount, other.reBuyCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetReBuyLimit()).compareTo(other.isSetReBuyLimit());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReBuyLimit()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reBuyLimit, other.reBuyLimit);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetResetBalanceAfterRebuy()).compareTo(other.isSetResetBalanceAfterRebuy());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResetBalanceAfterRebuy()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resetBalanceAfterRebuy, other.resetBalanceAfterRebuy);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TTournamentInfo(");
    boolean first = true;

    sb.append("tournamentId:");
    sb.append(this.tournamentId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("state:");
    if (this.state == null) {
      sb.append("null");
    } else {
      sb.append(this.state);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("startDate:");
    sb.append(this.startDate);
    first = false;
    if (!first) sb.append(", ");
    sb.append("endDate:");
    sb.append(this.endDate);
    first = false;
    if (!first) sb.append(", ");
    sb.append("balance:");
    sb.append(this.balance);
    first = false;
    if (!first) sb.append(", ");
    sb.append("buyInPrice:");
    sb.append(this.buyInPrice);
    first = false;
    if (!first) sb.append(", ");
    sb.append("buyInAmount:");
    sb.append(this.buyInAmount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("reBuyAllowed:");
    sb.append(this.reBuyAllowed);
    first = false;
    if (!first) sb.append(", ");
    sb.append("reBuyPrice:");
    sb.append(this.reBuyPrice);
    first = false;
    if (!first) sb.append(", ");
    sb.append("reBuyAmount:");
    sb.append(this.reBuyAmount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("reBuyCount:");
    sb.append(this.reBuyCount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("reBuyLimit:");
    sb.append(this.reBuyLimit);
    first = false;
    if (!first) sb.append(", ");
    sb.append("resetBalanceAfterRebuy:");
    sb.append(this.resetBalanceAfterRebuy);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TTournamentInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TTournamentInfoStandardScheme getScheme() {
      return new TTournamentInfoStandardScheme();
    }
  }

  private static class TTournamentInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<TTournamentInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TTournamentInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TOURNAMENT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.tournamentId = iprot.readI64();
              struct.setTournamentIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // STATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.state = iprot.readString();
              struct.setStateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // START_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.startDate = iprot.readI64();
              struct.setStartDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // END_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.endDate = iprot.readI64();
              struct.setEndDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // BALANCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.balance = iprot.readI64();
              struct.setBalanceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // BUY_IN_PRICE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.buyInPrice = iprot.readI64();
              struct.setBuyInPriceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // BUY_IN_AMOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.buyInAmount = iprot.readI64();
              struct.setBuyInAmountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // RE_BUY_ALLOWED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.reBuyAllowed = iprot.readBool();
              struct.setReBuyAllowedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // RE_BUY_PRICE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.reBuyPrice = iprot.readI64();
              struct.setReBuyPriceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // RE_BUY_AMOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.reBuyAmount = iprot.readI64();
              struct.setReBuyAmountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // RE_BUY_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.reBuyCount = iprot.readI32();
              struct.setReBuyCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // RE_BUY_LIMIT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.reBuyLimit = iprot.readI32();
              struct.setReBuyLimitIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // RESET_BALANCE_AFTER_REBUY
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.resetBalanceAfterRebuy = iprot.readBool();
              struct.setResetBalanceAfterRebuyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TTournamentInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TOURNAMENT_ID_FIELD_DESC);
      oprot.writeI64(struct.tournamentId);
      oprot.writeFieldEnd();
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      if (struct.state != null) {
        oprot.writeFieldBegin(STATE_FIELD_DESC);
        oprot.writeString(struct.state);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(START_DATE_FIELD_DESC);
      oprot.writeI64(struct.startDate);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(END_DATE_FIELD_DESC);
      oprot.writeI64(struct.endDate);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BALANCE_FIELD_DESC);
      oprot.writeI64(struct.balance);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BUY_IN_PRICE_FIELD_DESC);
      oprot.writeI64(struct.buyInPrice);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BUY_IN_AMOUNT_FIELD_DESC);
      oprot.writeI64(struct.buyInAmount);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RE_BUY_ALLOWED_FIELD_DESC);
      oprot.writeBool(struct.reBuyAllowed);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RE_BUY_PRICE_FIELD_DESC);
      oprot.writeI64(struct.reBuyPrice);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RE_BUY_AMOUNT_FIELD_DESC);
      oprot.writeI64(struct.reBuyAmount);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RE_BUY_COUNT_FIELD_DESC);
      oprot.writeI32(struct.reBuyCount);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RE_BUY_LIMIT_FIELD_DESC);
      oprot.writeI32(struct.reBuyLimit);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RESET_BALANCE_AFTER_REBUY_FIELD_DESC);
      oprot.writeBool(struct.resetBalanceAfterRebuy);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TTournamentInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TTournamentInfoTupleScheme getScheme() {
      return new TTournamentInfoTupleScheme();
    }
  }

  private static class TTournamentInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<TTournamentInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TTournamentInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTournamentId()) {
        optionals.set(0);
      }
      if (struct.isSetName()) {
        optionals.set(1);
      }
      if (struct.isSetState()) {
        optionals.set(2);
      }
      if (struct.isSetStartDate()) {
        optionals.set(3);
      }
      if (struct.isSetEndDate()) {
        optionals.set(4);
      }
      if (struct.isSetBalance()) {
        optionals.set(5);
      }
      if (struct.isSetBuyInPrice()) {
        optionals.set(6);
      }
      if (struct.isSetBuyInAmount()) {
        optionals.set(7);
      }
      if (struct.isSetReBuyAllowed()) {
        optionals.set(8);
      }
      if (struct.isSetReBuyPrice()) {
        optionals.set(9);
      }
      if (struct.isSetReBuyAmount()) {
        optionals.set(10);
      }
      if (struct.isSetReBuyCount()) {
        optionals.set(11);
      }
      if (struct.isSetReBuyLimit()) {
        optionals.set(12);
      }
      if (struct.isSetResetBalanceAfterRebuy()) {
        optionals.set(13);
      }
      oprot.writeBitSet(optionals, 14);
      if (struct.isSetTournamentId()) {
        oprot.writeI64(struct.tournamentId);
      }
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetState()) {
        oprot.writeString(struct.state);
      }
      if (struct.isSetStartDate()) {
        oprot.writeI64(struct.startDate);
      }
      if (struct.isSetEndDate()) {
        oprot.writeI64(struct.endDate);
      }
      if (struct.isSetBalance()) {
        oprot.writeI64(struct.balance);
      }
      if (struct.isSetBuyInPrice()) {
        oprot.writeI64(struct.buyInPrice);
      }
      if (struct.isSetBuyInAmount()) {
        oprot.writeI64(struct.buyInAmount);
      }
      if (struct.isSetReBuyAllowed()) {
        oprot.writeBool(struct.reBuyAllowed);
      }
      if (struct.isSetReBuyPrice()) {
        oprot.writeI64(struct.reBuyPrice);
      }
      if (struct.isSetReBuyAmount()) {
        oprot.writeI64(struct.reBuyAmount);
      }
      if (struct.isSetReBuyCount()) {
        oprot.writeI32(struct.reBuyCount);
      }
      if (struct.isSetReBuyLimit()) {
        oprot.writeI32(struct.reBuyLimit);
      }
      if (struct.isSetResetBalanceAfterRebuy()) {
        oprot.writeBool(struct.resetBalanceAfterRebuy);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TTournamentInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(14);
      if (incoming.get(0)) {
        struct.tournamentId = iprot.readI64();
        struct.setTournamentIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.state = iprot.readString();
        struct.setStateIsSet(true);
      }
      if (incoming.get(3)) {
        struct.startDate = iprot.readI64();
        struct.setStartDateIsSet(true);
      }
      if (incoming.get(4)) {
        struct.endDate = iprot.readI64();
        struct.setEndDateIsSet(true);
      }
      if (incoming.get(5)) {
        struct.balance = iprot.readI64();
        struct.setBalanceIsSet(true);
      }
      if (incoming.get(6)) {
        struct.buyInPrice = iprot.readI64();
        struct.setBuyInPriceIsSet(true);
      }
      if (incoming.get(7)) {
        struct.buyInAmount = iprot.readI64();
        struct.setBuyInAmountIsSet(true);
      }
      if (incoming.get(8)) {
        struct.reBuyAllowed = iprot.readBool();
        struct.setReBuyAllowedIsSet(true);
      }
      if (incoming.get(9)) {
        struct.reBuyPrice = iprot.readI64();
        struct.setReBuyPriceIsSet(true);
      }
      if (incoming.get(10)) {
        struct.reBuyAmount = iprot.readI64();
        struct.setReBuyAmountIsSet(true);
      }
      if (incoming.get(11)) {
        struct.reBuyCount = iprot.readI32();
        struct.setReBuyCountIsSet(true);
      }
      if (incoming.get(12)) {
        struct.reBuyLimit = iprot.readI32();
        struct.setReBuyLimitIsSet(true);
      }
      if (incoming.get(13)) {
        struct.resetBalanceAfterRebuy = iprot.readBool();
        struct.setResetBalanceAfterRebuyIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

