# FROM gcr.io/mq-legacy-games/atlassian-default-image-4-customized AS build
# FROM maven:3.9-amazoncorretto-8 AS build
# FROM maven:3.9-eclipse-temurin-8-alpine AS build
FROM mq-gs-base:latest AS build

# FROM maven:3.9-amazoncorretto-8-alpine AS build

WORKDIR /app

COPY --chown=nobody:nogroup . .

RUN ./build-all-modules.sh

RUN ./game-server/build/live/build-mqb2-live.sh