package com.dgphoenix.casino.common.util.system;

/**
 * Created by quant on 19.11.15.
 */
public enum Metric {
    CPU,
    MEMORY,
    BASE_GAME_CACHE_SIZE,
    DB_LINK_CACHE_SIZE,
    EXTERNAL_GAME_IDS_CACHE_SIZE,
    JACK_POT_CACHE_SIZE,
    TRANSACTION_DATA_PERSISTER_CACHE_SIZE,

    BONUS_TRACKER_TASK_COUNT,
    DELAYED_EXECUTOR_TASK_COUNT,
    FR_BONUS_WIN_TRACKER_TASK_COUNT,
    FR_BONUS_NOTIFY_TRACKER_TASK_COUNT,
    LOGOUT_TRACKER_TASK_COUNT,
    PAYMENT_TRANSACTION_TRACKER_TASK_COUNT,
    PING_SESSION_CACHE_TASK_COUNT,
    WALLET_TRACKER_TASK_COUNT,
    ALERT_DISPATCHER_READY_TO_SEND_ALERTS,

    ACCOUNT_DISTRIBUTED_LOCK_MANAGER_LOCAL_LOCKS_COUNT,
    ACCOUNT_DISTRIBUTED_LOCK_MANAGER_SERVER_LOCKS_COUNT,
    DISTRIBUTED_LOCK_MANAGER_LOCAL_LOCKS_COUNT,
    DISTRIBUTED_LOCK_MANAGER_SERVER_LOCKS_COUNT,
    DOMAIN_SESSION_ACTIVE_TRANSACTIONS_COUNT,
    GAME_DATA_MANAGER_LOCKS_SIZE,
    HTTP_CLIENT_CONNECTIONS_COUNT,
    SHUTDOWN_FILTER_ACTIVE_THREADS_COUNT;

    private int logPeriodMillis = 5000;

    Metric() {
    }

    Metric(int logPeriodMillis) {
        this.logPeriodMillis = logPeriodMillis;
    }

    public int getLogPeriodMillis() {
        return logPeriodMillis;
    }
}
