common_strings = {
    "": "",
    "<< Click here to details >>": "<< Klik hier voor details >>",
    "{} credits": "{} credits",
    "{} credits / {}": "{} credits / {}",
    "{} free spins remain": "{} Free spins over",
    "{} Free spins remain": "{} Free spins over",
    "{} Bet:": "{} Inzet:",
    "{} Win:": "{} Winst:",
    "Bet:": "Inzet:",
    "Bet: {}": "Inzet: {}",
    "Cascade": "Cascade",
    "Cascade (FS)": "Cascade (Free Spins)",
    "Coin: {}": "Munt: {}",
    "DoubleUp": "Dubbelop",
    "Double Up": "Dubbelop",
    "Free Spin": "Free Spin",
    "Free Spins": "Free Spins",
    "Free Spins remain: {}": "Free spins over: {}",
    "Game End": "Speleinde",
    "Line {}: {} credits": "Lijn {}: {} credits",
    "Line {}: {}": "Lijn {}: {}",
    "Multiplier: {}": "Vermenigvuldiger: {}",
    "Multiplier: {}x": "Vermenigvuldiger: {}x",
    "Scatter": "Scatter",
    "Scatter Win: {}": "Scatterwinst: {}",
    "Statistics of Play": "Spelstatistieken",
    "Statistics of Play ({})": "Spelstatistieken ({})",
    "Total Bet: {}": "Totale Inzet: {}",
    "Total Win: {}": "Totale Winst: {}",
    "Win: {}": "Winst: {}",
    "Buy Free Spins": "Koop Free Spins",
    "Buy Free Spin": "Koop Free Spins",
    "Buy Free Spin Respin": "Koop Free Spin Respin",
    "Chain {} of {}": "Keten {} van {}",
    "+{} free spins": "+{} free spins",
    "{} credits line {}": "{} credits lijn {}",
    "+ {} extra Free Spins": "+ {} extra Free Spins",
    "Bet: {} Coin: {} Win: {}": "Inzet: {} Munt: {} Winst: {}",
    "Bet: {}  Coin: {}  Win: {}": "Inzet: {} Munt: {} Winst: {}",
    "Coin: {}  Bet: {}  Win: {}": "Munt: {} Inzet: {} Winst: {}",
    "Free Spin added: {}": "Free Spin toegevoegd: {}",
    "Free Spin is triggered": "Free Spin is geactiveerd",
    "Line {} of {}": "Lijn {} van {}",
    "Multiplier + {}": "Vermenigvuldiger + {}",
    "Scatter win {} credits": "Scatterwinst {} credits",
    "Loading": "Laden",
    "100% Bet:": "100% Inzet:",
    "100% Win:": "100% Winst:",
    "50% Bet:": "50% Inzet:",
    "50% Win:": "50% Winst:",
    "Player won": "Speler won",
    "Player WON": "Speler WON",
    "Player lost": "Speler verloor",
    "Player LOST": "Speler VERLOOR",
    "Player LOSE": "Speler VERLIEST",
    "Connecting to server...": "Verbinden met de server...",
    "Loading base...": "Basis laden...",
    "Loading images": "Afbeeldingen laden",

    "Respin": "Re-spin",
    "Respin is triggered": "Re-spin is geactiveerd",
    "Respin Multiplier: {}": "Re-spin Vermenigvuldiger: {}",
    "Instant Cash Prize: {} credits": "Directe Cash Prijs: {} credits",
    "{} credits for Scatters": "{} credits voor Scatters"
};