common_strings = {
    "": "",
    "<< Click here to details >>": "<< Klicka här för detaljer >>",
    "{} credits": "{} krediter",
    "{} credits / {}": "{} krediter / {}",
    "{} free spins remain": "Återstående Free Spins {}",
    "{} Free spins remain": "Återstående Free Spins {}",
    "{} free spins remain, multiplier: {}": "Återstående Free Spins {}, Small Jackpot: {}",
    "100% Bet:": "Insats 100%:",
    "{} Bet:": "Insats {}:",
    "100% Win:": "Vinst 100%:",
    "{} Win:": "Vinst {}:",
    "50% Bet:": "Insats 50%:",
    "50% Win:": "Vinst 50%:",
    "Active Lines: {}": "Aktiva linjer: {}",
    " additional wilds": " Ytterligare wilds",
    "Bet:": "Insats:",
    "Bet: {}": "Insats: {}",
    "BIG Mega Win": "Stor Megavinst",
    "Bonus Payout": "Bonusutbetalning",
    "Bonus Payout: {}": "Bonusutbetalning: {}",
    "Bonus Payout: {} / {}": "Bonusutbetalning: {} / {}",
    "Bonus Payout: {} credits / {}": "Bonusutbetalning: {} krediter / {}",
    "Bonus round": "Bonusrunda",
    "Bonus Round": "Bonusrunda",
    "Bonus Win: {}": "Bonusvinst: {}",
    "Burn": "Bränn",
    "Cascade": "Kaskad",
    "Cascade (FS)": "Kaskad (FS)",
    "Choice": "Val",
    "Choice: {}": "Val: {}",
    "CHOICE": "VAL",
    "Click Me": "Klicka på mig",
    "Click Me Payout:": "Klicka på mig-utbetalning:",
    "Click Me Payout: {}": "Klicka på mig-utbetalning: {}",
    "Click Me Payout: {} / {}": "Klicka på mig-utbetalning: {} / {}",
    "Coin: {}": "Mynt: {}",
    "COLLAPSE": "KOLLAPS",
    "Collapse": "Kollaps",
    "Collapse Payout: {}": "Kollaps-utbetalning: {}",
    "Collapse win: {}": "Kollapsvinst: {}",
    "Collapse Win: {}": "Kollapsvinst: {}",
    "Connecting to server...": "Ansluter till server...",
    "Continuation": "Fortsättning",
    "Credits": "Krediter",
    "Current value: {}": "Nuvarande värde: {}",
    "Current Win: {}": "Nuvarande vinst: {}",
    "Double": "Dubbel",
    "DoubleUp": "Dubblera",
    "Double Up": "Dubblera",
    "End of Free Spins": "Slut på Free Spins",
    "ERROR": "FEL",
    "Explode": "Explodera",
    "Explode (FS)": "Explodera (FS)",
    "First step": "Första steget",
    "Free Spins remain: {}": "Återstående Free Spins: {}",
    "Free spins win: {}": "Free spins-vinst: {}",
    "Free Spins total: {}": "Totalt antal Free Spins: {}",
    "FS Meter: {}": "FS-mätare: {}",
    "Game Continuation": "Spelfortsättning",
    "Game End": "Spelavslut",
    "Game Not Finished": "Spel ej avslutat",
    "Game Start": "Spelstart",
    "Hit": "Träff",
    "Hold cards": "Behåll kort",
    "Information not found": "Informationen hittades inte",
    "Instant": "Omedelbar",
    "Instant payout: {}": "Omedelbar utbetalning: {}",
    "Insurance": "Försäkring",
    "Jackpot": "Jackpott",
    "Jackpot: {}": "Jackpott: {}",
    "Jackpot Win: {}": "Jackpottvinst: {}",
    "Large Jackpot": "Stor Jackpott",
    "Large Jackpot win: {}": "Stor Jackpottvinst: {}",
    "Large Scatter": "Stor Scatter",
    "Large Scatter win: {}": "Stor Scattervinst: {}",
    "Left": "Vänster",
    "Line {}: {}": "Linje {}: {}",
    "Line {}: {} credits": "Linje {}: {} krediter",
    "{} credits line {}": "{} krediter linje {}",
    "Line {}: add free spins": "Linje {}: Lägg till free spins",
    "Line {} of {}": "Line {} av {}",
    "Loading": "Laddar",
    "Loading base...": "Laddar bas...",
    "Loading images": "Laddar bilder",
    "LOSE": "FÖRLORA",
    "Middle Jackpot": "Mellan Jackpott",
    "Middle Jackpot win: {}": "Mellan Jackpottvinst: {}",
    "Middle Scatter": "Mellan Scatter",
    "Middle Scatter win: {}": "Mellan Scattervinst: {}",
    "Money Wheel": "Pengahjul",
    "Multiplier: {}": "Multiplikator: {}",
    "Multiplier: {}x": "Multiplikator: {}x",
    "Next Draw": "Nästa dragning",
    "Not Finished": "Inte slutförd",
    "Payout: {}": "Utbetalning: {}",
    "Payout: {} credits / {}": "Utbetalning: {} krediter / {}",
    "Payout Wheel {}: {}": "Utbetalningshjul {}: {}",
    "PLAYER": "SPELARE",
    "Place Bet": "Placera insats",
    "Place Bet (Jackpot)": "Placera insats (Jackpott)",
    "Place Bet (Super)": "Placera insats (Super)",
    "Place Bet (Wild)": "Placera insats (Wild)",
    "Player won": "Spelare vann",
    "Player WIN": "Spelare VINNER",
    "Player WON": "Spelare VANN",
    "Player lost": "Spelare förlorade",
    "Player LOST": "Spelare FÖRLORARDE",
    "Player LOSE": "Spelare FÖRLORAR",
    "Possible Credits": "Möjliga krediter",
    "Possible win": "Möjlig vinst",
    "Possible win:": "Möjlig vinst:",
    "Potential Win: {}": "Möjlig Vinst: {}",
    "Respin": "Återsnurr",
    "ReSpin": "Återsnurr",
    "Respin Free": "Återsnurr dree",
    "Respin Main": "Återsnurr främst",
    "ReSpin multiplier: {}x": "Återsnurr-multiplikator: {}x",
    "Respins remain: {}": "Återstående återsnurrar: {}",
    "RESULT": "RESULTAT",
    "Result": "Resultat",
    "Result:": "Resultat:",
    "Right": "Höger",
    "Round Bet: {} credits": "Rundans insats: {} krediter",
    "Round Complete": "Runda avklarad",
    "Round Win: {} credits": "Rundas vinst: {} krediter",
    "Scatter Payout: {}": "Scatter-utbetalning: {}",
    "Scatter Win: {}": "Scattervinst: {}",
    "Second step": "Andra steg",
    "Small Jackpot": "Liten Jackpott",
    "Small Jackpot win: {}": "Liten Jackpottvinst: {}",
    "Small Scatter": "Liten Scatter",
    "Small Scatter win: {}": "Liten Scattervinst: {}",
    "Split": "Dela",
    "Stand": "Stanna",
    "Statistics": "Statistik",
    "Statistics of Play": "Spelstatistik",
    "Statistics of Play ({})": "Spelstatistik ({})",
    "Super Payout": "Superutbetalning",
    "Surrender": "Ge upp",
    "Total Bet: {}": "Totalinsats: {}",
    "Total Bet: {} credits": "Totalinsats: {} krediter",
    "Total FreeSpins Payout": "Total FreeSpins-utbetalning",
    "Total Win: {}": "Total vinst: {}",
    "Total Win: {} credits": "Total vinst: {} krediter",
    "Unj win: ": "Unj-vinst: ",
    "Wild Reel": "Wild-hjul",
    "Win": "Vinst",
    "WIN": "VINST",
    "Win in credits": "VInst i krediter",
    "Win Jackpot: {}": "Vinst Jackpott: {}",
    "Win: {}": "Vinst: {}",
    "Wheel": "Hjul",
    "Buy Free Spins": "Köp Free Spins",
    "Buy Free Spin": "Köp Free Spin",
    "Buy Free Spin Respin": "Köp Free Spin-Återsnurr",
    "Free Spin Respin": "Free Spin-återsnurr",
    "Main Respin": "Huvud-återsnurr",
    "Sticky Multiplier: {}": "Sticky Multiplikator: {}",
    "Chain {} of {}": "Kedja {} av {}",
    "Vine Win: {}": "Klätterväxtvinst: {}",
    "<< Show Vine Info >>": "<< Visa Klätterväxt-info >>",
    "{}. Before: {}, After: {}": "{} Innan: {}, Efter: {}",
    " Final Win: {}x{} = {}": "Sista vinst: {}x{} = {}",
    "Grid progress: {}": "Rutnätsframsteg: {}",
    "Buy Price: {}": "Köpkostnad: {}",
    "Hero feature win: {}": "Hjälte-funktionvinst: {}",
    "Fan girl win: {}": "Fan girl-vinst: {}",
    "Coin: {} Bet: {} Win: {}": "Mynt: {} Insats: {} Vinst: {}",
    "CUP": "Cup",
    "TREE": "Träd",
    "Wheel {}:  -> next wheel": "Hjul {} {}: -> nästa hjul",

    "Dealer's Hand": "Dealerns hand",
    "Double Bet: {}": "Dubbel insats: {}",
    "Double Bet: {}, win: {}": "Dubbel insats: {}, vinst: {}",
    "Bet: {}, win: {}": "Insats: {}, Vinst: {}",
    "Insurance -> Bet: {}, win: {}": "Försäkring -> Insats: {}, vinst: {}",
    "Insurance Bet: {}": "Försäkringinsats: {}",
    "Player's Hand #{}": "Spelarens hand #{}",
    "Free Spin": "Free Spin"
};