common_strings = {
    "": "",
    "<< Click here to details >>": "<< Clicca qui per i dettagli >>",
    "{} credits": "{} crediti",
    "{} credits / {}": "{} crediti / {}",
    "{} Free spins": "{} giri gratis",
    "{} free spins remain": "{} giri gratis rimanenti",
    "{} Free spins remain": "{} giri gratis rimanenti",
    "{} free spins remain, multiplier: {}": "{} giri gratis rimanenti, moltiplicatore: {}",
    "100% Bet:": "Puntata 100%:",
    "{} Bet:": "Puntata {}:",
    "100% Win:": "Vincita 100%:",
    "{} Win:": "Vincita {}:",
    "50% Bet:": "Puntata 50%:",
    "50% Win:": "Vincita 50%:",
    "Active Lines: {}": "Linee Attive: {}",
    "Bet:": "Puntata:",
    "Bet: {}": "Puntata: {}",
    "Bonus": "Bonus",
    "Bonus Payout": "Vincita Bonus",
    "Bonus Payout:": "Vincita Bonus:",
    "Bonus Payout: {}": "Vincita Bonus: {}",
    "Bonus Payout: {} / {}": "Vincita Bonus: {} / {}",
    "Bonus Payout: {} credits / {}": "Vincita Bonus: {} crediti / {}",
    "Bonus round": "Round Bonus",
    "Bonus Round": "Round Bonus",
    "Bonus Win: {}": "Vincita Bonus: {}",
    "Burn": "Brucia",
    "Cascade": "Cascata",
    "Cascade (FS)": "Cascata (FS)",
    "Choice": "Scelta",
    "Choice: {}": "Scelta: {}",
    "CHOICE": "SCELTA",
    "Click Me": "Cliccami",
    "Click Me Payout:": "Vincita Cliccami:",
    "Click Me Payout: {}": "Vincita Cliccami: {}",
    "Click Me Payout: {} / {}": "Vincita Cliccami: {} / {}",
    "Coin: {}": "Moneta: {}",
    "COLLAPSE": "SEPARA",
    "Collapse": "Separa",
    "Collapse Payout: {}": "Separa Vincita: {}",
    "Collapse win: {}": "Vincita Caduta: {}",
    "Collapse Win: {}": "Vincita Caduta: {}",
    "Connecting to server...": "Connessione al server…",
    "Continuation": "Continuazione",
    "Credits": "Crediti",
    "Current value: {}": "Valore attuale: {}",
    "Current Win: {}": "Vincita Attuale: {}",
    "DEALER": "BANCO",
    "Double": "Raddoppia",
    "DoubleUp": "Raddoppia",
    "Double Up": "Raddoppia",
    "End of Free Spins": "Fine dei Giri Gratis",
    "ERROR": "ERRORE",
    "Explode": "Esplosione",
    "Explode (FS)": "Esplosione (FS)",
    "First step": "Primo passo",
    "Free Spin": "Giro Gratis",
    "Free Spins": "Giri Gratis",
    "Free Spins, Wilds": "Giri Gratis, Jolly",
    "Free Spins remain: {}": "Giri gratis rimanenti: {}",
    "Free spins win: {}": "Giri gratis vinti: {}",
    "Game Continuation": "Continua Gioco",
    "Game End": "Fine Gioco",
    "Game Not Finished": "Gioco non terminato",
    "Game Start": "Inizio Gioco",
    "Hit": "Carta",
    "Hold cards": "Tieni carte",
    "Information not found": "Informazione non trovata",
    "Instant": "Immediato",
    "Instant payout: {}": "Vincita immediata: {}",
    "Insurance": "Assicurazione",
    "Jackpot": "Montepremi",
    "Jackpot: {}": "Montepremi: {}",
    "Jackpot Win: {}": "Vincita Montepremi: {}",
    "Large Jackpot": "Montepremi Grande",
    "Large Jackpot win: {}": "Vincita Montepremi Grande: {}",
    "Large Scatter": "Grande Scatter",
    "Large Scatter win: {}": "Vincita Scatter Grande: {}",
    "Left": "Sinistra",
    "Line {}: {}": "Linea {}: {}",
    "Line {}: {} credits": "Linea {}: {} crediti",
    "Line {}: add free spins": "Linea {}: aggiungi giri gratis",
    "Loading": "Caricamento",
    "Loading base...": "Caricamento base…",
    "Loading images": "Caricamento immagini",
    "LOSE": "PERDI",
    "Middle Jackpot": "Montepremi Medio",
    "Middle Jackpot win: {}": "Vincita Montepremi Medio: {}",
    "Middle Scatter": "Medio Scatter",
    "Middle Scatter win: {}": "Vincita Scatter Medio: {}",
    "Money Wheel": "Money Wheel",
    "Multiplier: {}": "Moltiplicatore: {}",
    "Multiplier: {}x": "Moltiplicatore: {}x",
    "Next Draw": "Prossima distribuzione",
    "Not Finished": "Non terminato",
    "Payout: {}": "Vincita: {}",
    "Payout: {} credits / {}": "Vincita: {} crediti / {}",
    "PLAYER": "GIOCATORE",
    "Place Bet": "Effettua Puntata",
    "Place Bet (Jackpot)": "Effettua Puntata (Montepremi)",
    "Place Bet (Super)": "Effettua Puntata (Super)",
    "Place Bet (Wild)": "Effettua Puntata (Jolly)",
    "Player won": "Giocatore vince",
    "Player WON": "Giocatore VINCE",
    "Player lost": "Giocatore perde",
    "Player LOST": "Giocatore PERDE",
    "Player LOSE": "Giocatore PERDE",
    "Possible Credits": "Crediti Potenziali",
    "Possible win": "Vincita Potenziale",
    "Possible win:": "Vincita Potenziale:",
    "Potential Win: {}": "Vincita Potenziale: {}",
    "Respin": "Rigira",
    "ReSpin": "Rigira",
    "ReSpin multiplier: {}x": "Moltiplicatore RiGira: {}x",
    "RESULT": "RISULTATO",
    "Result": "Risultato",
    "Result:": "Risultato:",
    "Right": "Destra",
    "Round Bet: {} credits": "Puntata Round: {} crediti",
    "Round Complete": "Round Completato",
    "Round Win: {} credits": "Vincita Round: {}",
    "Scatter": "Scatter",
    "Scatter Payout: {}": "Vincita Scatter: {}",
    "Scatter Win: {}": "Vinci con Scatter: {}",
    "Second step": "Secondo passo",
    "Small Jackpot": "Montepremi Piccolo",
    "Small Jackpot win: {}": "Vincita Montepremi Piccolo: {}",
    "Small Scatter": "Piccolo Scatter",
    "Small Scatter win: {}": "Vincita Scatter Piccolo: {}",
    "Split": "Dividi",
    "Stand": "Stai",
    "Statistics": "Statistiche",
    "Statistics of Play": "Statistiche del Gioco",
    "Statistics of Play ({})": "Statistiche del Gioco ({})",
    "Super Payout": "Vincita Super",
    "Surrender": "Abbandona",
    "Total Bet: {}": "Puntata Totale: {}",
    "Total Bet: {} credits": "Totale Puntata: {} crediti",
    "Total FreeSpins Payout": "Totale Vincita Giri Gratis",
    "Total Win: {}": "Vincita Totale: {}",
    "Total Win: {} credits": "Totale Vincita: {} crediti",
    "Unj win: ": "Vincita Unj: ",
    "Wild": "Jolly",
    "Wild: ": "Jolly: ",
    "Wilds": "Jolly",
    "Wild Reel": "Ruota Jolly",
    "Win": "Vinci",
    "WIN": "VINCI",
    "Win in credits": "Vincita in crediti",
    "Win Jackpot: {}": "Vincita Montepremi: {}",
    "Win: {}": "Vinci: {}",
    "Wheel": "Ruota",
    "Buy Free Spins": "Acquista giri gratis",
    "Buy Free Spin": "Acquista giro gratis",
    "Buy Free Spin Respin": "Acquista respin dei giri gratis",
    "Free Spin Respin": "Respin dei giri gratis",
    "Main Respin": "Respin standard",
    "Respin Main": "Respin standard",
    "Sticky Multiplier: {}": "Moltiplicatore appiccicoso: {}",
    "Chain {} of {}": "Catena {} di {}",
    "Vine Win: {}": "Vincita della funzione Vite: {}",
    "<< Show Vine Info >>": "<< Mostra le informazioni sulla funzione Vite >>",
    "{}. Before: {}, After: {}": "{} Prima: {}, Dopo: {}",
    " Count of lose: {}, multiplier: {}": "Numero di perdite: {}, moltiplicatore: {}",
    " Final Win: {}x{} = {}": "Vincita finale: {}x{} = {}",
    "Grid progress: {}": "Progresso sulla griglia: {}",
    "Buy Price: {}": "Prezzo d’acquisto: {}",
    "Hero feature win: {}": "Vincita della funzione Eroe: {}",
    "Fan girl win: {}": "Vincita della fan: {}",
    "+{} free spins": "+{} giri gratis",
    "Coin: {} Bet: {} Win: {}": "Moneta: {} Puntata: {} Vincita: {}",
    "Bet: {}  Coin: {}  Win: {}": "Puntata: {}  Moneta: {} Vincita: {}",

    "Dealer's Hand": "Mano del Banco",
    "Double Bet: {}": "Puntata Doppia: {}",
    "Double Bet: {}, win: {}": "Puntata Doppia: {}, vinci: {}",
    "Bet: {}, win: {}": "Puntata: {}, vinci: {}",
    "Insurance -> Bet: {}, win: {}": "Assicurazione -> Puntata: {}, vinci: {}",
    "Insurance Bet: {}": "Puntata Assicurazione: {}",
    "Player's Hand #{}": "Mano Giocatore #{}",

    "Respin is triggered": "Il Respin \u00e8 innescato",
    "Respin Multiplier: {}": "Moltiplicatore del Respin: {}",
    "Instant Cash Prize: {} credits": "Premio istantaneo in denaro: {} crediti",
    "{} credits for Scatters": "{} crediti per gli Scatter"
};