var common_strings = {
    "": "",
    "<< Click here to details >>": "<<Haz clic aquí para obtener más detalles>>",
    "{} credits": "{} créditos",
    "{} credits / {}": "{} créditos / {}",
    "{} Free spins": "{} giros gratis",
    "Free Spins remain: {}": "{} giros gratis",
    "{} free spins remain": "{} giros gratis restantes",
    "{} Free spins remain": "{} giros gratis restantes",
    "{} free spins remain, multiplier": "{} giros gratis restantes, multiplicador: {}",
    "50% Bet": "50% de apuesta",
    "50% Bet:": "50% de apuesta:",
    "50% Win": "50% de premio",
    "50% Win:": "50% de premio:",
    "100% Bet": "100% de apuesta",
    "100% Bet:": "100% de apuesta:",
    "100% Win": "100% de premio",
    "100% Win:": "100% de premio:",
    "Active Lines: {}": "Líneas activas: {}",
    "Active Lines": "Líneas activas",
    "Bet": "Apuesta",
    "Bet:": "Apuesta:",
    "Bet: {}": "Apuesta: {}",
    "{} Bet": "{} de apuesta",
    "{} Bet:": "{} de apuesta:",
    "{} Win:": "{} de premio:",
    "{} Win": "{} de premio",
    "Bonus": "Bono",
    "Bonus Payout": "Pago de bono",
    "Bonus Payout:": "Pago de bono:",
    "Bonus Payout: {}": "Pago de bono: {}",
    "Bonus Payout: {} / {}": "Pago de bono: {} / {}",
    "Bonus Payout: {} credits / {}": "Pago de bono: {} / {} créditos / {}",
    "Bonus round": "Ronda de bono",
    "Bonus Round": "Ronda de bono",
    "Bonus Win": "Premio de bono",
    "Burn": "Burn",
    "Cascade": "Cascada",
    "Cascade (FS)": "Cascada (giros gratis)",
    "Choice": "Elección",
    "Choice: {}": "Elección: {}",
    "CHOICE": "ELECCIÓN",
    "Click Me": "Haz clic sobre mí",
    "Click Me Payout": "Pago de Haz clic sobre mí",
    "Click Me Payout: {}": "Pago de Haz clic sobre mí: {}",
    "Click Me Payout: {} / {}": "Pago de Haz clic sobre mí: {} / {}",
    "Coin": "Moneda",
    "COIN": "MONEDA",
    "Coin: {}": "Moneda: {}",
    "COLLAPSE": "COLAPSO",
    "Collapse": "Colapso",
    "Collapse Payout": "Pago de Colapso",
    "Collapse Payout: {}": "Pago de Colapso: {}",
    "Collapse win": "Premio de Colapso",
    "Collapse Win": "Premio de Colapso",
    "Collapse Win: {}": "Premio de Colapso: {}",
    "Connecting to server...": "Conectando con el servidor...",
    "Continuation": "Continuación",
    "Credits": "Créditos",
    "Current value": "Valor actual",
    "Current Win": "Premio actual",
    "DEALER": "CRUPIER",
    "Double": "Doblar",
    "DoubleUp": "Doblar",
    "Double Up": "Doblar",
    "End of Free Spins": "Fin de los giros gratis",
    "ERROR": "ERROR",
    "Explode": "Explota",
    "Explode (FS)": "Explota (giros gratis)",
    "First step": "Primer paso",
    "Free Spin": "Giro gratis",
    "Free Spins": "Giros gratis",
    "Free Spins, Wilds": "Giros gratis, comodines",
    "Free Spins remain": "Giros gratis restantes",
    "Free spins win": "Premio de giros gratis",
    "Free spins win: {}": "Premio de giros gratis: {}",
    "Free Spins win: {}": "Premio de giros gratis: {}",
    "Game Continuation": "Continuación del juego",
    "Game End": "Fin del juego",
    "Game Not Finished": "Juego no terminado",
    "Game Start": "Inicio de juego",
    "Hit": "Pedir carta",
    "Hold cards": "Plantarse",
    "Information not found": "No se ha encontrado la información",
    "Instant": "Instantáneo",
    "Instant payout": "Pago instantáneo",
    "Insurance": "Seguro",
    "Jackpot": "Jackpot",
    "Jackpot: {}": "Jackpot: {}",
    "Jackpot Win": "Premio de jackpot",
    "Large Jackpot": "Jackpot grande",
    "Large Jackpot win": "Premio de jackpot grande",
    "Large Scatter": "Scatter grande",
    "Large Scatter win": "Premio de scatter grande",
    "Left": "Izquierda",
    "Line {}": "Línea {}",
    "Line {}: {}": "Línea {}: {}",
    "Line {} of {}": "Línea {} de {}",
    "Line {}: {} credits": "Línea {}: {} créditos",
    "{} credits line {}": "{} créditos línea {}",
    "Line {}: add free spins": "Línea {}: Añadir giros libres",
    "Loading": "Cargando",
    "Loading base...": "Cargando base...",
    "Loading images": "Cargando imágenes",
    "LOSE": "HAS PERDIDO",
    "Middle Jackpot": "Jackpot medio",
    "Middle Jackpot win": "Premio de jackpot medio",
    "Middle Scatter": "Scatter medio",
    "Middle Scatter win": "Premio de scatter medio",
    "Money Wheel": "Ruleta de dinero",
    "Multiplier: {}": "Multiplicador: {}",
    "Multiplier": "Multiplicador: {}x",
    "Next Draw": "Siguiente sorteo",
    "Not Finished": "Sin finalizar",
    "Payout: {}": "Pago: {}",
    "Payout: {} credits / {}": "Pago: {} créditos / {}",
    "PLAYER": "JUGADOR",
    "Place Bet": "Realizar apuesta",
    "Place Bet (Jackpot)": "Realizar apuesta (jackpot)",
    "Place Bet (Super)": "Realizar apuesta (súper)",
    "Place Bet (Wild)": "Realizar apuesta (comodín)",
    "Player won": "El jugador ha ganado",
    "Player WON": "El jugador ha GANADO",
    "Player WIN": "El jugador ha GANADO",
    "Player lost": "el jugador ha perdido",
    "Player LOST": "El jugador HA PERDIDO",
    "Player LOSE": "El jugador HA PERDIDO",
    "Possible Credits": "Créditos posibles",
    "Possible win": "Premio posible",
    "Possible win:": "Premio posible:",
    "Potential Win": "Premio potencial",
    "Respin": "Regiro",
    "ReSpin": "Regiro",
    "ReSpin multiplier": "Multiplicador regiro",
    "RESULT": "RESULTADO",
    "Result": "Resultado",
    "Result:": "Resultado:",
    "Right": "Derecha",
    "Round Bet": "Apuesta de ronda",
    "Round Complete": "Ronda completa",
    "Round Win": "Premio de ronda",
    "Scatter": "Scatter",
    "Scatter Payout": "Pago de scatter",
    "Scatter Win": "Premio de scatter",
    "Scatter win": "Premio de scatter",
    "Second step": "Segundo paso",
    "Small Jackpot": "ackpot pequeño",
    "Small Jackpot win": "Premio de jackpot pequeño",
    "Small Scatter": "Scatter pequeño",
    "Small Scatter win": "Premio de scatter pequeño",
    "Split": "Dividir",
    "Stand": "Stand",
    "Statistics": "Estadísticas",
    "Statistics of Play": "Estadísticas del juego",
    "Statistics of Play ({})": "Estadísticas del juego ({})",
    "Super Payout": "Súper Pago",
    "Surrender": "Rendirse",
    "Total Bet": "Apuesta total",
    "Total Bet: {}": "Apuesta total: {}",
    "Total Bet: {} credits": "Apuesta total: {} créditos",
    "Total FreeSpins Payout": "Pago total de giros gratis",
    "Total Win": "Premio total",
    "Total Win: {}": "Premio total: {}",
    "Total Win: {} credits": "Premio total: {} créditos",
    "Unj win": "Premio de jackpot universal",
    "Wild": "Comodín",
    "Wild:": "Comodín:",
    "Wild: ": "Comodín: ",
    "Wilds": "Comodines",
    "Wild Reel": "Rodillo de comodín",
    "Win": "Premio",
    "WIN": "PREMIO",
    "Win in credits": "Premio en créditos",
    "Win Jackpot": "Jackpot de premio",
    "Win: {}": "Premio: {}",
    "Wheel": "Ruleta",
    "Buy Free Spins": "Comprar giros gratis",
    "Buy Free Spin": "Comprar giro gratis",
    "Buy Free Spin Respin": "Regiro Comprar giro gratis",
    "Free Spin Respin": "Regiro Giro Gratis",
    "Respin Free": "Regiro Giro Gratis",
    "Main Respin": "Regiro principal",
    "Respin Main": "Regiro principal",
    "Free Spin Wilds Count": "Cuenta de comodines de giros gratis",
    "Bomb Counter": "Cuenta de bombas",
    "Bomb Counter: {}": "Cuenta de bombas: {}",
    // game strings
    "+{} free spins(WinMeter: {})": "+{} giros gratis(ContadorGanancia: {})",
    "+{} free spins": "+{} giros gratis",
    "WinMeter: {}": "ContadorGanancia: {}",
    "Chain {} of {}": "Cadena {} de {}",
    "Elf": "Elfo",
    "Goblin": "Duende",
    "Wilds remain {}, reels: {}": "Quedan comodines {}, rodillos: {}",
    "In Museum": "En museo",
    "Get Him": "Cógelo",
    "Vase": "Florero",
    "Painting": "Pintura",
    "Statue": "Estatua",
    "Bonus Payout: {} free spins": "Pago de bonos: {} giros gratis",
    "Free Spin multiplier: {}x": "Multiplicador giros gratis: {}x",
    "Numbers chosen: {}": "Números elegidos: {}",
    "Number hit: {}": "Número aciertos: {}",
    "Roulette Bonus": "Bono ruleta",
    "Slots Bonus": "Bono tragaperras",
    "Wheel Bonus": "Bono rueda",
    "Pots of Gold": "Potes de oro",
    "Mega Symbol": "Mega símbolo",
    "Golden Bonus": "Bono dorado",
    "Creativity:": "Creatividad:",
    "Freshness:": "Frescura:",
    "Lock Wilds": "Comodines bloqueados",
    "Presentation:": "Presentación:",
    "Taste:": "Gusto:",
    "Total Bonus Round Win": "Ganancia ronda bono total",
    "<< Show Black Hole Info >>": "<< Mostrar información agujero negro >>",
    "<< Show Plant Info >>": "<< Mostrar información planta >>",
    "Air Action": "Acción aire",
    "Air Payout: {}": "Pago aire: {}",
    "Black Hole Win: {}": "Ganancia agujero negro: {}",
    "Cosmos": "Cosmos",
    "Earth Action": "Acción tierra",
    "Earth Payout: {}": "Pago tierra: {}",
    "Fire Action": "Acción fuego",
    "Fire Payout: {}": "Pago fuego: {}",
    "Nature": "Naturaleza",
    "Plant Win: {}": "Ganancia pago: {}",
    "Water Action": "Acción agua",
    "Water Payout: {}": "Pago agua: {}",
    "Select Mode": "Seleccionar modo",
    "Good": "Bueno",
    "GOOD": "BUENO",
    "Bad": "Malo",
    "BAD": "MALO",
    "BOTH": "AMBOS",
    "Add {} Free Spins": "Añadir {} giros libres",
    "Selected side: {}": "Lado seleccionado: {}",
    "Wheel win:": "Ganancia rueda:",
    "Candy Cane": "Bastoncitos de caramelo",
    "Caramel Chew": "Caramelo masticable",
    "Chocolate Square": "Pastilla de chocolate",
    "Cotton Candy": "Algodón de azúcar",
    "Feature({}) payout: {}": "Función({}) paga: {}",
    "Game score: {}": "Puntuación juego: {}",
    "Gumball Jawbreaker": "Caramelo de chicle",
    "Gumdrop": "Gominolas",
    "Jelly Beans": "Caramelos de goma",
    "Level score: {}": "Puntuación nivel: {}",
    "Lollipop": "Piruleta",
    "Peanut Butter Cup": "Pastel de mantequilla de cacahuete",
    "Statistics(Level: {})": "Estadísticas(Nivel: {})",
    "White Chocolate": "Chocolate blanco",
    "{} FS remain, Multiplier: {}": "{} Queda FS, Multiplicador: {}",
    "Chosen dancer:": "Bailarín escogido:",
    "Is Wild:": "Es comodín:",
    "Is Wild: ": "Es comodín: ",
    "Wild multiplier: {}x": "Comodín multiplicador: {}x",
    "Multiplier: {}x": "Multiplicador: {}x",
    "Dealer's Hand": "Mano del crupier",
    "Double Bet: {}": "Apuesta doble: {}",
    "Double Bet: {}, win: {}": "Apuesta doble: {}, premio: {}",
    "Bet: {}, win: {}": "Apuesta: {}, premio: {}",
    "Insurance -> Bet: {}, win: {}": "Seguro -> Apuesta: {}, premio: {}",
    "Insurance Bet: {}": "Apuesta de seguro: {}",
    "Player's Hand #{}": "Mano del jugador #{}",
    "Badges: {}": "Insignias: {}",
    "Play {} of {}": "Juego {} de {}",
    "Coin: {} Bonus Win: {}": "Moneda: {} Ganancia bono: {}",
    "Coin: {}  Bonus Win: {}": "Moneda: {} Ganancia bono: {}",
    "Payout Wheel {}: {}": "Pago rueda {}: {}",
    "Wheel {}:  -> next wheel": "Rueda {}: -> próxima rueda",
    "Cluster {} of {}, {}": "Grupo {} de {}, {}",
    "Cluster {} of {}, {} credits": "Grupo {} de {}, {} créditos",
    "trail advances": "avances camino",
    "removing golden wild": "eliminando comodín dorado",
    "shuffles symbols": "baraja símbolos",
    "No winning clusters": "No grupos ganadores",
    "Level Up Won: {}": "Subir de nivel ganó: {}",
    "Level Up Trail: {}/{}": "Camino subir de nivel: {}/{}",
    "Game Score: {}": "Puntuación juego: {}",
    "Level Score: {}": "Puntuación nivel: {}",
    "Level: {}": "Nivel: {}",
    "{} free spins": "{} giros gratis",
    "Free Spins total: {}": "Giros Gratis total: {}",
    "Coin: {} Bet: {} Win: {}": "Moneda: {} Apuesta: {} Ganancia: {}",
    "Bet: {}  Coin: {}  Win: {}": "Apuesta: {} Moneda: {} Ganancia: {}",
    "Big Boss Bonus: {}": "Bono gran jefe: {}",
    "<< Zodiac wheel position >>": "<< Posición rueda Zodíaco >>",
    "Day: {}": "Día: {}",
    "credits": "créditos",
    "free spins": "Giros gratis",
    "Wheel result": "Resultad rueda",
    "Wheel result: {}": "Resultad rueda: {}",
    "wilds": " comodines",
    " wilds": " comodines",
    "{} coins -> {} credits": "{} monedas -> {} créditos",
    "{} freespins": "{} giros gratis",
    "Bets per line: {}": "Apuestas por línea: {}",
    " additional wilds": " Comodines adicionales",
    " Lion icons": " Iconos leones",
    " Dragon icons": " Iconos dragones",
    "{} wheel rotations": "{} giros rueda",
    "NONE": "NINGUNO",
    "HIDE": "ESCONDER",
    "SHOW": "MOSTRAR",
    "Smashed positions:": "Posiciones smash",
    "MODE": "Modo",
    "< lines | scatter >": "< líneas | scatter >",
    "< lines info": "< información líneas",
    "Mega Win Wheel": "Mega ganancia rueda",
    "MINI Mega Win": "Mega ganancia MINI",
    "BIG Mega Win": "Mega ganancia BONO",
    "GIANT Mega Win": "Mega ganancia GIGANTE",
    "Poker Club": "Club póker",
    "Bonus Process": "Proceso bono",
    "select:": "seleccionar:",
    "winner:": "ganador:",
    "Add Free Spins": "Añadir giros gratis",
    "Free Spin added: {}": "Añadir {} giros gratis",
    "Free Spins, Cascade": "Giros gratis, Cascada",
    "Cascade FreeSpin": "Giros gratis Cascada",
    "Hold": "Mantener",
    "Spreading wilds >": "Desplegando comodines >",
    "Crow": "Cuervo",
    "Magic Book": "Libro mágico",
    "Magic Book payout: {}": "Paga libro mágico: {}",
    "<< Battle Info >>": "<< Información batalla >>",
    "Hero block strike": "Héroe bloqueado golpear",
    "Hero blocked": "Héroe bloqueado",
    "Hero dodge": "Héroe esquivar",
    "Hero KD": "Héroe KD",
    "Hero KO blow": "Héroe golpe KO",
    "Hero strike": "Héroe golpear",
    "Hero struck": "Héroe golpeado",
    "Hero victory": "Héroe victoria",
    "Princess": "Princesa",
    "Scatter win: {}": "Ganancia scatter: {}",
    "Scatter win:": "Ganancia scatter:",
    "Scatter Win:": "Ganancia scatter:",
    "Scatter Win: {}": "Ganancia scatter: {}",
    "Villain block strike": "Villano bloqueado golpear",
    "Villain blocked": "Villano bloqueado",
    "Villain dodge": "Villano esquivar",
    "Villain KD": "Villano KD",
    "Villain KO blow": "Villano golpe KO",
    "Villain strike": "Villano golpear",
    "Villain struck": "Villano golpeado",
    "Villain victory": "Villano victoria",
    "Small Jackpot win: {}": "Ganancia jackpot pequeño: {}",
    "Middle Scatter win: {}": "Ganancia scatter medio: {}",
    "Large Scatter win: {}": "Ganancia scatter grande: {}",
    "Blue Meter ({})  Red Meter({})": "Contador azul ({})  Contador rojo({})",
    "LEFT": "IZQUIERDA",
    "RIGHT": "DERECHA",
    "Bonus win: {}": "Ganancia bono: {}",
    "Bonus Win: {}": "Ganancia bono: {}",
    "END": "FIN",
    "Jekyll Action": "Acción Jekyll",
    "Jekyll Bonus": "Bono Jekyll",
    "Hyde Action": "Acción Hyde",
    "Hyde Bonus": "Bono Hyde",
    "Hyde Win: {}": "Ganancia Hyde: {}",
    "Total bonus win: {}": "Ganancia bono total: {}",
    "Back: {}": "Volver: {}",
    "Class: {}": "Clase: {}",
    "Chalk Wild": "Comodín Chalk",
    "Gepetto Wild": "Comodín Gepeto",
    "Fairy Respin": "Giro extra hada",
    "Pinocchio Wild": "Comodín Pinocho",
    "real_boy": "muchacho_real",
    "Stage: {}": "Etapa: {}",
    "wood_boy": "muchacho_madera",
    "Wood Meter: {}": "Contador madera: {}",
    "Real Meter: {}": "Contador real: {}",
    "World: Class": "Mundo: Clase",
    "World: Shop": "Mundo: Tienda",
    "World: Stage": "Mundo: Etapa",
    "FS": "GG",
    "CUP": "VASO",
    "TREE": "ÁRBOL",
    "{}. Before: {}, After: {}": "{}. Antes: {}, Después: {}",
    "Respins remain: {}": "Giros extra restantes: {}",
    "+{} respins": "+{} giros extra",
    "+{} Free Spins": "+{} Giros gratis",
    "Free Spin Wilds Count: {}": "Giros gratis comodines: {}",
    "Sticky Multiplier: {}": "Multiplicador fijo: {}",
    "Vine Win: {}": "Premio Vid: {}",
    "<< Show Vine Info >>": "<< Mostrar información de Vid >>",
    " Count of lose: {}, multiplier: {}": "Contador de pérdidas: {}, multiplicador: {}",
    " Final Win: {}x{} = {}": "Premio final: {}x{} = {}",
    "Grid progress: {}": "Progreso de las casillas: {}",
    "Buy Price: {}": "Precio de compra: {}",
    "Hero feature win: {}": "Premio de la función Héroe: {}",
    "Fan girl win: {}": "Premio de la Admiradora: {}",
    "FS Meter: {}": "Giros gratis ganancia: {}",
    "Respin Wild Boost": "Potenciador Comodín Regiro",
    "Respin Wild Boost triggered": "Potenciador Comodín Regiro activado",
    "Stick'n'Respin": "Símbolo Fijo y Regiro",
    "Stick'n'Respin triggered": "Símbolo Fijo y Regiro activado",
    "Free Spin with Multipliers": "Giro Gratis con multiplicadores",
    "Action: {}": "Acción: {}",
    "Action: Shuffle": "Acción: Mezclar",
    "Shuffle": "Mezclar",
    "Action: Split": "Acción: Dividir",
    "Split": "Dividir",
    "Action: Clone": "Acción: Clonar",
    "Clone": "Clonar",
    "Wilds off Count: {}": "Número de comodines: {}",
    "Wilds off Payout: {}": "Pago de comodines: {}"
};