package com.betsoft.casino.mp.movement.generators;


import com.betsoft.casino.mp.model.movement.BezierTrajectory;
import com.betsoft.casino.mp.model.movement.Point;
import com.betsoft.casino.mp.model.movement.Trajectory;
import com.betsoft.casino.mp.model.movement.PossiblePoints;
import com.betsoft.casino.mp.movement.common.SpawnCurvePoint;
import com.dgphoenix.casino.common.util.KryoHelper;
import com.dgphoenix.casino.common.util.Pair;
import com.dgphoenix.casino.common.util.RNG;
import com.dgphoenix.casino.common.util.Triple;
import org.apache.commons.codec.binary.Base64;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BezierCurveGenerator {
    private static final Logger LOG = LogManager.getLogger(BezierCurveGenerator.class);

    static Map<Integer, PossiblePoints> predefinedPoints;

    private final SpawnCurvePoint[] spawningPoints = new SpawnCurvePoint[44];
    int resX;
    int resY;
    double maxEnemyWidth;
    double maxEnemyHeight;
    double Dh;
    double Dw;
    double W;
    double resNorm;

    static final int[][] shiftStartPos = new int[][]{
            {-1, -1}, {-1, 0}, {-1, 1}, {-1, 2}, {-1, 3}, {-1, 4}, {-1, 5}, {-1, 6}, {-1, 7}, {-1, 8}, // left
            {0, 8}, {1, 8}, {2, 8}, {3, 8}, {4, 8}, {5, 8}, {6, 8}, {7, 8}, {8, 8}, {9, 8}, {10, 8}, {11, 8}, {12, 8}, // bottom
            {12, 7}, {12, 6}, {12, 5}, {12, 4}, {12, 3}, {12, 2}, {12, 1}, {12, 0}, {12, -1}, //right
            {11, -1}, {10, -1}, {9, -1}, {8, -1}, {7, -1}, {6, -1}, {5, -1}, {4, -1}, {3, -1}, {2, -1}, {1, -1}, {0, -1} //up
    };

    // coefficients used for 32-point Legendre-Gaussquadrature rule
    static final double[] Ci = new double[]{0.096540089, 0.096540089, 0.09563872, 0.09563872, 0.093844399, 0.093844399, 0.091173879, 0.091173879,
            0.087652093, 0.087652093, 0.083311924, 0.083311924, 0.078193896, 0.078193896, 0.072345794, 0.072345794, 0.065822223, 0.065822223,
            0.058684093, 0.058684093, 0.050998059, 0.050998059, 0.042835898, 0.042835898, 0.034273863, 0.034273863, 0.025392065, 0.025392065,
            0.016274395, 0.016274395, 0.00701861, 0.00701861};
    static final double[] ti = new double[]{-0.048307666, 0.048307666, -0.144471962, 0.144471962, -0.239287362, 0.239287362, -0.331868602,
            0.331868602, -0.421351276, 0.421351276, -0.506899909, 0.506899909, -0.587715757, 0.587715757, -0.663044267, 0.663044267, -0.732182119,
            0.732182119, -0.794483796, 0.794483796, -0.849367614, 0.849367614, -0.896321156, 0.896321156, -0.934906076, 0.934906076, -0.964762256,
            0.964762256, -0.985611512, 0.985611512, -0.997263862, 0.997263862};


    enum DirectionSector {
        I,
        II,
        III,
        IV
    }

    static {
        predefinedPoints = new HashMap<>();
        predefinedPoints.put(1, KryoHelper.deserializeFrom(Base64.decodeBase64("sgEBAGphdmEudXRpbC5BcnJheUxpc/QDAQFjb20uYmV0c29mdC5jYXNpbm8ubXAubW9kZWwubW92ZW1lbnQuUG9pbvTARhVVVVVVVkBeAAAAAAAAAAEBQHDgAAAAAABAUYAAAAAAAAABAUCPvqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQHDgAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCPvqqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCM/AAAAAABwEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAVoAAAAAAAAABAUCKOVVVVVVWwEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAVoAAAAAAAAABAUCHdqqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAVoAAAAAAAAABAUCEtAAAAAAAwEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAVoAAAAAAAAABAUCB8VVVVVVVwEQAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAVoAAAAAAAAABAUCHdqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCKOVVVVVVWQIVAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCM/AAAAAABQIVAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCPvqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAVoAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAW4AAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAYEAAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAYEAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAYsAAAAAAAAABAUCRQKqqqqqrQEQAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAZUAAAAAAAAABAUCRQKqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAZUAAAAAAAAABAUCPvqqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAZUAAAAAAAAABAUCM/AAAAAABwEQAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAYsAAAAAAAAABAUCEtAAAAAAAQIVAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAYEAAAAAAAAABAUCHdqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAYEAAAAAAAAABAUCKOVVVVVVWQIVAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAYEAAAAAAAAABAUCM/AAAAAABQIVAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAYEAAAAAAAAABAUCPvqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAYEAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAZUAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAZUAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAZ8AAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAakAAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAakAAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAbMAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAb0AAAAAAAAABAUCRQKqqqqqrQEQAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAcOAAAAAAAAABAUCRQKqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQIJwAAAAAABAciAAAAAAAAABAUCPvqqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAbMAAAAAAAAABAUCB8VVVVVVVQIVAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAbMAAAAAAAAABAUCEtAAAAAAAQIVAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAbMAAAAAAAAABAUCHdqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAbMAAAAAAAAABAUCKOVVVVVVWQIVAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAbMAAAAAAAAABAUCM/AAAAAABQIVAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAbMAAAAAAAAABAUCPvqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAbMAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAb0AAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAb0AAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAcOAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAciAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAciAAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAc2AAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAdKAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAdeAAAAAAAAABAUCRQKqqqqqrQEQAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAdeAAAAAAAAABAUCRQKqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQH1gAAAAAABAdyAAAAAAAAABAUCPvqqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQGfAAAAAAABAdKAAAAAAAAABAUCB8VVVVVVVQIVAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdKAAAAAAAAABAUCEtAAAAAAAQIVAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdKAAAAAAAAABAUCHdqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdKAAAAAAAAABAUCKOVVVVVVWQIVAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdKAAAAAAAAABAUCM/AAAAAABQIVAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdKAAAAAAAAABAUCPvqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdKAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdKAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdeAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdyAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdyAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAeGAAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAeaAAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAeuAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAeuAAAAAAAAABAUCRQKqqqqqrQEQAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQHSgAAAAAABAfCAAAAAAAAABAUCPvqqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQHcgAAAAAABAeGAAAAAAAAABAUCB8VVVVVVVQIVAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQHNgAAAAAABAeaAAAAAAAAABAUCEtAAAAAAAQIVAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQGzAAAAAAABAeaAAAAAAAAABAUCHdqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQGzAAAAAAABAeaAAAAAAAAABAUCKOVVVVVVWQIVAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQFGAAAAAAABAeaAAAAAAAAABAUCM/AAAAAABQIVAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQFGAAAAAAABAeaAAAAAAAAABAUCPvqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQFGAAAAAAABAeaAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQFGAAAAAAABAeuAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQFGAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQFGAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQGLAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQGfAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQGzAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQG9AAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQHIgAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQEQAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQHNgAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQHSgAAAAAABAfCAAAAAAAAABAUCPvqqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQIHQAAAAAABAdyAAAAAAAAABAUCEtAAAAAAAQIVAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQIEwAAAAAABAdyAAAAAAAAABAUCHdqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQHmgAAAAAABAeGAAAAAAAAABAUCKOVVVVVVWQIVAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQHcgAAAAAABAeGAAAAAAAAABAUCM/AAAAAABQIVAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQHXgAAAAAABAeGAAAAAAAAABAUCPvqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQHDgAAAAAABAeaAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQFGAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQFuAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQHIgAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQHrgAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQIEwAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQIOwAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQIYwAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkCFQAAAAAAAAAEBQIRQAAAAAABAdKAAAAAAAAABAUCM/AAAAAABQIVAAAAAAAAAAQADAQHARhVVVVVVVkCFQAAAAAAAAAEBQIJwAAAAAABAdKAAAAAAAAABAUCPvqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCFQAAAAAAAAAEBQG9AAAAAAABAdeAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCFQAAAAAAAAAEBQFGAAAAAAABAeGAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkCFQAAAAAAAAAEBQFGAAAAAAABAeuAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkCFQAAAAAAAAAEBQHwgAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkCFQAAAAAAAAAEBQIswAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQFARhVVVVVVVkCFQAAAAAAAAAEBQIbQAAAAAABAdKAAAAAAAAABAUCPvqqqqqqrQIVAAAAAAAAAAQADAQFARhVVVVVVVkCFQAAAAAAAAAEBQITwAAAAAABAdKAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQFARhVVVVVVVkCFQAAAAAAAAAEBQFGAAAAAAABAeaAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQFARhVVVVVVVkCFQAAAAAAAAAEBQFGAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQFARhVVVVVVVkCFQAAAAAAAAAEBQITwAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQFAijlVVVVVVkCFQAAAAAAAAAEBQHhgAAAAAABAfCAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAijlVVVVVVkCFQAAAAAAAAAEBQHmgAAAAAABAeGAAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAjPwAAAAAAUCFQAAAAAAAAAEBQHrgAAAAAABAeuAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAjPwAAAAAAUCFQAAAAAAAAAEBQHrgAAAAAABAeGAAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAj76qqqqqq0CFQAAAAAAAAAEBQH1gAAAAAABAeaAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAj76qqqqqq0CFQAAAAAAAAAEBQH1gAAAAAABAdyAAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0CFQAAAAAAAAAEBQH/gAAAAAABAfCAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0CFQAAAAAAAAAEBQH/gAAAAAABAeaAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0CFQAAAAAAAAAEBQH/gAAAAAABAdyAAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0CFQAAAAAAAAAEBQH/gAAAAAABAdKAAAAAAAAABAcBGFVVVVVVWQIVAAAAAAAAAAQADAQFAkUCqqqqqq0CCwAAAAAAAAAEBQH/gAAAAAABAeuAAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAAAQADAQFAkUCqqqqqq0CCwAAAAAAAAAEBQH/gAAAAAABAeaAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0CCwAAAAAAAAAEBQH/gAAAAAABAeGAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0CCwAAAAAAAAAEBQH/gAAAAAABAdyAAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0CCwAAAAAAAAAEBQH/gAAAAAABAdyAAAAAAAAABAcBGFVVVVVVWQIVAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAdeAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAdeAAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAdKAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAc2AAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAc2AAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAciAAAAAAAAABAcBGFVVVVVVWQIVAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAcOAAAAAAAAABAcBGFVVVVVVWQGkAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAcOAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAb0AAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAbMAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAbMAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAakAAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAZ8AAAAAAAAABAcBGFVVVVVVWQIVAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAZ8AAAAAAAAABAcBGFVVVVVVWQF4AAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAZ8AAAAAAAAABAcBGFVVVVVVWQGkAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAZUAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAYsAAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAYsAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAYEAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAW4AAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAW4AAAAAAAAABAcBGFVVVVVVWQIVAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAW4AAAAAAAAABAcBGFVVVVVVWQEQAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAW4AAAAAAAAABAcBGFVVVVVVWQF4AAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAVoAAAAAAAAABAcBGFVVVVVVWQGkAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAW4AAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAYEAAAAAAAAABAcBGFVVVVVVWQIVAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWwEQAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQEQAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQF4AAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQGkAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAW4AAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQIEwAAAAAABAW4AAAAAAAAABAcBGFVVVVVVWQIVAAAAAAAAAAQADAQFAkUCqqqqqq0BeAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWwEQAAAAAAAAAAQADAQFAkUCqqqqqq0BeAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQEQAAAAAAAAAAQADAQFAkUCqqqqqq0BeAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQF4AAAAAAAAAAQADAQFAkUCqqqqqq0BeAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQGkAAAAAAAAAAQADAQFAkUCqqqqqq0BeAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0BeAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAA"), PossiblePoints.class));
        predefinedPoints.put(25, KryoHelper.deserializeFrom(Base64.decodeBase64("jwEBAGphdmEudXRpbC5BcnJheUxpc/QDAQFjb20uYmV0c29mdC5jYXNpbm8ubXAubW9kZWwubW92ZW1lbnQuUG9pbvTARhVVVVVVVkBeAAAAAAAAAAEBQGpAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQGVAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFuAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCPvqqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCM/AAAAAABwEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAVoAAAAAAAAABAUCKOVVVVVVWwEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAVoAAAAAAAAABAUCHdqqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAVoAAAAAAAAABAUCEtAAAAAAAwEQAAAAAAAAAAQADAQHARhVVVVVVVkBeAAAAAAAAAAEBQFGAAAAAAABAVoAAAAAAAAABAUCB8VVVVVVVwEQAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAUYAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAVoAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAVoAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAW4AAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAYEAAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAYEAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAYsAAAAAAAAABAUCRQKqqqqqrQEQAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAZUAAAAAAAAABAUCRQKqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAZUAAAAAAAAABAUCPvqqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkBpAAAAAAAAAAEBQFGAAAAAAABAZUAAAAAAAAABAUCM/AAAAAABwEQAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAYsAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAZUAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAZUAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAZ8AAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAakAAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAakAAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAbMAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAb0AAAAAAAAABAUCRQKqqqqqrQEQAAAAAAAAAAQADAQHARhVVVVVVVkBxgAAAAAAAAAEBQFGAAAAAAABAcOAAAAAAAAABAUCRQKqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQIswAAAAAABAdKAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQHDgAAAAAABAbMAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAb0AAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAcOAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAciAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAciAAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAc2AAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAdKAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAdeAAAAAAAAABAUCRQKqqqqqrQEQAAAAAAAAAAQADAQHARhVVVVVVVkB2gAAAAAAAAAEBQFGAAAAAAABAdeAAAAAAAAABAUCRQKqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdyAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdKAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdeAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdyAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAdyAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAeGAAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAeaAAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAeuAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAeuAAAAAAAAABAUCRQKqqqqqrQEQAAAAAAAAAAQADAQHARhVVVVVVVkB7gAAAAAAAAAEBQFGAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrwEQAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQGzAAAAAAABAeuAAAAAAAAABAUCKOVVVVVVWQIVAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQFGAAAAAAABAeaAAAAAAAAABAUCM/AAAAAABQIVAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQFGAAAAAAABAeaAAAAAAAAABAUCPvqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQFGAAAAAAABAeaAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQFGAAAAAAABAeuAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQFGAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQFGAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQGLAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQGfAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQGzAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQG9AAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQF4AAAAAAAAAAQADAQHARhVVVVVVVkCAQAAAAAAAAAEBQHIgAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQEQAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQHcgAAAAAABAeGAAAAAAAAABAUCM/AAAAAABQIVAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQHXgAAAAAABAeGAAAAAAAAABAUCPvqqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQHDgAAAAAABAeaAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQFGAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQFuAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQHIgAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQHrgAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQIEwAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHGAAAAAAAAAAQADAQHARhVVVVVVVkCCwAAAAAAAAAEBQIOwAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQGkAAAAAAAAAAQADAQHARhVVVVVVVkCFQAAAAAAAAAEBQG9AAAAAAABAdeAAAAAAAAABAUCRQKqqqqqrQIVAAAAAAAAAAQADAQHARhVVVVVVVkCFQAAAAAAAAAEBQFGAAAAAAABAeGAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQHARhVVVVVVVkCFQAAAAAAAAAEBQFGAAAAAAABAeuAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQHARhVVVVVVVkCFQAAAAAAAAAEBQHwgAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQHARhVVVVVVVkCFQAAAAAAAAAEBQIswAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHaAAAAAAAAAAQADAQFARhVVVVVVVkCFQAAAAAAAAAEBQFGAAAAAAABAeaAAAAAAAAABAUCRQKqqqqqrQILAAAAAAAAAAQADAQFARhVVVVVVVkCFQAAAAAAAAAEBQFGAAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQIBAAAAAAAAAAQADAQFARhVVVVVVVkCFQAAAAAAAAAEBQITwAAAAAABAfCAAAAAAAAABAUCRQKqqqqqrQHuAAAAAAAAAAQADAQFAijlVVVVVVkCFQAAAAAAAAAEBQHhgAAAAAABAfCAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAjPwAAAAAAUCFQAAAAAAAAAEBQHrgAAAAAABAeuAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAjPwAAAAAAUCFQAAAAAAAAAEBQHrgAAAAAABAeGAAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAj76qqqqqq0CFQAAAAAAAAAEBQH1gAAAAAABAeaAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAj76qqqqqq0CFQAAAAAAAAAEBQH1gAAAAAABAeGAAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0CFQAAAAAAAAAEBQH/gAAAAAABAfCAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0CFQAAAAAAAAAEBQH/gAAAAAABAeaAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0CFQAAAAAAAAAEBQH/gAAAAAABAdyAAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0CFQAAAAAAAAAEBQH/gAAAAAABAdeAAAAAAAAABAcBGFVVVVVVWQIVAAAAAAAAAAQADAQFAkUCqqqqqq0CCwAAAAAAAAAEBQH/gAAAAAABAfCAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0CCwAAAAAAAAAEBQH/gAAAAAABAeuAAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAAAQADAQFAkUCqqqqqq0CCwAAAAAAAAAEBQH/gAAAAAABAeaAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0CCwAAAAAAAAAEBQH/gAAAAAABAeGAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0CCwAAAAAAAAAEBQH/gAAAAAABAeGAAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0CCwAAAAAAAAAEBQH/gAAAAAABAdyAAAAAAAAABAcBGFVVVVVVWQIVAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAeGAAAAAAAAABAcBGFVVVVVVWQF4AAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAdyAAAAAAAAABAcBGFVVVVVVWQGkAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAdeAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAdeAAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAdKAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAc2AAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAeaAAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0CAQAAAAAAAAAEBQH/gAAAAAABAeaAAAAAAAAABAcBGFVVVVVVWQIVAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAc2AAAAAAAAABAcBGFVVVVVVWQEQAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAciAAAAAAAAABAcBGFVVVVVVWQF4AAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAcOAAAAAAAAABAcBGFVVVVVVWQGkAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAcOAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAb0AAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAbMAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQH/gAAAAAABAbMAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0B7gAAAAAAAAAEBQICQAAAAAABAeaAAAAAAAAABAcBGFVVVVVVWQILAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAakAAAAAAAAABAcBGFVVVVVVWQEQAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAZ8AAAAAAAAABAcBGFVVVVVVWQF4AAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAZ8AAAAAAAAABAcBGFVVVVVVWQGkAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAZUAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAYsAAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAYsAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0B2gAAAAAAAAAEBQH/gAAAAAABAYEAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAW4AAAAAAAAABAcBGFVVVVVVWQEQAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAW4AAAAAAAAABAcBGFVVVVVVWQF4AAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAVoAAAAAAAAABAcBGFVVVVVVWQGkAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0BxgAAAAAAAAAEBQH/gAAAAAABAYEAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWwEQAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQEQAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQF4AAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQGkAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHuAAAAAAAAAAQADAQFAkUCqqqqqq0BpAAAAAAAAAAEBQH/gAAAAAABAYEAAAAAAAAABAcBGFVVVVVVWQIBAAAAAAAAAAQADAQFAkUCqqqqqq0BeAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWwEQAAAAAAAAAAQADAQFAkUCqqqqqq0BeAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQEQAAAAAAAAAAQADAQFAkUCqqqqqq0BeAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQF4AAAAAAAAAAQADAQFAkUCqqqqqq0BeAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQGkAAAAAAAAAAQADAQFAkUCqqqqqq0BeAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHGAAAAAAAAAAQADAQFAkUCqqqqqq0BeAAAAAAAAAAEBQH/gAAAAAABAUYAAAAAAAAABAcBGFVVVVVVWQHaAAAAAAAAA"), PossiblePoints.class));
    }

    public BezierCurveGenerator(int resX, int resY, double maxEnemyWidth, double maxEnemyHeight) {
        this.resX = resX;
        this.resY = resY;
        this.maxEnemyWidth = maxEnemyWidth;
        this.maxEnemyHeight = maxEnemyHeight;
        this.W = Math.max(maxEnemyWidth * 16 / resX, maxEnemyHeight * 9 / resY);
        int len = resX / 16;

        this.Dh = ((9 + 2 * W) / 8) * len;
        this.Dw = ((16 + 2 * W) / 12) * len;

        for (int idx = 0; idx < spawningPoints.length; idx++) {
            spawningPoints[idx] = new SpawnCurvePoint(shiftStartPos[idx][0] * Dw + Dw / 2, shiftStartPos[idx][1] * Dh + Dh / 2);
        }
        this.resNorm = ((double) resX) / 16;
    }

    public Trajectory generateLinear(int enemyTypeId, long baseTime, boolean needUsualTrajectory, PathParam paramByEnemy) {
        ArrayList<Point> points = new ArrayList<>();

        int cntTry1 = 1000;
        int cntTry2 = 200;
        boolean foundTrajectory = false;

        while (cntTry1-- > 0) {
            int startPointIndex = RNG.nextInt(spawningPoints.length);
            while (cntTry2-- > 0) {
                points.clear();
                SpawnCurvePoint spawningPointStart = spawningPoints[startPointIndex];
                SpawnCurvePoint spawningPointEnd = spawningPoints[RNG.nextInt(spawningPoints.length)];
                long timePath = baseTime + RNG.nextInt(10000);
                long startTime = System.currentTimeMillis() + 1000;
                points.add(new Point(spawningPointStart.getX(), spawningPointStart.getY(), startTime));
                points.add(new Point(spawningPointEnd.getX(), spawningPointEnd.getY(), startTime + timePath));
                List<Triple<Double, Double, Double>> listInterSetPoints = getListInterSetPoints(points);
                boolean controlOrientation = paramByEnemy == null || (!paramByEnemy.isControlOrientation() ||
                        checkOrientation(listInterSetPoints, true, points, paramByEnemy));
                boolean checkEndpointSeparation = paramByEnemy == null || checkEndpointSeparation(listInterSetPoints, true, points, paramByEnemy);

                if (controlOrientation && checkEndpointSeparation) {
                    foundTrajectory = true;
                }
            }
            if (foundTrajectory) {
                break;
            }
        }

        Trajectory trajectory = needUsualTrajectory ? new Trajectory(0, points) : new BezierTrajectory(0, points);
        LOG.debug("generateQuadratic, foundTrajectory: " + foundTrajectory + ", trajectory: " + trajectory + ", enemyTypeId: " + enemyTypeId);
        return trajectory;
    }

    public Trajectory generateQuadratic(int enemyTypeId, PathParam paramByEnemy) {
        ArrayList<Point> points = new ArrayList<>();

        PossiblePoints possiblePoints = predefinedPoints.get(enemyTypeId);
        if(possiblePoints != null){
            List<Point> randomPossiblePoints = possiblePoints.getRandomPossiblePoints();
            long timePath = 10000 + RNG.nextInt(10000);
            long startTime = System.currentTimeMillis() + 1000;
            long middleTime = startTime + timePath / 2;
            randomPossiblePoints.get(0).setTime(startTime);
            randomPossiblePoints.get(1).setTime(middleTime);
            randomPossiblePoints.get(2).setTime(startTime + timePath);
            BezierTrajectory bezierTrajectory = new BezierTrajectory(0, randomPossiblePoints);
            LOG.debug("generateQuadratic from randomPossiblePoints, bezierTrajectory: " + bezierTrajectory);
            return bezierTrajectory;
        }

        int cntTry1 = 1000;
        int cntTry2 = 200;
        boolean foundTrajectory = false;
        while (cntTry1-- > 0) {
            SpawnCurvePoint spawningPointStart = spawningPoints[RNG.nextInt(spawningPoints.length)];
            while (cntTry2-- > 0) {
                points.clear();
                SpawnCurvePoint spawningPointEnd = spawningPoints[RNG.nextInt(spawningPoints.length)];
                long timePath = 10000 + RNG.nextInt(10000);
                long startTime = System.currentTimeMillis() + 1000;
                points.add(new Point(spawningPointStart.getX(), spawningPointStart.getY(), startTime));
                points.add(new Point(RNG.nextInt(resX), RNG.nextInt(resY), startTime + timePath / 2));
                points.add(new Point(spawningPointEnd.getX(), spawningPointEnd.getY(), startTime + timePath));

                List<Triple<Double, Double, Double>> listInterSetPoints = getListInterSetPoints(points);

                double lengthAndPoints = points.size() >= 2 ? checkLengthAndPoints(listInterSetPoints, false, points) : 0;
                boolean checkLengthAndPoints = lengthAndPoints >= paramByEnemy.getEffectiveLenPath();
                boolean controlOrientation = !paramByEnemy.isControlOrientation() ||
                        checkOrientation(listInterSetPoints, false, points, paramByEnemy);

                boolean checkEndpointSeparation = checkEndpointSeparation(listInterSetPoints, false, points, paramByEnemy);
                boolean tangentialDirection = checkTangentialDirection(points);
                double curvature = getCurvature(points);
                boolean checkCurvature = curvature <= paramByEnemy.getThresholdCurvature();

                if (checkLengthAndPoints
                        && checkCurvature
                        && tangentialDirection
                        && controlOrientation
                        && checkEndpointSeparation
                ) {
                    foundTrajectory = true;
                    break;
                }
            }

            if (foundTrajectory) {
                break;
            }
        }

        BezierTrajectory trajectory = new BezierTrajectory(0, points);
        LOG.debug("generateQuadratic, trajectory: " + foundTrajectory + ", trajectory: " + trajectory + ", enemyTypeId: " + enemyTypeId);
        return trajectory;
    }

    DirectionSector getDirectionSector(double angle) {
        double piHalf = Math.PI / 2;
        if (angle > -piHalf && angle <= 0) {
            return DirectionSector.I;
        } else if (angle >= 0 && angle < piHalf) {
            return DirectionSector.IV;
        } else if (angle > -Math.PI && angle < -piHalf) {
            return DirectionSector.II;
        } else {
            return DirectionSector.III;
        }
    }

    public boolean checkTangentialDirection(List<Point> basePoints) {
        double dt = 0.001;
        double X0, X1, X2, Y0, Y1, Y2;

        boolean validTangentialDirection = true; // in case the path is linear, always return true
        DirectionSector prev = null;  //

        X0 = basePoints.get(0).getX() / resNorm;
        Y0 = basePoints.get(0).getY() / resNorm;
        X1 = basePoints.get(1).getX() / resNorm;
        Y1 = basePoints.get(1).getY() / resNorm;
        X2 = basePoints.get(2).getX() / resNorm;
        Y2 = basePoints.get(2).getY() / resNorm;

        double Xt0 = X0;
        double Yt0 = Y0;

        for (double t = dt; t <= 1; t += dt) {
            double Xt1 = ((1 - t * (1 - t) * X0 + 2 * t * (1 - t) * X1 + t * t * X2));
            double Yt1 = ((1 - t) * (1 - t) * Y0 + 2 * t * (1 - t) * Y1 + t * t * Y2);
            double angle = Math.atan2(Yt1 - Yt0, Xt1 - Xt0);
            DirectionSector current = getDirectionSector(angle);
            if (prev == null) {
                prev = current;
            } else {
                boolean case1 = (prev.equals(DirectionSector.II) || prev.equals(DirectionSector.III))
                        && (current.equals(DirectionSector.II) || current.equals(DirectionSector.III));
                boolean case2 = (prev.equals(DirectionSector.I) || prev.equals(DirectionSector.IV))
                        && (current.equals(DirectionSector.I) || current.equals(DirectionSector.IV));
                if (!case1 && !case2) {
                    validTangentialDirection = false;
                    break;
                }
            }
            Xt0 = Xt1;
            Yt0 = Yt1;
        }
        return validTangentialDirection;
    }

    public double checkLengthAndPoints(List<Triple<Double, Double, Double>> listInterSetPoints,
                                       boolean isLinear, List<Point> basePoints) {

        //        double dt = 0.001;
        double effective_path_len = 0;

        double X0, X1, X2, Y0, Y1, Y2;

        if (isLinear) {
            X0 = basePoints.get(0).getX();
            Y0 = basePoints.get(0).getY();
            X1 = 0;
            Y1 = 0;
            X2 = basePoints.get(1).getX();
            Y2 = basePoints.get(1).getY();
        } else {
            X0 = basePoints.get(0).getX();
            Y0 = basePoints.get(0).getY();
            X1 = basePoints.get(1).getX();
            Y1 = basePoints.get(1).getY();
            X2 = basePoints.get(2).getX();
            Y2 = basePoints.get(2).getY();
        }

        for (int idx = 0; idx < listInterSetPoints.size() - 1; idx++) {
            Triple<Double, Double, Double> interPointOne = listInterSetPoints.get(idx);
            Triple<Double, Double, Double> interPointTwo = listInterSetPoints.get(idx + 1);
            double t0 = interPointOne.third();
            double t1 = interPointTwo.third();
            double len = 0;
            if (isLinear) {
                double sx0 = (1 - t0) * X0 + t0 * X2;
                double sy0 = (1 - t0) * Y0 + t0 * Y2;
                double sx1 = (1 - t1) * X0 + t1 * X2;
                double sy1 = (1 - t1) * Y0 + t1 * Y2;
                len = Math.sqrt((sx0 - sx1) * (sx0 - sx1) + (sy0 - sy1) * (sy0 - sy1));
            } else {
                for (int n = 0; n < Ci.length; n++) {
                    double t = 0.5 * (t1 - t0) * ti[n] + 0.5 * (t1 + t0);
                    double dXsq2 = Math.pow(t * (X0 - 2 * X1 + X2) + (X1 - X0), 2);
                    double dYsq2 = Math.pow(t * (Y0 - 2 * Y1 + Y2) + (Y1 - Y0), 2);
                    len += 0.5 * (t1 - t0) * Ci[n] * 2 * Math.sqrt(dXsq2 + dYsq2);
                }
            }

            effective_path_len += len;
        }

        return effective_path_len / resNorm;
    }

    public boolean checkEndpointSeparation(List<Triple<Double, Double, Double>> listInterSetPoints, boolean isLinear,
                                           List<Point> basePoints, PathParam paramByEnemy) {
        double X0, X1, X2, Y0, Y1, Y2;
        if (isLinear) {
            X0 = basePoints.get(0).getX() / resNorm;
            Y0 = basePoints.get(0).getY() / resNorm;
            X1 = 0;
            Y1 = 0;
            X2 = basePoints.get(1).getX() / resNorm;
            Y2 = basePoints.get(1).getY() / resNorm;
        } else {
            X0 = basePoints.get(0).getX() / resNorm;
            Y0 = basePoints.get(0).getY() / resNorm;
            X1 = basePoints.get(1).getX() / resNorm;
            Y1 = basePoints.get(1).getY() / resNorm;
            X2 = basePoints.get(2).getX() / resNorm;
            Y2 = basePoints.get(2).getY() / resNorm;
        }

        double dist;

        for (int idx = 0; idx < listInterSetPoints.size() - 1; idx++) {
            Triple<Double, Double, Double> interPointOne = listInterSetPoints.get(idx);
            Triple<Double, Double, Double> interPointTwo = listInterSetPoints.get(idx + 1);
            double t0 = interPointOne.third();
            double t1 = interPointTwo.third();
            double Xt0 = ((1 - t0) * (1 - t0) * X0 + 2 * t0 * (1 - t0) * X1 + t0 * t0 * X2);
            double Yt0 = ((1 - t0) * (1 - t0) * Y0 + 2 * t0 * (1 - t0) * Y1 + t0 * t0 * Y2);
            double Xt1 = ((1 - t1 * (1 - t1) * X0 + 2 * t1 * (1 - t1) * X1 + t1 * t1 * X2));
            double Yt1 = ((1 - t1) * (1 - t1) * Y0 + 2 * t1 * (1 - t1) * Y1 + t1 * t1 * Y2);
            dist = Math.sqrt((Xt1 - Xt0) * (Xt1 - Xt0) + (Yt1 - Yt0) * (Yt1 - Yt0));

            if (dist >= paramByEnemy.getEndpointsDistLimit()) {
                return true;
            }
        }
        return false;
    }

    public boolean checkOrientation(List<Triple<Double, Double, Double>> listInterSetPoints,
                                    boolean isLinear, List<Point> basePoints, PathParam paramByEnemy) {

        double dt = 0.01;
        double X0, X1, X2, Y0, Y1, Y2;

        if (isLinear) {
            X0 = basePoints.get(0).getX();
            Y0 = basePoints.get(0).getY();
            X1 = 0;
            Y1 = 0;
            X2 = basePoints.get(1).getX();
            Y2 = basePoints.get(1).getY();
        } else {
            X0 = basePoints.get(0).getX();
            Y0 = basePoints.get(0).getY();
            X1 = basePoints.get(1).getX();
            Y1 = basePoints.get(1).getY();
            X2 = basePoints.get(2).getX();
            Y2 = basePoints.get(2).getY();
        }

        for (int idx = 0; idx <= listInterSetPoints.size() - 1; idx++) {
            Triple<Double, Double, Double> interPoint = listInterSetPoints.get(idx);
            double t0 = interPoint.third();

            double sx0, sy0, sx1, sy1;
            if (isLinear) { // for a straight line, use the enpoints to estiamte the orientation
                sx0 = X0 / resNorm;
                sy0 = Y0 / resNorm;
                sx1 = X2 / resNorm;
                sy1 = Y2 / resNorm;
            } else {
                sx0 = ((1 - t0) * (1 - t0) * X0 + 2 * t0 * (1 - t0) * X1 + t0 * t0 * X2) / resNorm;
                sy0 = ((1 - t0) * (1 - t0) * Y0 + 2 * t0 * (1 - t0) * Y1 + t0 * t0 * Y2) / resNorm;
                sx1 = ((1 - (t0 + dt)) * (1 - (t0 + dt)) * X0 + 2 * (t0 + dt) * (1 - (t0 + dt)) * X1 + (t0 + dt) * (t0 + dt) * X2) / resNorm;
                sy1 = ((1 - (t0 + dt)) * (1 - (t0 + dt)) * Y0 + 2 * (t0 + dt) * (1 - (t0 + dt)) * Y1 + (t0 + dt) * (t0 + dt) * Y2) / resNorm;
            }

            double beta = Math.atan2(sy1 - sy0, sx1 - sx0) * 180 / Math.PI;  // initial tangential angle

            double alpha1 = paramByEnemy.getAlpha1();
            double alpha2 = paramByEnemy.getAlpha2();
            double alpha3 = paramByEnemy.getAlpha3();
            double alpha4 = paramByEnemy.getAlpha4();
            double alpha5 = paramByEnemy.getAlpha5();
            double alpha6 = paramByEnemy.getAlpha6();
            double alpha7 = paramByEnemy.getAlpha7();
            double alpha8 = paramByEnemy.getAlpha8();

            if (idx == 0) {
                // first check the entry point
                if (sx0 <= 0) { // from west
                    if (!((beta >= -alpha1) && (beta <= alpha2))) {
                        return false; // bad path
                    }
                } else if (sx0 >= 16) { // from east
                    boolean conda = (beta >= -180) && (beta <= -180 + alpha3);
                    boolean condb = (beta >= 180 - alpha4) && (beta <= 180);
                    boolean condc = (beta == 180) || (beta == -180); // we add this because -180 & 180 are same tagnetical angle for our case
                    if (!(conda || condb || condc)) {
                        return false; // bad path
                    }
                } else if (sy0 <= 0) { // from north
                    boolean conda = (beta >= 0) && (beta <= alpha5);
                    boolean condb = (beta >= 180 - alpha6) && (beta <= 180);
                    boolean condc = (beta == 180) || (beta == -180); // we add this because -180 & 180 are same tagnetical angle for our case
                    if (!(conda || condb || condc)) {
                        return false; // bad path
                    }
                } else { // from south
                    boolean conda = (beta >= -alpha7) && (beta <= 0);
                    boolean condb = (beta >= -180) && (beta <= -180 + alpha8);
                    boolean condc = (beta == -180) || (beta == 180); // we add this because -180 & 180 are same tagnetical angle for our case
                    if (!(conda || condb || condc)) {
                        return false; // bad path
                    }
                }
            } else {
                // now check the exit point
                if (sx0 >= 16) { // to east
                    if (!((beta >= -alpha1) && (beta <= alpha2))) {
                        return false; // bad path
                    }
                } else if (sx0 <= 0) { // to west
                    boolean conda = (beta >= -180) && (beta <= -180 + alpha3);
                    boolean condb = (beta >= 180 - alpha4) && (beta <= 180);
                    boolean condc = (beta == 180) || (beta == -180); // we add this because -180 & 180 are same tagnetical angle for our case
                    if (!(conda || condb || condc)) {
                        return false; // bad path
                    }
                } else if (sy0 >= 9) { // to south
                    boolean conda = (beta >= 0) && (beta <= alpha5);
                    boolean condb = (beta >= 180 - alpha6) && (beta <= 180);
                    boolean condc = (beta == 180) || (beta == -180); // we add this because -180 & 180 are same tagnetical angle for our case
                    if (!(conda || condb || condc)) {
                        return false; // bad path
                    }
                } else { // to north
                    boolean conda = (beta >= -alpha7) && (beta <= 0);
                    boolean condb = (beta >= -180) && (beta <= -180 + alpha8);
                    boolean condc = (beta == -180) || (beta == 180); // we add this because -180 & 180 are same tagnetical angle for our case
                    if (!(conda || condb || condc)) {
                        return false; // bad path
                    }
                }
            }
        }

        return true;
    }


    public Point getPointForTime(double t, List<Point> points) {
        double Xt = 0, Yt = 0;
        double X0 = points.get(0).getX();
        double Y0 = points.get(0).getY();
        double X1 = points.get(1).getX();
        double Y1 = points.get(1).getY();
        if (points.size() == 2) { // Linear
            Xt = Math.round(((1 - t) * X0 + t * X1) / 16) * resX;
            Yt = Math.round(((1 - t) * Y0 + t * Y1) / 9) * resY;
        } else if (points.size() == 3) { //Quadratic
            double X2 = points.get(2).getX();
            double Y2 = points.get(2).getY();
            Xt = ((1 - t) * (1 - t) * X0 + 2 * t * (1 - t) * X1 + t * t * X2);
            Yt = ((1 - t) * (1 - t) * Y0 + 2 * t * (1 - t) * Y1 + t * t * Y2);
        }
        return new Point(Xt, Yt, 0);
    }

    private boolean pointIsOutMap(Point point) {
        double x = point.getX();
        double y = point.getY();
        return x < 0 || x > resX || y < 0 || y > resY;
    }

    public List<Triple<Double, Double, Double>> getListInterSetPoints(List<Point> points) {
        ArrayList<Triple<Double, Double, Double>> pointsRes = new ArrayList<>();
        boolean lastPointIsOut = true;
        double dt = 0.001;
        double t = 0;
        while (t <= 1) {
            Point pointForTime = getPointForTime(t, points);
            boolean pointIsOutMap = pointIsOutMap(pointForTime);
            if (pointIsOutMap != lastPointIsOut) {
                lastPointIsOut = pointIsOutMap;
                pointsRes.add(new Triple<>(pointForTime.getX(), pointForTime.getY(), t));
            }
            t += dt;
        }
        return pointsRes;
    }

    public double getCurvature(List<Point> points) {
        double maxCurvature = -1; // initialize it to negative instead of zero
        double dt = 0.001;  // adjust this if it is too small to affect the efficiency
        if (points.size() == 2) {
            maxCurvature = 0;
        } else if (points.size() == 3) {
            double X0 = points.get(0).getX();
            double Y0 = points.get(0).getY();
            double X1 = points.get(1).getX();
            double Y1 = points.get(1).getY();
            double X2 = points.get(2).getX();
            double Y2 = points.get(2).getY();
            double numer = X2 * (Y0 - Y1) + X0 * (Y1 - Y2) + X1 * (Y2 - Y0);
            for (double t = 0; t <= 1; t += dt) {
                double denorm = 2 * Math.pow(Math.pow((X0 - 2 * X1 + X2) * t + (X1 - X0), 2) + Math.pow((Y0 - 2 * Y1 + Y2) * t + (Y1 - Y0), 2), 3. / 2);
                if (denorm != 0) {
                    double cur = Math.abs(numer / denorm); // take the absolution, ignore the convexity and concavity
                    if (cur > maxCurvature) {
                        maxCurvature = cur;
                    }
                }
            }
        }
        return maxCurvature;
    }

    public SpawnCurvePoint getSpawnCurvePointByIndex(int idx) {
        return idx >= 0 && idx < spawningPoints.length ? spawningPoints[idx] : null;
    }


    public PossiblePoints generatePossibleQuadraticPoints(PathParam paramByEnemy) {
        List<List<Point>> res = new ArrayList<>();

        int limitShift = 70;
        List<String> uniqPoints = new ArrayList<>();
        StringBuilder sb = new StringBuilder();
        for (SpawnCurvePoint spawningPointStart : spawningPoints) {
            for (SpawnCurvePoint spawningPointEnd : spawningPoints) {
                for (int middleX = limitShift; middleX < resX-limitShift; middleX += 20) {
                    for (int middleY = limitShift; middleY < resY-limitShift; middleY += 20) {
                        List<Point> points = new ArrayList<>();
                        Point point1 = new Point(spawningPointStart.getX(), spawningPointStart.getY(), 0);
                        Point point2 = new Point(middleX, middleY, 0);
                        Point point3 = new Point(spawningPointEnd.getX(), spawningPointEnd.getY(), 0);
                        points.add(point1);
                        points.add(point2);
                        points.add(point3);
                        sb.setLength(0);
                        sb.append((int) point1.getX()).append("_").append((int) point1.getY()).append("_")
                                .append((int) point3.getX()).append("_").append((int) point3.getY());
                        if (!uniqPoints.contains(sb.toString())) {
                            if (checkPoints(points, paramByEnemy)) {
                                uniqPoints.add(sb.toString());
                                res.add(points);
                            }
                        }
                    }
                }
            }
        }
        return new PossiblePoints(res);
    }


    boolean checkPoints(List<Point> points, PathParam paramByEnemy) {
        List<Triple<Double, Double, Double>> listInterSetPoints = getListInterSetPoints(points);

        double lengthAndPoints = points.size() >= 2 ? checkLengthAndPoints(listInterSetPoints, false, points) : 0;
        boolean checkLengthAndPoints = lengthAndPoints >= paramByEnemy.getEffectiveLenPath();
        if (!checkLengthAndPoints) {
            return false;
        }

        boolean controlOrientation = !paramByEnemy.isControlOrientation() || checkOrientation(listInterSetPoints, false, points, paramByEnemy);
        if (!controlOrientation) {
            return false;
        }

        boolean checkEndpointSeparation = checkEndpointSeparation(listInterSetPoints, false, points, paramByEnemy);
        if (!checkEndpointSeparation) {
            return false;
        }

        boolean tangentialDirection = checkTangentialDirection(points);
        if (!tangentialDirection) {
            return false;
        }

        double curvature = getCurvature(points);
        boolean checkCurvature = curvature <= paramByEnemy.getThresholdCurvature();

        return checkCurvature;
    }
}
