package com.betsoft.casino.mp.model.quests;

public enum QuestType {
    COLLECT_SET_TREASURES,
    COLLECT_GROUP_TREASURES,
    COLLECT_N_TREASURES_SPECIFIC_TYPE,
    COLLECT_N_ANY_TREASURES_FROM_GROUP,
    KILL_N_ENEMIES_SPECIFIC_TYPE,
    KILL_N_ENEMIES_EACH_TYPE_IN_RANDOM_GROUP,
    KILL_N_RANDOM_ENEMIES_IN_RANDOM_GROUP,
    KILL_N_TIMES_EACH_ENEMY,
    KILL_ONE_RANDOM_GOD,
    KILL_ALL_GODS,
}
