export const WEAPONS = {
	DEFAULT:					-1,
	RICOCHET:					3, //LASER
	PLASMAGUN:					4, //INSTAKILL
	MINELAUNCHER:				5,
	RAILGUN:					6,
	ARTILLERYSTRIKE:			7,
	FLAMETHROWER:				9,
	CRYOGUN:					10,
	LIGHTNING:					13,
	NAPALM:						14,
	NUKE:						15,
	HIGH_LEVEL: 				16,
	ARTILLERYSTRIKE_POWER_UP:	17,
	FLAMETHROWER_POWER_UP:		18,
	CRYOGUN_POWER_UP:			19,
	RICOCHET_POWER_UP:			20,
	INSTAKILL_POWER_UP:			21
};