package com.dgphoenix.casino.common.web.login.apub;

public interface APUBConstants {

    /*
     * params and statuses for AP->lobby protocol
     */
    String STATUS_SUCCESS = "SUCCESS";
    String STATUS_FAIL_GENERIC_ERROR = "FAIL_GENERIC_ERROR";
    String STATUS_FAIL_GAMEID_INVALID = "FAIL_GAMEID_INVALID";
    String STATUS_FAIL_GAMESESSIONID_INVALID = "FAIL_GAMESESSIONID_INVALID";
    String STATUS_FAIL_USERNAME_INVALID = "FAIL_USERNAME_INVALID";
    String STATUS_FAIL_UNFINISHEDGAME_ERROR = "FAIL_UNFINISHEDGAME_ERROR";
    String STATUS_FAIL_INSUFFICIENT_FUNDS = "FAIL_INSUFFICIENT_FUNDS";
    String STATUS_FAIL_BLACKLIST_USER = "FAIL_BLACKLIST_USER";
    String STATUS_FAIL_GAMESESSIONID_ALREADY_CLOSED = "FAIL_GAMESESSIONID_ALREADY_CLOSED";
    String STATUS_FAIL_LOGIN_INVALID = "FAIL_LOGIN_INVALID";
    String STATUS_FAIL_USER_ALREADY_LOGGEDIN = "FAIL_USER_ALREADY_LOGGEDIN";
    String STATUS_FAIL_NOT_ALLOW_CASINO = "FAIL_NOT_ALLOW_CASINO";

    /*
     * params and statuses for lobby->gs1 protocol
     */
    String PARAM_GAMEID = "gameId";
}
